### ISSUE TITLE
Fix missiles exploding against the sky ceiling

### ISSUE THREAD

**Issue by AXDOOMER** [Russian-Doom/russian-doom#10]
This is something that I had fixed in my port while experimenting a long time ago (but removed later for compatibility) and I believe it would fit inside your port's philosophy: https://github.com/AXDOOMER/doom-vanille/commit/35fd277d2e02d934431367e2655596b8079dc002

**Comment by JNechaevsky** [comment]
Oh, this looks interesting, thanks! Committed here: https://github.com/JNechaevsky/russian-doom/commit/6bf2674e01d7f1c16752baf9fc76c588d5850cdd

Interesting fact: without `(singleplayer)` internal demos was broken only in DOS version, major project was completely okay with this. But just to be 1000% sure that it will not break any internal demos, I have defined it strictly for `(singleplayer)`.
