### ISSUE TITLE
[Doom 1] Add widescreen friendly backgrounds

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#106]
It takes about 5 minutes to make a draft, and will take about 30-60-90 minutes for each background to be pixel-polished.

Some examples of 426x200 drafts:

![DOOM04](https://user-images.githubusercontent.com/21193394/56688345-2d962480-66e1-11e9-9363-dd6646bc0a2a.png)

![DOOM06](https://user-images.githubusercontent.com/21193394/56688359-338c0580-66e1-11e9-8b48-ad1f5525eb5b.png)

![DOOM07](https://user-images.githubusercontent.com/21193394/56688369-3981e680-66e1-11e9-8957-346e77c5955c.png)

**Comment by JNechaevsky** [comment]
Maybe it's not a bad idea after all.

![DOOM49](https://user-images.githubusercontent.com/21193394/56693470-34c32f80-66ed-11e9-89c2-d855fabe6dd0.png)

**Comment by JNechaevsky** [comment]
![DOOM51](https://user-images.githubusercontent.com/21193394/56845293-9808b980-68c7-11e9-98c3-74381ecc7fa9.png)

**Comment by JNechaevsky** [comment]
Rerendered. 

![DOOM52](https://user-images.githubusercontent.com/21193394/56846902-7d413f80-68dd-11e9-8f81-5632fa0056f2.png)

**Comment by fabiangreffrath** [comment]
What the...? How do you extend these graphics and why do they look so good?

**Comment by JNechaevsky** [comment]
No magic here either. :) In some places I'm using "stamping" of existing parts of the picture, and placing them to the side parts. CREDITS screen is recreated from scratch. I can record a video if you wish, watching a progress will be quite fun.

**Comment by JNechaevsky** [comment]
![DOOM54](https://user-images.githubusercontent.com/21193394/56851750-69b4c980-691b-11e9-9666-201517ca923c.png)

**Comment by JNechaevsky** [comment]
![Untitled-1](https://user-images.githubusercontent.com/21193394/56852538-50187f80-6925-11e9-8242-9c3b9f8f8e08.png)

**Comment by JNechaevsky** [comment]
![DOOM73](https://user-images.githubusercontent.com/21193394/56862840-d8dffb80-69b7-11e9-9abb-a946ba38cb3c.png)

**Comment by fabiangreffrath** [comment]
Impressive, I was looking forward to this one! Remember, this was the cover for the demo tape I recorded with my band way back in 1999. :grin:

**Comment by JNechaevsky** [comment]
Thanks! Sure I remember :) Phew, this seems to be all of them, now Doom I is truly moved to "Full HD".

Now starts part №3 - extremely close looking and polishing of all of them. Again. :cold_sweat:
And only after that I will be ready to make a commit. 

Ah yes, my favorite part, HELP1&2.

![DOOM75](https://user-images.githubusercontent.com/21193394/56863115-3590e580-69bb-11e9-932e-3b3f13b36a46.png)

TODO: skull placement should be fixed.
![DOOM74](https://user-images.githubusercontent.com/21193394/56863118-39246c80-69bb-11e9-8779-eb465b712f57.png)

**Comment by JNechaevsky** [comment]
No, this wasn't the end, there is still a CREDIT screen from shareware/registered versions:

![CREDIT](https://user-images.githubusercontent.com/21193394/56863491-6f63eb00-69bf-11e9-888a-82613b0dd4dd.png)

I was never lucky to find a source for gray vine background, and this screen is a bit rare, so I'm free to recreate it from scratch using a W106_1 patch from Doom 1 (in 4:3 gray vine was same in translated version):

![CREDITS](https://user-images.githubusercontent.com/21193394/56863541-16e11d80-69c0-11e9-9a5a-6743e8c4dd3c.png)

_____

Interestingly, early versions of shareware (0.99 - 1.25 Cybex) was having a mention about NeXT computer:

0.99
![CREDIT](https://user-images.githubusercontent.com/21193394/56863584-d33ae380-69c0-11e9-9d1b-99853f40a3ee.png)


1.1 - 1.25 Cybex:
![CREDIT](https://user-images.githubusercontent.com/21193394/56863578-bd2d2300-69c0-11e9-8af0-77d44bad9138.png)

1.4 and higher:
![CREDIT](https://user-images.githubusercontent.com/21193394/56863589-e64db380-69c0-11e9-8c0b-0933de311a48.png)
