### ISSUE TITLE
Apply brightmap for explossive barrel

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#107]
I need a small experiment - apply brightmap to the explosive barrel, same I was done in Yaguar:

![Untitled-1](https://user-images.githubusercontent.com/21193394/56860556-834c2480-69a0-11e9-9205-d0434b78fc90.png)

It's a `dimmed_items`, i.e. green color is not in full possible bright. But have to careful by two reasons:
* Yaguar is using different, gloomy palette.
* On maps like Barrels o' Fun high amount of lit barrels may not look so good.

**Comment by JNechaevsky** [comment]
:heart_eyes: (Doom 1)

![DOOM62](https://user-images.githubusercontent.com/21193394/56860756-b55e8600-69a2-11e9-8c23-acc695f5e690.png)

:worried: (Doom 2)

![DOOM63](https://user-images.githubusercontent.com/21193394/56860739-9a8c1180-69a2-11e9-9186-6d0fce6f49a7.png)

**Comment by fabiangreffrath** [comment]
Wow, this looks great -- even in Doom 2 IMHO.

**Comment by JNechaevsky** [comment]
@fabiangreffrath thanks, so be it! I can't suggest it for you, because in full brightness, slime is looking too agressive: 

![DOOM68](https://user-images.githubusercontent.com/21193394/56861032-b2b16000-69a5-11e9-8826-8b9e9e1d5c0f.png)

**Comment by JNechaevsky** [comment]
...even on standard Doom palette, where colors have a lesser contrast :(
These colors are absolutely same to Crispy renderer with gamma-correction OFF.

![DOOM70](https://user-images.githubusercontent.com/21193394/56861093-74687080-69a6-11e9-879c-e0228714e849.png)

Oh, there are some lit pixels on metal area, so I'll have to make a new one bmap for barrels.

**Comment by JNechaevsky** [comment]
Implemented in https://github.com/JNechaevsky/russian-doom/commit/ec64909737a1694d93e88d0d97e64c5c22ab7c5e.

**Comment by fabiangreffrath** [comment]
> Oh, there are some lit pixels on metal area, so I'll have to make a new one bmap for barrels.

I have the `greenonly3` table for this in Crispy. :wink:

**Comment by JNechaevsky** [comment]
Uh-oh, just tried `greenonly3` (I'm also having it) - yeah, it's working fine. I'm just afraid that using by a full bright, barrels will be annoyingly bright. 

Hm, I remember that while your very first implementation, you was using a "half-bright", not "full-bright" approach. Maybe it is possible to implement back somehow, without much job in the code? At least for barrels.

Anyways, here's my barrel brightmap in all it's glory. :no_mouth:
![BRTMAP11](https://user-images.githubusercontent.com/21193394/56863667-0cc01e80-69c2-11e9-8d2d-b9362c64e776.png)

**Comment by fabiangreffrath** [comment]
That burning barrel in the background of your doom 2 shot, is it brightmapped or is this already a fulbright sprite?

**Comment by JNechaevsky** [comment]
Sadly, it's a fullbright sprite.

![DOOM76](https://user-images.githubusercontent.com/21193394/56864598-0a16f680-69cd-11e9-8fa3-e9607280259c.png)

But perhaps, I should try to make a metal colors half-brighted, probably it will be a cool effect. Thanks for idea!

**Comment by JNechaevsky** [comment]
@fabiangreffrath, not very good, metal is too dark. Probably, metal should be half-brighted...

Before:
![DOOM99](https://user-images.githubusercontent.com/21193394/57034974-9a696b80-6c59-11e9-8808-8cf17feccb66.png)

And after:
![DOOM98](https://user-images.githubusercontent.com/21193394/57034998-a8b78780-6c59-11e9-9016-79644d25792c.png)

**Comment by JNechaevsky** [comment]
Here, all three possible combinations. I think "halfbright" approach is neat? Howdy you think?

![Untitled-1](https://user-images.githubusercontent.com/21193394/57035577-12846100-6c5b-11e9-9762-b031d5804b3e.png)

**Comment by fabiangreffrath** [comment]
Hm, I don't think the difference is too compelling to change anything at all.

**Comment by JNechaevsky** [comment]
But there is a difference. :) I was totally excited by watching how lighting is blinking on dark metal in this area ([screenshot](https://user-images.githubusercontent.com/21193394/57038059-9b060000-6c61-11e9-8c69-feea1c3a763a.png)). Too bad that burning barrel is not oftenly appears in Doom II levels, but there are still TNT and Plutonia.
