### ISSUE TITLE
Hexen: possible crash after trowing a flechette in tall sector

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#112]
On Seven Portals. What the...
```
Thread 1 "russian-hexen" received signal SIGSEGV, Segmentation fault.
P_PointOnLineSide (x=-3060273, y=-42059866, line=0x0) at p_maputl.c:61
61	    if (!line->dx)
```
![Снимок экрана_2019-05-05_17-54-50](https://user-images.githubusercontent.com/21193394/57195790-3eeff400-6f5f-11e9-93de-f4c87632f5f3.png)

**Comment by JNechaevsky** [comment]
Pitto! It's a vannia bug, can be reproduced in Chocolate Hexen. Saved game: [hexndata.zip](https://github.com/JNechaevsky/russian-doom/files/3145673/hexndata.zip)

**Edit:** but DOS version is not crashing. :flushed:

**Comment by fabiangreffrath** [comment]
Could you please move this to the Chocolate tracker and request that the DOS behavior be emulated?

**Comment by JNechaevsky** [comment]
Ah, sure. DOSBox console output remains silent about memory & etc., probably because I have missed something. Oh well, let's move on.

**Comment by JNechaevsky** [comment]
I really have no any idea how to fix it and why it happening. Maybe it's not a `P_PointOnLineSide` issue, something bad happening earlier...

Closing, further investigation moved to: https://github.com/chocolate-doom/chocolate-doom/issues/1160
