### ISSUE TITLE
Heretic: sound playback is extremely low

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#114]
Sound playback in Heretic is very quiet. It seems sounds are playing at half their normal volume. Checked with DOS Heretic and Chocolate Heretic, and the sounds are louder.

**Comment by JNechaevsky** [comment]
Hello @hfc2x and thanks for feedback!

Hmm, I have never compared before, but yeah, volume is definitely different between DOS version. Sadly, it does not seems to be fixable in current released version, but in upcoming version I will use libsample rate which allow allow to set internal volume scaling to something more close to vanilla.

Not sure about release date, but I can post a dev build in the evening.

**Comment by JNechaevsky** [comment]
Here, could you please try this dev build without your existing config files?

* https://drive.google.com/file/d/1B1zFOBt9ooCH65Tr8qRcOMivU9nalip2/view?usp=sharing

I've made sound volume values mostly close to vanilla executable. There is now also widescreen versions of Heretic and Hexen, which probably you will be interested to check out.

**Comment by hfc2x** [comment]
Okay, I deleted my config files and all, and reconfigured it. Heretic sounds play perfect now. I tested all executables, and they're fine, however I tried to load an older save with this new version of Heretic, and saves are broken.

[Htic saves.zip](https://github.com/JNechaevsky/russian-doom/files/3164711/Htic.saves.zip)

The attached files are 2 save files created with Russian Heretic. Hticsav0.hsg was created with version 3.1a, and it's both Vanilla and Chocolate compatible. However, it crashes this dev build without any messages. Hticsav1.hsg was created with this dev version, and it crashes all Vanilla, Choco and Russian Heretic 3.1a, with a "P_UnarchiveSpecials:Unknown tclass 20 in savegame" error.

Hexen and Doom saves are unaffected, and they're all compatible.

**Comment by JNechaevsky** [comment]
Oh, savegame backwards compatibility is a huge problem. :)

I was expecting Doom saves from previous version will crash, because I have removed custom objects of colored blood and corpses, now they are using standard objects with color translation.

In Heretic, this must be because of introduced "Total time", which is now also writing in savegame, and thus, savegame structure is modified, making previous versions incompatible.

Also, RD's savegames are not compatible with Vanilla and Chocolate, none of three games.

**Comment by hfc2x** [comment]
Curious that saved games work. I didn't actually expect Russian Doom saves working in Vanilla, but I expected I could use saves from a previous version of Russian Doom to work. Interestingly, Russian Hexen saves _do_ work in Vanilla, although the viewheight is saved wrong, but there are no problems other than that.

If there is no planned backwards compatibility, do you plan on changing the saved file names or extensions? I think that could help with the confussion. Also to discourage players from loading Russian Hexen saves with Vanilla Hexen, changing the save directory changing to something different from "HEXNDATA" could also help.

**Comment by hfc2x** [comment]
By the way, I found out that in the 3.2 executable you uploaded to Google Drive, the bug is not fixed. The sound volume is now linked to the music volume, and scales accordingly. Setting the music to max makes the sound effects play at the intended volume, but if you lower the music volume, the sound effects lower too. In fact, setting the music volume to 0 turns off all the sound in the game. At higher music volumes, the sound and effects play normally, but lowering the music volume makes the sounds go quiet very fast, with the music sounding much louder than the game sounds at lower volumes.

**Comment by JNechaevsky** [comment]
That's really odd, I can't reproduce it, in none of three games. Are you using OPL synth for music playing? Maybe there is some kind of automatic volume control software on your system?

As about changing savegame extensions - sounds like a good idea! Are these extensions looking good?
- `.rdm` for Doom
- `.rht` for Heretic
- `.rhx` for Hexen

Maybe a moving all saves to subfolder `saves` will also be good idea for keeping main directory clean.

**Comment by hfc2x** [comment]
Actually, I'm using Native MIDI for the music. I'm playing on Windows 10 64-bit if that matters. I attached my config file for Russian Heretic 3.1a (because it also happens in that version). I changed the extension from INI to TXT, because Github didn't let me upload it otherwise.
[russian-heretic.txt](https://github.com/JNechaevsky/russian-doom/files/3195661/russian-heretic.txt)

Regarding extensions, I think it's fine. As long as they're different so people don't get confused, it's all good.

**Comment by JNechaevsky** [comment]
> Actually, I'm using Native MIDI for the music.

That's explains everything. :) It was a native problem/bug of Windows Vista and higher, where, roughly speaking, MIDI playback and WAVE playback was made through one system channel, and thus, was having one volume.

I was never playing much with MIDI synth, always proffering OPL, but even a brief test reveal that problem. Introduced small app `midiproc.exe` in Chocolate Doom solved this issue, so I've copied over this approach, and now MIDI volume bug seems to be fixed in all three games. 

I will upload new build soon, just need to make some changes in rewritten in-game Options menu in Doom - few variables becomes _dangerous_ after turning into hot swappable.

**Comment by JNechaevsky** [comment]
Here's a dev build with midiproc executable: 
* https://drive.google.com/file/d/1zw-XkufwLaV2NTbOCw9xMsBrMxqEzblq/view?usp=sharing

Please note, it's pretty stable, but some things haven't polished yet. Savegame extensions and placement haven't changed for now.

**Comment by hfc2x** [comment]
Okay, I'd say that the issue is fixed now!

This is unrelated, but I suggested it in another thread: do you plan on adding "use inventory" as a bindable mouse action? It would be very useful for both Heretic and Hexen.
