### ISSUE TITLE
Doom: overhaul options menu

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#115]
Maybe one day. Should use custom, unchangeable graphics or custom big font to keep original design. Menu elements and items are:

**Video**
- Fullscreen mode [on / off]
- Fix aspect ratio [on / off]
- Uncapped FPS [on / off]
- Smooth pixel scaling [on / off]
- Show disk icon [on / off]
- Software rendering [on / off] (possible w/o restarting?)

**Display**
- Screen size [slider]
- Gamma-correction [slider]
- Detail level [high/low]
- Messages [on/off]

**Audio**
- SFX volume [slider]
- Music volume [slider]
- Sound mode: [stereo/mono]

**Controls**
- Mouse sensitivity [slider]
- Mouse acceleration [slider] // ever used?
- Mouse threshold [slider] // ever used?
- Mouse look [on/off]
- Always run [on/off]

**Gameplay features**
- All the optional features on 2-3 pages (small font only)

**Development / Experimental** // needed?
- Disable wiping
- Disable flats rendering

... or ... **Vanilla mode:** [on/off]

**End Game**
**~Language: [Russian / English]~** (not sure... not really easy)

**Comment by JNechaevsky** [comment]
I'll probably will follow approach of GZDoom 4.x versions, where main menu, skill level, episode selection and save/load menus are still using `M_` graphical patches, while the rest of in-game menus are using custom font.

Still, my custom menu font will be a standard Doom big font. Thinking about _"what will happen if mod will be loaded"_ explodes my mind already...

**Comment by JNechaevsky** [comment]
@fabiangreffrath this is what I was having in my head month ago, but now it is obvious - I can't suggest it for Crispy, because the difference is too huge. Hovewer, can you look at menu items? Maybe you'll find something interesting.

Most of things are working already, but there is still a lot of work to do.

![DOOM00](https://user-images.githubusercontent.com/21193394/57485180-b3a29580-72b3-11e9-87ae-9e2a36885cc4.png)
![DOOM01](https://user-images.githubusercontent.com/21193394/57485181-b3a29580-72b3-11e9-8bac-ef7e8249d999.png)
![DOOM02](https://user-images.githubusercontent.com/21193394/57485182-b3a29580-72b3-11e9-9abb-85229182b217.png)
![DOOM03](https://user-images.githubusercontent.com/21193394/57485183-b3a29580-72b3-11e9-96ae-3a19ed90ea89.png)
![DOOM04](https://user-images.githubusercontent.com/21193394/57485186-b43b2c00-72b3-11e9-90b9-e46f8415106b.png)

**Comment by fabiangreffrath** [comment]
Looks great, very clean and tidied up design! 

What does "Video Renderer: GPU" mean? I mean, what are the other alternatives?

And, since you ask for my opinion, currently I prefer not to have menu entries for options which have a key binding (e.g. Always Run or Gamma) or for which there is a dedicated entry in the Setup tool (e.g. Fullscreen).

**Comment by JNechaevsky** [comment]
Thanks! I'm still polishing it, but real nightmare comes with Russian strings, which are: 1) much longer than English sometimes, 2) I'm trying to don't use a slang or terms, preferring to have a clean language. But that's another story. :)

As about Always Run - this is mostly a place holder, maybe it is worth to remove it and rename whole menu to something like "Mouse Sensitivity". 

Gamma correction is needed, because by using a slider, it it possible to cycle through not only forward, but also backward, and since I have a 18 levels, it's kinda handy.

CPU / GPU rendering is a `force_software_renderer`, a strictly hidden variable in Chocolate Doom. When it's set to `1`, all graphical calculations are made through CPU (and of course, engine start to consume much CPU usage), but the most interesting part here - if I remember correctly, this way it is possible to run the game even on "Standard VGA controller", at least on Windows. 

I have tried it almost a 1.5 years ago, and this seems to the the only way to run game on Windows XP (@bradharding, this part probably will be interesting for you). Definitely need to double check at least on Virtual machine, but I still have a real PC with XP, hidden somewhere deep inside in my wardrobe.

**Comment by JNechaevsky** [comment]
P.S. Ah yes, about Fullscreen. I was pretty surprised, that "Fullscreen" is not only a variable, hot-switching is require sending keys to SDL, which I haven't figured out how to do yet. I think, everyone nowadays knows about `Alt/Cmd + Enter`, so yeah, maybe it is worth to remove. 

Removing will also save me from some headache about keys sending. :smile:

**Comment by JNechaevsky** [comment]
@fabiangreffrath, I have a bad feeling, that I'm starting to copy over Crispness menu too much, especially in "next / prev" elements. Vertical scrolling could make a difference, but:
1. It's not common for traditional Doom menu.
2. Not sure how to implement it.

I'm totally in love with this layout, but don't want to _steal_ it from you. So I would like to ask openly - don't you have anything against, if I'll use Crispy-styled layout?

![DOOM10](https://user-images.githubusercontent.com/21193394/57548170-fa05fc00-7368-11e9-8f46-1ce96375900e.png)

**Comment by fabiangreffrath** [comment]
Please feel free to take whatever you need from my code. The license is free and it's meant like this. All I am asking for is proper attribution. :wink:

**Comment by JNechaevsky** [comment]
And thank you as always! This time I was meaning slightly different thing, not a code (honestly, I've just taken your `I_ReInitGraphics` and verified some things), but the Idea, Shape of Crispness menu, which is slightly modified and applied to new template:

![DOOM18](https://user-images.githubusercontent.com/21193394/57565788-3880d280-73cc-11e9-837c-f6d0d284a4d7.png)

Using some kind of background will give some free vertical space, but watching how bmaps or HUD is changing colors in hot mode is a joy, comparable to the child's one. :relaxed:

I wonder if newly introduced `CR_DARKRED` can be used for some monsters, which blood is darken... 
Probably not, not good idea. Blood splats are not only "visual blood", they are also "visual feedback" of hitting monsters rather than walls, and too dark blood is hardly visible. This was my mistake while making dark green blood for Barons, alas, but good thing we made bright green blood better.
