### ISSUE TITLE
Make a MSYS build with proper UTF-8 console output

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#117]
First part to make console output appears:

**configure.ac**
```
if test "$GCC" = "yes"
then
        WARNINGS="-Wall -Wdeclaration-after-statement -Wredundant-decls"
---        CFLAGS="-O$OPT_LEVEL -g $WARNINGS $orig_CFLAGS"
+++        CFLAGS="-O$OPT_LEVEL -g $WARNINGS $orig_CFLAGS -mconsole"
fi
```

Next, UTF-8 charset must be set, otherwise console output will use CP866 codepage ([screenshot](https://user-images.githubusercontent.com/21193394/57733183-956bd980-76a7-11e9-8092-bc4b9df54410.png)). It can be fixed by starting RD from another console with following commands:

```
chcp 65001
russian-doom.exe
```

And viola, proper char in console ([screenshot](https://user-images.githubusercontent.com/21193394/57733287-d8c64800-76a7-11e9-91fc-f52bc45464d0.png)).

I wonder is there a way to display a proper UTF-8 by default, without `chcp` command... Or maybe I should just create a batch file, this is only for development purposes anyway.

**Comment by JNechaevsky** [comment]
Interesting, MSYS is not showing further output after sound init, but gives some info about SDL ([screenshot](https://user-images.githubusercontent.com/21193394/57734283-3bb8de80-76aa-11e9-999d-ad2345309517.png)).

**Comment by JNechaevsky** [comment]
Looks likes, there is one and only reasonable choice for Windows console output: 
```
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
````

**Comment by JNechaevsky** [comment]
Fixed via https://github.com/JNechaevsky/russian-doom/commit/8a89d024b21aaf2e4b5069809f43364b89e226c8 ([screenshot](https://user-images.githubusercontent.com/21193394/57950188-37c9ce00-78ef-11e9-9e00-c27549a47aec.png)). О, да! But I wonder is there a way to make this console optional... Probably not.

**Comment by JNechaevsky** [comment]
> But I wonder is there a way to make this console optional... Probably not.

Actually, it does:

```
{
    AllocConsole();
    freopen("CONIN$", "r",stdin); 
    freopen("CONOUT$","w",stdout); 
    freopen("CONOUT$","w",stderr);  

    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
}
```

Any by using this approach GCC flag ` -mconsole` is no longer needed. :flushed:
I should introduce `-console` command line parameter, or make console default for `-devparm`

**Comment by JNechaevsky** [comment]
@fabiangreffrath I've got a raw idea. How about something like this?

![Untitled-1](https://user-images.githubusercontent.com/21193394/57957479-14aa1900-7905-11e9-8b04-726829cc1d28.png)

It's a mockup. I'm also not sure about same approach of console coloring for Linux, Windows and other OSes...

**Edit:** I'm playing around with:
```
SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), FOREGROUND_BLUE | FOREGROUND_INTENSITY);
```
...but it seems to be Windows-only specific.

**Comment by JNechaevsky** [comment]
@fabiangreffrath actually... Having just colored title is cool, but not very useful (and probably dangerous on Linux, where console may be initially different by using non-dark backgound). But the console on Windows can be really helpful, especially for Crispy, where you have added some useful information about mapping errors. Most important: it can be optional, not necessary with `-devparm` mode.

AFAIR, we was having some talks with Chocolate crew about missing `stderr.txt` after going to SDL2, but now it is blazingly simple, I've got all the code up and running, so I can explain pretty much everything.

Should I post a suggestion?

**Comment by fabiangreffrath** [comment]
> Should I post a suggestion?

You have already done so, but not at the right location. :stuck_out_tongue_winking_eye: Yes, please take this to the Choco tracker, preferably with a patch or as a PR. Thanks!

**Comment by JNechaevsky** [comment]
Excellent! I'll post a suggestion in the evening. Not sure I will provide a PR or patch - still don't know how to use a `diff`, and not sure which approach (`-devparm` or `-console`) will be chosen, but I'll try to explain what and where should be added. There is nothing hard, just a few lines of simple code, guarded with `#ifdef _WIN32`.
