### ISSUE TITLE
[TNT] Add widescreen friendly backgrounds

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#118]
Oh no, not again! :anguished:

**Comment by JNechaevsky** [comment]
Dyavolyuciya! :smiling_imp:

![DOOM58](https://user-images.githubusercontent.com/21193394/58752256-a47ac600-84b4-11e9-8b51-5945e6beaafe.png)

**Comment by JNechaevsky** [comment]
**Interpic**

![DOOM66](https://user-images.githubusercontent.com/21193394/58752672-c7f53f00-84bb-11e9-8992-9db5b9c5d846.png)

**Comment by JNechaevsky** [comment]
**Help**

![DOOM73](https://user-images.githubusercontent.com/21193394/58752972-916df300-84c0-11e9-83a2-3f6ef4739a81.png)

**Credits**

![DOOM74](https://user-images.githubusercontent.com/21193394/58752974-99c62e00-84c0-11e9-8e35-bf8f05f6f792.png)

**Comment by JNechaevsky** [comment]
And finally, **BossBack** :blue_heart:

![DOOM71](https://user-images.githubusercontent.com/21193394/58752978-aba7d100-84c0-11e9-9bfe-769df1d5cb93.png)

Mockup version: [BOSSBACK_mockup.png](https://user-images.githubusercontent.com/21193394/58753006-08a38700-84c1-11e9-95e3-952225580255.png)

**Comment by fabiangreffrath** [comment]
Great job! :+1:

**Comment by JNechaevsky** [comment]
@fabiangreffrath thanks! Sadly, these was a last ones. :/
