### ISSUE TITLE
Implement 'use artifact' mouse button

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#121]
As suggested by @hfc2x.

**Comment by fabiangreffrath** [comment]
This should at least get suggested upstream at choco.

**Comment by JNechaevsky** [comment]
Sure, gladly. Brief test shows that mouse events are handled a bit different - I've got a proper behavior while mouse button is pressed, but if I move mouse a bit, artifact usage code start to invoking again. No idea for now what to do. :expressionless:
