### ISSUE TITLE
Heretic: overhaul options menu

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#123]
More nightmares comes true...

![HTIC02](https://user-images.githubusercontent.com/21193394/58903747-cff8ed00-870e-11e9-91bc-8d64a2ff67f0.png)

**Comment by JNechaevsky** [comment]
![HTIC06](https://user-images.githubusercontent.com/21193394/59056684-6a893580-88a1-11e9-841c-b116e8e7e035.png)

White digits are looking bad, too notable, non in harmony with dark green big font. I need more color translation tables.

**Comment by JNechaevsky** [comment]
Gameplay features prototype.

![HTIC10](https://user-images.githubusercontent.com/21193394/59066382-9c0cfb80-88b7-11e9-9457-62726acce1d8.png)

Couple of things to do:
* Write headers (Visual, Tactical) by yellow color.
* Colorize item selector with cyan-to-red color, to make it same to standard red menu arrow.
* Colorize `on` by green color, `off` by red color.
* There are only two pages, worth to change "Next" to something? Also yellow color.

**Comment by JNechaevsky** [comment]
Seems to be a final implementation. Will use `next page` and `previous page`, thanks theleo_ua for suggestion!

![HTIC11](https://user-images.githubusercontent.com/21193394/59133738-9da2f600-8981-11e9-9047-150e02707dee.png)

**Comment by fabiangreffrath** [comment]
Looks great!

**Comment by JNechaevsky** [comment]
Thanks for your opinion, it's always valuable for me!

I was planning to finish it today, but we have a +31° at Celsius (it's something deffinitly above normal for Russia), so I simply can't find any will to make single line of code. Thinking about moving with notebook into the fridge. So hot, that it feels like a Hell on Earth is coming! :fire:

**Comment by JNechaevsky** [comment]
@fabiangreffrath ah yes, one more important thing I've totally forgot to say. Using some kind of background will allow to place few more lines, which are will not be drawn on the status bar. But I'm not using it not because of necessity of status bar redrawing / `inhelpscreens` stuff, nope - an ability to see how b-maps, fake contrast and colored blood are changing in "live" mode is an awesome feeling. :)

Jaguar is a small exception, because status bar there is 40px tall, and just few pixels will be placed on st-bar if background is not present. Frankly, having a different status bar height was not very good thing for keeping code clear, but... At least, now Jaguar status bar is looking like a real Jaguar status bar.

Wondering about possible consequences if one day I'll decide to make Doom Alpha emulation, or possible other console ports.
