### ISSUE TITLE
Use official SDL2 dlls for SDL and MSYS dlls for everything else

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#127]
RD now able to play MP3/OGG/FLAC, but I have some problems with playback dlls. For some reason, bundled with Chocolate / Crispy making no sound at all, so I can't use them (plus I'll probably will need a x64 versions). 

MSYS dlls are working fine, except they are highly dependent from some others MSYS-related, which are definitely not needed for RD, and I don't want to have about +-10 superfluous dlls just to get this stuff working.

If I'll find out everything necessary for keeping game directory as clean as possible, "Native MIDI" should be renamed to "MIDI/MP3/OGG/FLAC" or "Midi and Digital" or something lite that _(thanks Fabian for the idea!)_.

**Comment by fabiangreffrath** [comment]
You may download SDL2_Mixer runtime libraries directly from upstream:
https://www.libsdl.org/projects/SDL_mixer/

**Comment by JNechaevsky** [comment]
Done already. :) I'm now using SDL 2.0.9 and SDL_Mixer 2.0.4, for x86 and x64. Turning on libsamplerate have fixed a "cracking" sound issue, so now it's pretty much same to released version w/o libsamplerate and older SDL.

**Comment by JNechaevsky** [comment]
@fabiangreffrath here, a [screenshot](https://user-images.githubusercontent.com/21193394/59525523-3d5f0780-8edf-11e9-8ac8-1046f9edb5dc.png) of all necessary MSYS dlls to get mp3 playable. That's apocalypse, but since it's a Windows-related, I must figure out what to by myself without distracting you.

By the way, Sigil with .mp3 music sounds pretty neat. :metal:

**Comment by JNechaevsky** [comment]
MP3 / OGG / FLAC working, full dlls package for x86: [rd_dlls_win32.zip](https://github.com/JNechaevsky/russian-doom/files/3291759/rd_dlls_win32.zip)

* libFLAC-8.dll (msys)
* libfluidsynth-2.dll (msys)
* libgcc_s_dw2-1.dll (msys)
* libmpg123-0.dll (msys)
* libogg-0.dll (msys)
* libpng16-16.dll (msys)
* libsamplerate-0.dll (msys)
* libvorbis-0.dll (msys)
* libvorbisfile-3.dll (msys)
* libwinpthread-1.dll (msys)
* SDL2.dll (2.0.9 [official](https://www.libsdl.org/download-2.0.php))
* SDL2_mixer.dll (2.0.4 [official](https://www.libsdl.org/projects/SDL_mixer/))
* SDL2_net.dll (2.0.1 [official](https://www.libsdl.org/projects/SDL_net/))
* zlib1.dll (msys)

Guess, I should **not** use non-msys dlls, since they **may** be compiled with MSVC and thus, will make a game dependent from MSVC redistributable (msvcr110.dll AFAIR). Testing on clean installation of Win 7/10 is still needed. Now for x64...

**Comment by JNechaevsky** [comment]
Same for x64: [rd_dlls_win64.zip](https://github.com/JNechaevsky/russian-doom/files/3291804/rd_dlls_win64.zip)

* libFLAC-8.dll (msys)
* libfluidsynth-2.dll (msys)
* libmpg123-0.dll (msys)
* libogg-0.dll (msys)
* libpng16-16.dll (msys)
* libsamplerate-0.dll (msys)
* libvorbis-0.dll (msys)
* libvorbisfile-3.dll (msys)
* SDL2.dll (2.0.9 [official](https://www.libsdl.org/download-2.0.php))
* SDL2_mixer.dll (2.0.4 [official](https://www.libsdl.org/projects/SDL_mixer/))
* SDL2_net.dll (2.0.1 [official](https://www.libsdl.org/projects/SDL_net/))
* zlib1.dll (msys)

I think there is a small bug in x86, which I can reproduce in Crispy... But I need to make a closer look first - non-midi music and libs something definitely new for me.

**Comment by JNechaevsky** [comment]
Caught! @fabiangreffrath here's a bug I was talking about. I have done following steps:

* `git pull` to have a bleeding edge of Crispy Doom
* `./autogen.sh --host=i686-w64-mingw32`
* `make`
* Copied over newly builded `crispy-midiproc.exe`
* Copied over all dlls from latest dev build

Next, tried to load this wad with E3M1 only music: [D_E3M1.zip](https://github.com/JNechaevsky/russian-doom/files/3291892/D_E3M1.zip)

Now here what is happening: 

* https://youtu.be/1FHqdpbzSFo

Looks likes `D_E3M1` becomes jammed. It's happens a bit randomly and same in RD x86 / x64:

* https://youtu.be/Nhj2U5tyhdw

**Comment by fabiangreffrath** [comment]
Yes, that's a bug with midiproc that I notices earlier: https://github.com/chocolate-doom/chocolate-doom/issues/963#issuecomment-351368408

In short words, the music lump is saved to a temporary file when it is played back. When a new song starts, the file is simply overridden. However, if we attempt to override the file while the backend still has it open, this attempt fails and the same file is played again. This only happens with midiproc, because we currently have no chance to wait until the midiproc process has actually finished playing a file so that we can override it afterwards.

**Comment by JNechaevsky** [comment]
I think I've got whole picture now, support of digital music is still experemental, for now, it's just something like "okay, it's just playing". And at least it's working.

> In short words, the music lump is saved to a temporary file when it is played back.

Wha--?! :scream: Guess it explains a small hiccup on loading of 10+ MB MP3s... But why such an odd routine is necessary? Cant it be read from lump, then placed into RAM for any farther processing?

**Comment by JNechaevsky** [comment]
@fabiangreffrath one more thing regarding temporary file: is it stored on program's directory or system temp folder? I'm asking because it's seems to be dangerous to have an installed game, Sigil and mp3 music on SSD drive - every music change is rewriting of 10-20 MB, which is definitely not good for SSD life.

Or I've got something wrong?

**Comment by fabiangreffrath** [comment]
> Wha--?! scream Guess it explains a small hiccup on loading of 10+ MB MP3s... But why such an odd routine is necessary? Cant it be read from lump, then placed into RAM for any farther processing?

It's documented here:
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/i_sdlmusic.c#L415

First, it is necessary for the `Mix_SetMusicCMD()` command, which calls an external music player application, to work. Second, think of midiproc, it's a separate process which couldn't load data from memory from the main process anyway.

> one more thing regarding temporary file: is it stored on program's directory or system temp folder?

It's written to a temporary directory, at least if your `TEMP` environment variable is properly set.

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/m_misc.c#L232

**Comment by JNechaevsky** [comment]
Dear Fabian, thank you very much for explanation. Yes, on Windows, both `TMP` and `TEMP` are declared as  `%USERPROFILE%\AppData\Local\Temp` (which is mostly system drive `C:`).

I'm on crossroad now. From one side, I want my program will not leave any possible big trails on SSD drive, from another, software like Google Chrome is keeping it's cache also on system drive, and it's far, far bigger than just 20-30 megabytes after visiting few sites. 

For example, Windows 7 hibernation more is writing full RAM dump on system drive, and speaking about modern RAM sizes this is a 2-8 GIGs. Windows 8 and 10 is writing only used memory, AFAIK.

Anyways... May I ask you for recommendation here? I really don't know what to choose.

**Comment by fabiangreffrath** [comment]
> Anyways... May I ask you for recommendation here? I really don't know what to choose.

Sorry, I have no idea. I am glad I don't have to care about this, actually. :wink:

**Comment by JNechaevsky** [comment]
Ooooooooh! :sob:

**Comment by fabiangreffrath** [comment]
Does this patch help a bit?
```
--- a/src/m_misc.c
+++ b/src/m_misc.c
@@ -41,6 +41,7 @@
 #include "deh_str.h"
 
 #include "i_swap.h"
+#include "i_timer.h" // I_Sleep()
 #include "i_system.h"
 #include "i_video.h"
 #include "m_misc.h"
@@ -185,6 +186,12 @@ boolean M_WriteFile(const char *name, const void *source, int length)
        
     handle = fopen(name, "wb");
 
+    for (count = 0; handle == NULL && count < 10; count++)
+    {
+        I_Sleep(100);
+        handle = fopen(name, "wb");
+    }
+
     if (handle == NULL)
        return false;
 
```

**Comment by JNechaevsky** [comment]
Made about 100 change attempts of testing map with menu - epispose 3 - episode 1 - endgame - episode 3 and so on. Yep, can confirm that it's working just fine now, thanks!

**Comment by JNechaevsky** [comment]
@fabiangreffrath are you planning to merge this patch into Crispy? I want to use it, but can't do this because of lack of your `[crispy]` signature.

**Comment by fabiangreffrath** [comment]
I guess this is even suitable for Choco. It has similar problems if you load a music PWAD and render midi with fluidsynth. 

Does it also work if you switch 10 and 100 in the patch? So `count < 100` and `I_Sleep(10)`.

**Comment by JNechaevsky** [comment]
Repeated same procedure, working absolutely fine. More of that, reduced `I_Sleep` delay "feels" much better. :thumbsup:

**Comment by fabiangreffrath** [comment]
Thanks for checking, as always!

**Comment by JNechaevsky** [comment]
My pleasure, thank you too for making digital music feature working proper! 

As about `TMP` dir using, I think I can change `tempdir` from system `TEMP` to `"."`, but no, this is not good idea - in case of running port from local cloud drive folder, temporary files will start to sync, making an unnecessary traffic. Better leave it as is, looks likes I'm worried about it too much.

**Comment by JNechaevsky** [comment]
Digital music issue fixed via https://github.com/JNechaevsky/russian-doom/commit/78cde2cc5782670cc69d33407a24f1604db1b6dd, thanks @fabiangreffrath as always!

As about initial issue - I have found everything I really need, for both x86 and x64 versions.

And as about `TEMP` dir writing - well, if Chocolate and Crispy is using this approach, I think I can follow this suite. Hopefully, one day situation will be changed and we'll have a proper support in the code for digital music playing, but until that, let's just keep in mind than OPL is thy only orthodoxal!
