### ISSUE TITLE
Russian DOOM for DOS 1.0 release plan

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#13]
## Released 01.06.2017!
Well, it's about time. Seventeen years ago I was a young kid, the first one who was able to translate DOS version using Dehacked, Hex editor, WinTex and Microsoft Paint, and now, after almost 1/3 of the whole lifespan I have recreated it with proper quality.

Of course, this DOS version will be something like "Demo scene" rather than port for playing Doom, nowadays, but goddammit, I'm really happy to finally get this Holy Grail of Doom translation.

But enough of beautiful words, I've got stuff to do.

### Step 1: Double-check everything
- ✔️All ingame demos from all supported games must work without desyncs, as well as all credit screen must be proper.
- ✔️Check more deeper, what else can I do for DOS4GW translation.
- ✔️Cleanup rusdoom.wad file.
- ✔️Change character encoding of order.txt and vendor.txt to CP866 (make 80 column limit).
- ✔️Include GPL.TXT file.
- ✔️Check all ENDOOM screens, since their chars were re-typed in ENDOOM using CP866.
- Probably play it on real PC with FreeDOS, loaded from USB stick.
- ✔️No further ideas implementation. Code corrections/cleanups/simplifications/code comments only.
- ✔️Think what I can do with my exclusive [Mini-Medusa](http://savepic.ru/14070062.png) bug. So, that was not related to original Medusa bug, probably it was happening because of some kind of overflow. Fixed in https://github.com/JNechaevsky/russian-doom/commit/b88031dca8fb360378074f93d61686c76183c711.
- Complete all the games:
✔️Nuts.wad (requires 32 mb of RAM, otherwise gives `Z_Malloc` error almost at the end)
✔️Doom Shareware
✔️The Ultimate Doom
✔️Doom 2: Hell on Earth
✔️Final Doom: The Plutonia Experiment
❌Final Doom: TNT - Evilution (I'm too tired of gaming, I can't play any longer)

### Step 2: Release
- ✔️Create new screenshots (4 is enough).
- ✔️Create readme text files in both Russian (DOS CP866) and English (ANSI). (make 80 column limit)
- ✔️Write few basic tips for getting a proper picture in DOSBox in readme files. Some people may not know about it, and will get blurred crap with wrong aspect ration. What should be set in dosbox.conf:
```
fullresolution=fixed
output=openglnb
aspect=true
keyboardlayout=RU
```
- ✔️Create change log text file, only in Russian (DOS CP866). (make 80 column limit)
- ✔️Update project's web pages.
- ✔️Upload binary archive and updated source code archive (from main version 2.2, DOS sources should be added) on the net.

### Step 3: Web
- ✔️Upload updated project's web page.
- ✔️Put online changelog file.
- ✔️Update [iddqd.ru](http://i.iddqd.ru/viewtopic.php?t=1044) forum thread with full description.
- ✔️Update page on [Chocolate Doom Wiki](https://www.chocolate-doom.org/wiki/index.php/Russian_Doom) (binary link only).
- ✔️Update page on [Doomwiki](https://doomwiki.org/wiki/Russian_Doom) (binary link only).
- ✔️Make a post on [VKontakte.ru](https://vk.com/julian_nechaevsky) social network.

### And of course...
Thank all great people for their code base, help, support, advises, comments and bits of code.
Because other's persons work and time should always be respected, as well as subordination.

Without all of them, my project could not ever be existed.

**Comment by JNechaevsky** [comment]
@AXDOOMER, @nukeykt,

Guys, there is a problem on Plutonia's MAP12 because of unknown map things id 225 and 226:
- Load Plutonia IWAD
- Go to map12
- Save your game
- Load you game
- Poof! Unknown tclass in saved game.

This is not happening in Vanilla Plutonia.

**Comment by AXDOOMER** [comment]
I don't know what could cause this. It's coming from my port. The only change that I did that could be related to this is [this](https://github.com/AXDOOMER/doom-vanille/commit/bd372eed3a20ce90bd06351a36ccb2d9ef2675a6), but I don't see any bug. You could still try to revert that line to how it was in PCDoom. 

The error occurs when the level is loading (you can create a savegame under PCDoom and it will load successfully on the original Doom). 

The displayed error is `P_UnarchiveSpecials:Unknown tclass 182 in savegame`.

**Comment by JNechaevsky** [comment]
Yeah, I've also tried your port, that's very strange. I think there are few ways to fix it:

1. Try to replace these unknown things through `doomednum` to some kind of knows things (like bullet puffs or even better to some kind of empty things). Like this, all in p_mobj.c:
```
if (mobjinfo[i].doomednum = 225)
mobjinfo[i].doomednum = -1
```
This is probably will be safest way.

2. Add these unknown thing to info.c. Seems to be completely unsafe for Vanilla compatibility, because this way Vanilla Plutonia can start to give "Unknown tclass" errors.

The most strangest thing is why this vanilla code is not working:
https://github.com/AXDOOMER/doom-vanille/blob/master/p_mobj.c#L761
```
    // don't spawn mapthing if unknown type
    if (i==NUMMOBJTYPES)
	return;
```
I.e., maybe it's working, but unknown thing still tries to be preserved in saved game.

In any way, better to consider this bug as a release blocker. AFAIR, there is also few more maps in Final Doom with such unknown this, I better to check them all by saving/loading.

**Edit:** Dang, it's not a doomednum 255 and etc., it's a thing number. Doomednum's are `0`, but I still can't see these things through IDDT. Removing these things through map editor solves saving problem.
Great...

**Comment by JNechaevsky** [comment]
@AXDOOMER, hell yeah, done! Fix was found in Chocolate Doom, take a look:
https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/doom/p_mobj.c#L771

After this fix saving/loading working fine.

**Comment by AXDOOMER** [comment]
Weird. There would be some reverse engineering work to do to find out how Doom behaves and why vanilla PCDoom v2 didn't exhibit the bug. . 

Anyways, I've patched my code and it works. Thanks for demystifying this bug.

**Comment by JNechaevsky** [comment]
## Released!

Binaries: [russian-doom-dos-1.0.zip](https://sourceforge.net/projects/jnechaevsky/files/Russian%20Doom%20for%20DOS/1.0/russian-doom-dos-1.0.zip/download)
Sources: [russian-doom-2.2-source.zip](https://sourceforge.net/projects/jnechaevsky/files/Russian%20Doom/2.2/Source/russian-doom-2.2-source.zip/download) _(updated archive)_
Full changelog: [changelog_dos_rus.html](http://jnechaevsky.users.sourceforge.net/projects/rusdoom/files/changelog_dos_rus.html#2.2) _(Russian only)_
Subsection in project's site: [rusdoom/dos.html](http://jnechaevsky.users.sourceforge.net/projects/rusdoom/dos.html) _(Russian only)_

**Comment by AXDOOMER** [comment]
Nice job! It's very cool to see colored blood and menu shadows in a DOS release of Doom. You did great!

**Comment by fabiangreffrath** [comment]
Congratulations!

**Comment by JNechaevsky** [comment]
**Hooraaaay!**

@nukeykt, @AXDOOMER, @fabiangreffrath, @bradharding, @jeffdoggett, @fragglet, @NY00123,

Dear colleagues, gentlemen, guys, friends! Thank you very much for all your help, support, advices, big and small bits of of code (even small bits was critical)! It was a flashing month of some definitely unusual experience. As usual, all your Names are placed in "acknowledgments" section in both `DOCS/INFO_EN&RU.TXT` of binary archive, as well as here, in [THANKS.md](https://github.com/JNechaevsky/russian-doom/blob/master/THANKS.md).

A lot of good things were implemented, and sadly, few was not. But I'm absolutely happy with the fact of all planned things were done, as well as Vanilla feeling and gameplay was preserved!

@nukeykt,

Алексей, Вам персональное и огромное спасибо за все Ваши труды. Без них ничего бы этого никогда не случилось, и сейчас, по прошествию такого огромного количества лет (порядка 17и), я уже точно могу сказать, что этот проект перевода - нечто сравнимое с... делом всей жизни. :-)
Моя единственная к Вам просьба - напишите, пожалуйста, ещё раз Полу Радеку насчёт публикации исходных кодов DMX. Если выпуск всё-таки случтится, мне кажется это будет как минимум новой главой истории в Doom-комьюнити.

**Comment by nukeykt** [comment]
Я писал ему месяц назад. Ответа пока нет. так что ждём.

**Comment by AXDOOMER** [comment]
> Ответа пока нет. так что ждём.
 
![1q4i0a](https://cloud.githubusercontent.com/assets/6194072/26693623/d036b212-46d2-11e7-95cc-64c5c3f72cf7.jpg)
DMX is a registered copyright in the US, which means the copyright will stand for the author's life plus 70 years. At least we have ASS, which id Software should have used in the first place.

**Comment by JNechaevsky** [comment]
Holy Jesus! What a news... 😖

**Comment by JNechaevsky** [comment]
@AXDOOMER, ahh, hmm, wait, guess I got it wrong. Is it means, that only after 70+ years DMX will become something like "public domain property"? Or is it means, that until 70+ will not pass, DMX can't be released as GPL/Freeware?

**Comment by AXDOOMER** [comment]
In the US, it would become public domain 70 years after the death of the author. We will all be dead when this time will come. 

If we want to use it, Radek would have to release the library licensed under the GPL by himself. Since I've read that the answer was "no", then I guess the only way to use it is if you're lucky enough to have that leaked DMX source code and are able to build it into PCDoom. You can't do a public release though. 

It may be considered abandonware (a software which is still under copyright, but the owner may not be tracking copyright violations), but it's still not compatible with the GPL. Maybe it would work if PCDoom was licensed under the Doom Source License and if the "illegal" version was only available through a Russian website, it would probably be "secure", though you'd have not to take copyright seriously to do this. It's just like how Nintendo doesn't sue websites distributing SNES or Nintendo 64 ROMs. 

There may be some reason why Radek doesn't want to release it under the GPL. It could be because it would require some work (e.g. cleanup files), he could still be making money out of it, etc. I wonder if he would still sell a licence for it though, still I don't believe anyone would buy one.  

Did I get it correct by translating to "The answer is no" or it was "There is no answer yet"? I don't know exactly what @nukeykt said he was waiting for, which makes me believe I got it wrong.

**Comment by nukeykt** [comment]
I mean there is no answer yet

**Comment by JNechaevsky** [comment]
@AXDOOMER, thanks for explanations!

Phew.. Luckily, we just have a little language misunderstanding here. 😊

Even if GPL release will not happen, DMX from Apogee is a real savior nowadays. Well, it may sounds just a little bit different in few instruments, but there no any other analogues, and probably will never be, since now is a 2017, not a 1997.

I wonder if my translated graphics can be considered as truly legal GPL. Probably "not much", since all the chars are based on original id graphics, which was not released as GPL. But I need it to look as much close to original, as possible. From another hand, this is just a harmless translation project, without original IWADs it is not possible to play at all. But if only I'll get something from Zenimax lawyers, I will have to do something - I have a lot of code from other projects, and the least thing I want to do, is to attract any unnecessary attention to respected authors of those projects.

But again, there a lots of mods/wads exist, which are using a lots of modified original graphics, and everything fine with them (I hope). So all I can do here - is to play fair and don't be an arse. :)

Maybe I should add some info, like "DOOM is a registered trademark of ..... ", just need to find a proper text.
