### ISSUE TITLE
Create a Classic edition of RusDoom

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#130]
Looks likes I'm pretty much tired of enhancements and other stuff. Despite of I'm satisfied of project's technical and visual look, I'm moving in wrong way by adding bunch of libraries, wads and executables. Introduced `-vanilla` mode is doing it's good and right thing, but still, this is not a panacea. I need something different, which is meaning - small, simple and fast. Just like Yaguar project, or DOS version, where I'm keeping everything in one simple wad.

I'm not meaning a Russian version of clean Chocolate Doom, no. Some things should be implemented because of their usability.

Some raw thoughts...

**Restrictions:**

- One translation pwad. Just one.
- No support for fallback to English language.
- No declared support for modding. Just pure Doom, Doom 2, TNT and Plutonia.
- No translated GFX patches, everything writable should be written by the ABC for size optimization.
- No gameplay enhancements.
- No mid-res.
- No libsamplerate.
- No 64-bit version.
- No widescreen version.
- No declared support for vanilla savegames. Never was my point.

**Reasonable enhancements:**

- Autorun toggling, walk/run modifier by `SHIFT` button.
- Improved palette. Because having a good visual is still my de-facato. Probably, in-game "Screen size" can be replaced with "Gamma-correction" slider.
- Disabled savegame and demo limits. No need to keep possible crash invoking.
- Doom+ limits. No need to bomb out in some TNT maps.
- Small bugfixes, like Icon of Sin's division by zero.
- Automap redrawing while playing.
- Key blinking for locked doors.
- Texts should cast shadows. Once it seen, it is impossible to see characters w/o shadows.
- `WADS`+`E` as default controls.

**Comment by fabiangreffrath** [comment]
I know this feeling of losing focus and direction pretty well. I got it rather early in Crispy's development, but people demanded more and more features and fixes and I figured that maintaining another stripped down version of the same port only lead to more development effort. Thus, I decided to keep the total number of features at a reasonable scale, choose sensible default and leave everything as Vanilla as possible in the default configuration, This somehow saved me over this phase, but sometimes the feeling of "what I am doing here at all?" is coming back. I need a little break for a few days then... :wink:

**Comment by JNechaevsky** [comment]
Oh yes, you got me right! It's complicated, request like "do that" or "implement that feature, or at least a hidden variable" sometimes sounds reasonable at least in technical POV, but leading to another maze in fact. Another huge problem which is always haunting: "what will happen if I'll do something", and it's making some features a bit handicapped or bounded.

Another aspect is a translation. Right from the very first releases I have declared that I'm not interested in any kind of discussions about it, just because my project = my vision, although I'm always open to hear some reasonable corrections, but nothing like "I _think_ it must be translated that way". 

When [Russian GZDoom](https://forum.zdoom.org/viewtopic.php?f=19&t=58872) comes out, which is based on translation resources of RD, it became more or less community translation project, and that leads to some funny (but serious!) request like... "Guys, have a closer look, keycard is a punch card, so translation must be changed!". Jesus Christ. :scream: 

I'm not related to this project and ZDoom community at all, but as a native Russian speaker I'm collaborating with Nemrtvi sometimes to correct some spelling and don't let some godawful things like punch cards happen.

I just want to experiment a bit. While reading Jaguar (font writing) and Heretic (level names on intermission) sources, I have discovered that many things may be visually same, but implemented differently. Not sure what will happen next, I'm afraid sooner or later I will want brightmaps, but until then, I'll try to make this version as small as possible.

**Comment by JNechaevsky** [comment]
Alright, I'm back on planet Earth again. I think I'll release this Classic version on 3rd anniversary of RD (2019-09-16), because this is how actually RD was started - Russian version of Chocolate Doom and nothing more. But here I still would like to implement just a few logical and safe enhancements.

**Comment by JNechaevsky** [comment]
Maybe one day. I will keep sources, but now it's obvious - I can do better by further work on `-vanilla` mode.
