### ISSUE TITLE
Allow to choose color of HUD messages

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#132]
Kinda useless, but in fact, it's a good addition for colored HUD.

Something like this @@ HUlib_drawTextLine, not sure how to make a proper multiple choice:
```
        if (c != ' ' && c >= l->sc && c <= '_')
        {
            w = SHORT(l->f[c - l->sc]->width);

            if (x+w > ORIGWIDTH)
            break;

+++         // [JN] Colorize HUD messages
+++         if (colored_messages == 0)      // red
+++             dp_translation = NULL;
+++         else if (colored_messages == 1) // green
+++             dp_translation = cr[CR_GREEN];
+++         else if (colored_messages == 2) // blue
+++             dp_translation = cr[CR_BLUE];
+++
            V_DrawShadowedPatchDoom(x, l->y, l->f[c - l->sc]);
+++
+++         if (colored_messages != 0) // clear translation
+++         dp_translation = NULL;

            x += w;
        }
```

**Comment by JNechaevsky** [comment]
@fabiangreffrath, may I abstractly suggest something about this for Crispy? Got a couple of raw thoughts about HUD messages, maybe making a separate section in Crispness menu will be more suitable. Items/ideas are:

* Colorize HUD messages [multi-choice of color translations]
* Centered HUD messages [on / off] - _Centered a-la Heretic._
* Scale HUD messages [on / off] - _Need to thing twice, having an unscaled messages, while the rest of texts are scaled, certainty a bad design ethics._
* HUD message timeout [1 to 9 / infinite?].

**Comment by fabiangreffrath** [comment]
Hm, not sure. Why would I want to colorize normal HUD text? That would de-emphasize it completely. What's the advantage of centering it? I understand the reasoning for a time-out, but I'd probably rather go the ZDoom way of showing up to 3 lines of HUD messages which collapse after their repsective time-outs. Still not fully convinced about this, though...

**Comment by JNechaevsky** [comment]
"Just because", actually. :) Green text is looking pretty neat, although I haven't checked how it looks altogether with other text like save game strings and etc. These all features, except timeout, is a ZDoomism. 

As about three lines of messages, I would like to don't recommend to do this: three lines of scaled text will eat a lot of screen area, especially in 4:3 screen mode.

**Comment by fabiangreffrath** [comment]
> "Just because", actually. 

Ouch, that's never a good reason! Apart from multi-line HUD messages, which you already argued against, I see no good reason to change Doom's current message system in fundamental ways - to be honest.

**Comment by JNechaevsky** [comment]
Oh well. That's all I can offer for now. :confused:
