### ISSUE TITLE
[Research] Make a sprite of crushed Spider Mastermind

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#14]
Thinking about color blood&corpses, I think I want a separate sprite of squished Mastermind.
There is no critical necessity for this, since it can be seen only on HOE map06 but it can be a nice addition to my optional stuff.

Low priority. 

As usual, self-restriction: don't use other's people graphics, all must be done by myself (but using vanilla sprites is allowed). Need to experiment. Of course it must be vanilla-like, and looking good, not...
![hey](http://savepic.ru/14265779.png)

**Comment by JNechaevsky** [comment]
Final version.
![ouch](http://savepic.ru/14258435.png)

**Comment by JNechaevsky** [comment]
Guess I'm done. Now for the code...
![crush](http://savepic.ru/14238979.png)

**Comment by AXDOOMER** [comment]
Can you also add it into the DOS version?

**Comment by JNechaevsky** [comment]
I would be glad, but can't handle it technically - it will require to teach the engine how to load sprites through -file. My few shy attempts to do this was not very successful, that's why colored blood using color translation, not sprites like in main project.

**Comment by AXDOOMER** [comment]
You're right. It requires `-merge`. Maybe I will add it someday. I would also add `-deh`.
