### ISSUE TITLE
Make `snd_samplerate` toggleable in options menu

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#142]
Menu item names:
* English: `Sample rate`
* Russian: `Частота дискретизации`

Available values:
* 11025
* 22050
* 44100 (default)
* ~48000~ _(not needed)_

**Comment by JNechaevsky** [comment]
:sweat_smile: Goddamit! This is not I was trying to do! https://youtu.be/ciJ78KDLOzI

**Comment by JNechaevsky** [comment]
Allright, enough of kidding. It is obivious, that sample rate is initialized somewhere in low level, and probably whole sound system should be restated. Maybe later.

Working code for `snd_samplerate` toggling in game menu:
```
void M_RD_Change_SampleRate(int choice)
{
    if (snd_samplerate == 11025)
        snd_samplerate  = 22050;
    else
    if (snd_samplerate == 22050)
        snd_samplerate  = 44100;
    else
    if (snd_samplerate == 44100)
        snd_samplerate  = 11025;

    // do something about sound system    
}
```

But those scream and pain sounds... I can swear that I've heard them in other games, probably they also comes from Sound Ideas library.

**Comment by fabiangreffrath** [comment]
What exactly is the use case for switching sound samplerate in-game?

**Comment by JNechaevsky** [comment]
There is more a feeling reason, rather than technical.

22050 sounds more "original", at least as far as I remember sound back in 1994. I can't say it for sure, probably back in that days I was playing with pretty cheap sound speakers. Maybe it's just an imagination already.

44100 is default and `libsamplerate` making a PERFECT interpolation for it. Should be strictly default.

11025, well, maybe not really necessary, unless someone would like to hear how actually sounds are playing from cellphone speaker. It is mostly for assortment, because having only 22050/44100 will look quite unusual.

Also, I need to fill my sub-menus, because sub-menu with just a 2-3 items is looking pretty bad.

**Comment by JNechaevsky** [comment]
It can be shortened to something like "Sound quality: high / low" (high: 44100, low: 22050), but I'm not sure it's a good idea. Sample quality and digital values are more traditional for this case.

**Comment by JNechaevsky** [comment]
And of course, this is also an argument!

![](https://i.kym-cdn.com/photos/images/original/000/141/601/sSyes.png)
_(hey, just kidding!)_

**Comment by fabiangreffrath** [comment]
I was suspecting that! :wink:

**Comment by JNechaevsky** [comment]
Okay, it was fun to play around with high-pitched sounds, but in fact - yeah, this is totally useless as a feature. Closing. :expressionless:
