### ISSUE TITLE
Hexen: incorrect Timon Axe apperance

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#143]
Probably worth to check out, this must be a vanilla bug. Steps to reproduce:

- Drain all blue mana from Axe, should be `0` or `below`.  It will lose blue glowing.
  - Yes, Axe consumes `2` blue mana, but hit is possible even with `1` mana, dropping down blue mana to negative value `-1`, it's a vanilla behavior, altrough player can not see it with standard status bar code.
- Switch it to another weapon, while blue mana is still `0` or `negative`.
- Switch to Axe again, it will be glowing again.

**Comment by fabiangreffrath** [comment]
Should probably check for `player->mana[MANA_1] > 0` here:

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/hexen/p_pspr.c#L608

**Comment by JNechaevsky** [comment]
Oh yes, that's it, thanks! 

This also should be corrected then:
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/hexen/p_pspr.c#L368

In `P_FireWeapon` condition seems to be correct. Well, not exactly, but explains how hits with `1` mana possible at all. Using `> 1`  will fix negative mana case, but this should never happen - even such a small thing is a traditional game mechanics:
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/hexen/p_pspr.c#L458

**Comment by JNechaevsky** [comment]
For the record, here's how negative mana apperance was fixed in custom fullscreen HUD: https://github.com/JNechaevsky/russian-doom/commit/06b870b3d7ff67139aa2dac553d5372a2284958c

A `minus` symbols exist in both code and graphics, obviously for negative frags. Hovewer, player can't see negative mana because of there is no mana indication in vanilla fullscreen HUD (a), and frags can't appear as lower than `-9` (b) (https://github.com/chocolate-doom/chocolate-doom/blob/master/src/hexen/sb_bar.c#L435). It's pretty much same with big red digits: https://github.com/chocolate-doom/chocolate-doom/blob/master/src/hexen/sb_bar.c#L487.
