### ISSUE TITLE
Fix stopped fuzz effect

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#144]
Not sure I'm no right track, but something like this seems to be working... Or maybe it's just an illusion, it may fix animation in some places, not entirely.
```
    // Clamp table lookup index.
    if (++fuzzpos == FUZZTABLE) 
    {
        // fuzzpos = 0;
        fuzzpos = P_Random()&49;
    }
```

**Comment by JNechaevsky** [comment]
@fabiangreffrath, maybe this will interesting for you. Here's a savegame with "dead zone" of freezed fuzz: [freezfuzz.zip](https://github.com/JNechaevsky/russian-doom/files/3736180/freezfuzz.zip) (set screen mode to Crispy HUD or full screen). Could you please take a try this approach:
```
	// Clamp table lookup index.
	if (++fuzzpos == FUZZTABLE) 
---	    fuzzpos = 0;
+++	    fuzzpos = Crispy_Random()&49;
```
Using a `&1` also works, but making animation notably rough. 

This also fixes notable change in the fuzz animation, while player is standing near the pile of spectre corpses and changing his weapons, but making animation playing while paused state.

**Comment by JNechaevsky** [comment]
Another draft. This seems to be properly pausing fuzz effect when it should be paused, but it's a bunch of `if` conditions in the constantly called function.

```
	// Clamp table lookup index.
	if (++fuzzpos == FUZZTABLE) 
	    fuzzpos = paused || menuactive || inhelpscreens ? 0 : Crispy_Random()&49;
```

**Comment by fabiangreffrath** [comment]
Sorry, I am not sure I understand what you are trying to achieve here.

**Comment by JNechaevsky** [comment]
Wha-? :fearful: Oh, pardon me. There is a bug in original fuzz code - fuzz animation "freezes" in some condition on the screen. It is described here: https://doomwiki.org/wiki/Partial_invisibility_effect (see "Animation remains still" paragraph). I'm trying to fix, by unclamping fuzz start position from `0` to some random value.

To see freezed fuzz in Crispy, please do this:
* Download my [savegame](https://github.com/JNechaevsky/russian-doom/files/3736180/freezfuzz.zip) and load it.
* Set screen size to full screen / Crispy HUD (warning: do not move camera left-right)
* You will see that fuzz effect is freezed (while player is holding chaingun and having invisibility effect)

This must be because stucked `fuzzpos` on zero + some specifics of how this funtion is actually working.

My code draft unfreezes stucked fuzz, but it's not optimized yet - I don't like the idea of having three different `if` condition being checked every rendered frame.

**Comment by fabiangreffrath** [comment]
I can see a repeating pattern in the fuzzed weapon sprite, but nothing static. To prevent the latter, we should probably make sure that `fuzzpos_tic` and `fuzzpos` are not already identical in `R_SetFuzzPosTic()`.

**Comment by JNechaevsky** [comment]
No-no, freezing - is not a pattern question primary. You mean, at your side in HUD-less screen size fuzz is still playing normally with provided savegame? Should I record a video to show how freezing is actually looking?

**Comment by fabiangreffrath** [comment]
No, thanks. I have created another savegame where the animation becomes static for me by turning around a few degrees.

In Crispy, the situation could be mitigated by something like this:
```
--- a/src/doom/r_draw.c
+++ b/src/doom/r_draw.c
@@ -344,6 +344,12 @@ int        fuzzpos = 0;
 static int fuzzpos_tic;
 void R_SetFuzzPosTic (void)
 {
+       // [crispy] prevent the animation from going static
+       if (fuzzpos_tic == fuzzpos)
+       {
+               fuzzpos = Crispy_Random()%FUZZTABLE;
+       }
+
        fuzzpos_tic = fuzzpos;
 }
 void R_SetFuzzPosDraw (void)

```

We could even unconditionally set `fuzzpos_tic =  Crispy_Random()%FUZZTABLE` or similar.

[doomsav0.zip](https://github.com/JNechaevsky/russian-doom/files/3739234/doomsav0.zip)

**Comment by JNechaevsky** [comment]
:heart_eyes:  I'll check it out in the evening. Ah yes, may we consider this a suggestion and own issue on Crispy tracker? It's a visual vanilla bug after all.

**Comment by fabiangreffrath** [comment]
Not sure. It's a very rare and obscure bug. And a lovely one... :wink:

**Comment by JNechaevsky** [comment]
Wha-? :anguished: Oh well. Whatever you say.

**Comment by JNechaevsky** [comment]
Yeah, your approach working, but there two issues (both visual):

* Fuzz effect becomes notably different, it feels like "shaking" up/down in some scenes.
* Again, on some scenes, it looks likes there are just a two frames of fuzz animation.

For now, I would like to stuck with my approach, because it makes fuzz just a little bit, barely different (err, feels like.. just a little bit "juicy") and making whole fuzz animation independently same if player is standing near corpses of Spectres and changing his weapons.

Jeez, it's really hard to explain this visual feeling.
