### ISSUE TITLE
Remove pain/ouch/rampage face when entering new level

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#146]
This is a small vanilla aesthetic bug - when player get's hurt and exiting the level, his pain/ouch/rampage face is keeping on next level.

Can be fixed by something like this:

**st_stuff.c**
```
// a random number per tick
// [JN] Made unstatic (for G_PlayerFinishLevel)
int st_randomnumber;  

// [JN] Made unstatic, externalized (for G_PlayerFinishLevel)
int faceindex;
```

**g_game.c @@ G_PlayerFinishLevel**
```
    p->fixedcolormap = 0;   // cancel ir gogles 
    p->damagecount = 0;     // no palette changes 
    p->bonuscount = 0; 
    st_palette = 0;         // [JN] Also no inner palette changes
+++ faceindex = st_randomnumber % 3; // [JN] Reset face index on next level
}
```
Seems to be safe, face is not changing while this function because of active wipe effect.

**Comment by JNechaevsky** [comment]
@fabiangreffrath :wave:, worth a suggestion?

**Comment by fabiangreffrath** [comment]
Sure!

**Comment by JNechaevsky** [comment]
Done, thank you. Looks likes it is absolutely safe. As an example, it is working fine even with Jaguar loading emulation, which is in fact is a "wipe without wiping effect". Have a look, face is not changing on status bar after hitting the exit switch: https://youtu.be/qZwohELWDt4
