### ISSUE TITLE
Add in-game menu item for language switching

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#148]
There are two possible approaches:

1. Make a soft switch. It will ask for quit, and after confirmation will swap `english_language` to opposite value, then save all game settings, then quit game. Not perfectly helpful, but can be handy for in-game switching, rather than editing config file or switching language in Setup executable.

2. Make a real hot-swapping switch. After some experiments it is clear: it's not hard to reinitialize menu system, finale texts and fonts, but there is another problem: all Russian resources should have DIFFERENT names. Titlepics, help screens, menu items, status bar and so on. This also will probably make Russian version totally unchangeable, but I'm okay with this, this is right thing to do.

First one is easiest and painless, second one is painful and will bring some mess in the code, but also much more useful and technically advanced.

**Comment by fabiangreffrath** [comment]
Alternative approach: Put everything language-related into pointer arrays of size `2` with index `0` pointing to the English variant and index `1` pointing to the Russian. Then it would be like e.g. `player->message = game_message[cfg_lang_rus]`, where `cfg_lang_rus` is your config variable which is `1` if Russian language is selected and `0` otherwise.

**Comment by JNechaevsky** [comment]
Thanks! Messages are smallest problem now, I can simply invoke this function right after language varable was changed: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/rd_lang.c#L170 and it will set proper messages for selected language.

Most big problem is font. I should keep `STCFN` for English version, but Russian should use something totally different, and it's same for all translated content, duh.

**Comment by JNechaevsky** [comment]
Ah yes, I'm already have all necessary fonts for Russian version, big and small, so this is not a problem.
Looks likes the only thing that stops me now is - I don't want to have a bunch of `if (english_language)` conditions in `player->message` drawing functions and the rest of everything necessary. 

Thinking more, this is not big problem at all, just need to do everything carefully.

And thinking even more, I have a one huge self-question now: what is more proper, having a sub-menu with just two big strings "English / Русский", or having a one extra string in main Options menu, which will cycle languages between "English / Русский". Second one seems to be more reasonable, and good thing I have a space for this element!

**Comment by JNechaevsky** [comment]
Should be something like this: https://www.youtube.com/watch?v=bkuUakKDhKU
Status bar and WI_ graphics are still not hot-swappable. Instead of "pitto!" placeholder, there must be a menu item:

* Language/Язык: English (if English language is active)
* Язык/Language: Русский (if Russian language is active)

Also, despite of restarting a finale screen is working fine, it's a demo sync killer switch. Good thing I don't need to care about it much, my aim is to keep only vanilla demos in sync.

**Comment by JNechaevsky** [comment]
Almost done. To summarize:

Pros:
* Switching is working fine, everything is changing in "live" mode.
* It is surprisingly interesting to see the difference on fly.
* Amount of pwads with translation resources greatly reduced.
* English language is perfectly compatible with graphical and text mods.

Cons:
* Despite of Russian language is declared as primary, now it's turned into second-class hack.
* Russian version becomes totally unfriendly with mods. Well, this is not so bad, because Russian, in fact, is all about vanilla.
* I'm forced to remove some extra content like translated textures (no way to switch them "on fly") and wide screens (no way to have them for both languages simultaneously).

Looks likes the project itself turning from "artistic translation port" to the "source port" in it's traditional meaning. But since people are seeking for mods compatibility, well, maybe it is not so wrong way to go.
