### ISSUE TITLE
Demos desync in Russian Heretic

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#152]
I want to start saying that I know that demos from the internal demo loop normally desync in Heretic, because they were recorded with v1.0 of the DOS executable and never updated to match the executable when it was modified by Raven. However, DEMO2 has always played consistently and never desynced.

Russian Heretic now plays it out of sync, and the player dies much earlier than expected, being killed by Gargoyles before descending into the river. This means that vanilla Heretic demos will desync as well, when they didn't before.

**Comment by JNechaevsky** [comment]
Hello @hfc2x and thanks for your time!

I see... RusHeretic is next on release plans, probably with language hot-swapping. But there is only one little big problem: I'm currently focused only on real life, so even can't tell when Heretic will be released. I'm afraid it's something about "in the next year". :-)
