### ISSUE TITLE
Allow to toggle full screen using Enter on num. keyboard

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#153]
It's a `SDL_SCANCODE_KP_ENTER`. Probably something like this, an additional boolean.

```
static boolean ToggleFullScreenKeyShortcutAlt(SDL_Keysym *sym)
{
    Uint16 flags = (KMOD_LALT | KMOD_RALT);
#if defined(__MACOSX__)
    flags |= (KMOD_LGUI | KMOD_RGUI);
#endif
    return sym->scancode == SDL_SCANCODE_KP_ENTER && (sym->mod & flags) != 0;
}
```

**Comment by JNechaevsky** [comment]
@fabiangreffrath maybe this will interesting for Chocolate/Crispy too? Not critically necessary but still handy. 

The reason why I have added toggling as a second boolean: I was not lucky to put both `SDL_SCANCODE_RETURN` and `SDL_SCANCODE_KP_ENTER` in `return` condition, i.e. this approach is not working at all:

```
return sym->scancode == (SDL_SCANCODE_RETURN || SDL_SCANCODE_KP_ENTER) && (sym->mod & flags) != 0;
```

**Comment by bradharding** [comment]
> ```
> return sym->scancode == (SDL_SCANCODE_RETURN || SDL_SCANCODE_KP_ENTER) && (sym->mod & flags) != 0;
> ```

Hi @JNechaevsky. You'll be wanting something more like this:

```
return (sym->scancode == SDL_SCANCODE_RETURN || sym->scancode == SDL_SCANCODE_KP_ENTER) && (sym->mod & flags) != 0;
```

**Comment by fabiangreffrath** [comment]
@bradharding 's solution is right, could you please post a PR for Choco with this?

If you want to check if a variable has the value 3 or 4, you cannot check `if (value == 3 || 4)`, you'll have to check `if (value == 3 || value == 4)`. :wink:

**Comment by JNechaevsky** [comment]
Thanks for explanations, colleagues! Another lesson learned. :) Sure, PR will arrive in the evening.
