### ISSUE TITLE
Widescreen Vertical Orientation Too High?

### ISSUE THREAD

**Issue by DwarsYT** [Russian-Doom/russian-doom#154]
The wording of that title might be a bit off, but I think the screenshots below might tell the tale better. Compare the 4:3 .exe's vertical orientation with the widescreen one's. It appears to look a little TOO high. This appears to be the case in Doom too. In Heretic, the view can be adjusted without mouselook due to the look up/look down commands, but the auto-aim feels a bit off when doing that too.

![screenshot-heretic-01](https://user-images.githubusercontent.com/54383651/71844082-63bedd00-3093-11ea-84ec-38f9ecc1f677.png)
![screenshot-heretic-00](https://user-images.githubusercontent.com/54383651/71844084-63bedd00-3093-11ea-8215-936a58f226a7.png)

**Comment by JNechaevsky** [comment]
Hello @DwarsYT and thanks for your time!

Yeah, that's a real problem. This height difference is not exactly a height of player's view problem - this is probably because of "view matrix" is still same to 4:3 (i.e. player does not have a wider view). Sadly, I still have no idea how to fix it. :/

**Comment by drfrag666** [comment]
I still suspect this is a bad adjustment either here:
`
#ifdef WIDESCREEN
        dy = ((i-(viewheight/2 + ((j-LOOKDIRMIN) << (hires && !detailshift)) * (screenblocks < 9 ? screenblocks : 9) / 10))<<FRACBITS)+FRACUNIT/2;
#else
        dy = ((i-(viewheight/2 + ((j-LOOKDIRMIN) << (hires && !detailshift)) * (screenblocks < 11 ? screenblocks : 11) / 10))<<FRACBITS)+FRACUNIT/2;
#endif
`
 Or here:
`
#ifdef WIDESCREEN
    tempCentery = viewheight/2 + (pitch << (hires && !detailshift)) * (screenblocks < 9 ? screenblocks : 9) / 10;
#else
    tempCentery = viewheight/2 + (pitch << (hires && !detailshift)) * (screenblocks < 11 ? screenblocks : 11) / 10;
#endif
`
Edit: interesting to see that insert code is broken.

**Comment by JNechaevsky** [comment]
Making some fun `ORIGWIDTH_DELTA` seems to be fixed incorrect vertical view direction (that's was the reason...). But i need to check it deeper.
```
#ifdef WIDESCREEN
    tempCentery = viewheight/2 - ORIGWIDTH_DELTA + (pitch << (hires && !detailshift)) * (screenblocks < 9 ? screenblocks : 9) / 10;
```

![screenshot-doom-00](https://user-images.githubusercontent.com/21193394/75525880-b6789d80-5a21-11ea-9aa3-0d74c25af5c8.png)
![screenshot-doom-01](https://user-images.githubusercontent.com/21193394/75525884-b7113400-5a21-11ea-84cc-fb8785678891.png)

**Comment by JNechaevsky** [comment]
Nope, I was wrong. By lovering camera, real "center of view" is also loosed. 

![screenshot-doom-05](https://user-images.githubusercontent.com/21193394/75536426-88498c80-5a26-11ea-92e5-4052d9a5913b.png)

![screenshot-doom-01](https://user-images.githubusercontent.com/21193394/75536512-8ed80400-5a26-11ea-92c9-ed938455a7b5.png)

Guess, it's pretty obvious now: there is nothing wrong in wide calculations, except it's a 4:3 matrix scaled to wide mode and as a result, some space in the top and in the bottom of screen are lost.

**Comment by drfrag666** [comment]
That's obvious but RUDE is not affected by this bug, the view is centered here (but there's no look up/down).

**Comment by JNechaevsky** [comment]
@drfrag666 according to RUDE 3.1.0 pre-release 2, it's pretty much 
![1](https://user-images.githubusercontent.com/21193394/75581739-28c99c00-5a7b-11ea-8e13-46f23d216b95.png)
![2](https://user-images.githubusercontent.com/21193394/75581742-29fac900-5a7b-11ea-917f-573beae98a5a.png)

same to RD, except black borders:

**Comment by drfrag666** [comment]
For me it's not the same, have you checked two windows of the same size side by side? For instance on E1M1 the difference is noticeable looking at the floor tiles.
 Edit: it's not the same width, i'll recheck.

**Comment by drfrag666** [comment]
Now i only see the problem in Heretic, both engines look good to me in Doom. May be it's just an optical effect.

**Comment by JNechaevsky** [comment]
@drfrag666 finally I have found `widescreen 2` option and I think it's awesome. :) Perhaps I'll switch to your approach completely. Only one moment: how do you think, can `widescreen` be hot-switched?

**Comment by drfrag666** [comment]
Thanks! I tried to explain how you could do it here: #168 
 Hope you've tried 3.1.0pre3, pre2 crashed when default screenblocks were less than 10. The port clearly is not popular. Have you tried the UM skill? :)
 The hot-switch would add more complexity and Crispy still has problems with that, Crispy also has screen size autodetection and i didn't fill the entire screen but chose something intermediate between 16:9 and 16:10.

**Comment by JNechaevsky** [comment]
:heart_eyes:
![image](https://user-images.githubusercontent.com/21193394/75674573-6bb38b80-5c96-11ea-8d60-36a915d806a6.png)

I have compared my code with RUDE and now I see where I was wrong! I have changed original `SCREENWIDTH` macro from 320 to 423, and that was the case: in some places it **should** remain as 320 even in widescreen mode. Alright, I think I can handle the rest, it will be pretty massive clean-up job.

Thank you very much!

Yep, I've tried pre3 right in the morning. Tried UM skill just briefly, but I like the idea of spawning 2x monster. BTW, maybe I should create a UM's nightmare-styled gfx for you? 

As about popularity.. Well, speaking frankly and from my side, I'm not really sure that RD is very popular (and neither I want to make it popular). Yeah, there are people who like it, there are russian-speaking who like it, there are russian-speaking who like it and prefer to play with English only language, and there are non-russian speaking people who like it. :) This is not game of popularity, I think it's all about self-realization, generating some cool ideas and of course, collaborating with other authors, without whose help I would not get that far.

**Comment by drfrag666** [comment]
You're welcome. I don't think it should be a massive job, just use a global variable like fabian did to minimize the changes downstream and make maintenance (merging from Crispy) easier. Copying to a local variable in r_draw is just for performance. And then "undo" the changes where needed using the other macro. Basically what i said in #168 
 This commit could help as reference https://github.com/drfrag666/chocolate-doom/commit/c7f81a21288e0c5f976405d1785ced699a42b7ac
 About download count i don't care but only 10 downloads per release... i know it's a pre-release sure. I will make a video when it's done.
 I plan to port the UM skill to ZDoom but it's actually easier than NM and it's at the bottom in RUDE just for compatibility. So thanks but i don't think changing the title it's worth the effort.

**Comment by JNechaevsky** [comment]
Here you go!
![M_EXTR copy](https://user-images.githubusercontent.com/21193394/75812684-ad7c2900-5d9f-11ea-92b6-9d17d4ba5cc3.png)

Believe my artistic POV, having some nice looking stuff is always worth and necessary. Common player will never have an interest to look into the source code, matters no how perfect it's written. But common player will probably always note that something not looking good in released project.

That's the approach I'm having in RD project - I know I can't write some complicated code without help, but having some "good visuals" is always first priority for me. This is why an improved palette (#5), tall skies were born, I was totally unhappy with vertically scaled standard textures, and this is why wider versions of title and others screens were created. It was an awesome challenge for me.

Anyways, better consider to make a source port for yourself primary, it's your project, your skills and ideas, your soul putted in. Your personal time of course. Your joy of creation, and it's not a bare word.

Maybe I'm speaking like a self-centered egoist, but... 

P.S. Today I have received a Sigil box, so please do not expect any code work. :) Still need a couple of hours to make a proper widescreen switch, it will be probably weekend amusement.

**Comment by drfrag666** [comment]
Thanks very much! I'll change it soon. For me it didn't look bad but you know better. The code is far from perfect of course.

**Comment by JNechaevsky** [comment]
My pleasure! No-no, I wasn't meaning that RUDE looking bad, no. 
I was meaning whole possible situation, when some visual stuff may have a higher importance, than technical.

**Comment by drfrag666** [comment]
I mean the current title, i know it's below nightmare but it's much easier. It's supposed to be challenging but playable. But it will look better now i guess. Heh, RUDE is a bit rough i know and that's part of it.

**Comment by JNechaevsky** [comment]
In the end, I've got this (wide titlepic loaded, but it's still cutted):
![image](https://user-images.githubusercontent.com/21193394/76535316-b8b01280-648b-11ea-8a0c-7bee82e8a4e7.png)

After starting any level, error happens:
```
0x004496d1 in R_DrawSpan () at r_draw.c:1253
1253            *dest = ds_colormap[ds_source[spot]];
```

Guess, I'll just stuck with two executables approach, I have neither idea what to do next, not any patience to proceed. :/

**Comment by drfrag666** [comment]
But what have you done? Using a macro or a global variable can't make that much of a difference, of course you need to set another widescreen variable.
 The new UM title graphic looks great, thanks again.

**Comment by fabiangreffrath** [comment]
The wide titlepic must be drawn without horizontal offset. I hope that's obvious.

**Comment by JNechaevsky** [comment]
@drfrag666 mostly applied your approach from https://github.com/drfrag666/RUDE/commit/62c9577f096c85a262b0ce2e82c40d0f02ff31c2 

@fabiangreffrath 😨 oh please, after the hourse I have spent on wide graphics, such things are not just obivious, they are "clear by default".

**Comment by drfrag666** [comment]
But that was overkill and more complicated, fabian used a global variable. This:
> To get one executable you need to change the SCREENWIDTH macro to a global variable with the same name initialized accordingly in i_video.c and then declare it as extern in i_video.h.

**Comment by JNechaevsky** [comment]
Alright, on 10-th attempt I give up. Still error with `R_DrawSpan`, still some mess on titlepic screen.
Hovewer, the thing I would like to implement is pretty same to the Unity edition, where window size is always wide, while in-game screen can be either 4:3 or 16:10. All I really need here is black borders, which can be done via `V_DrawFilledBox`. 

Here's an example:
![bandicam 2020-04-01 18-05-32-326](https://user-images.githubusercontent.com/21193394/78153320-9afb1b00-7443-11ea-848a-557920999a56.gif)

Sadly, Unity's approach is a huge driven nail into the coffin of real non-wide monitors, there will be no way to get full screen picture on fullscreen mode. But at least there won't be any necessity of making two executables and saves me from any farther headache.

**Comment by JNechaevsky** [comment]
Good news! I have successfully implemented `widescreen` variable now. The reason of my previous fails is simple - I have totally forgot about `ORIGWIDTH` marco, which is also necessary... Sadly, live switching is not working, no idea what to do. But even if restart will be needed, I think this is totally okay.

Now I need to make a huge code cleanup.

**Comment by drfrag666** [comment]
Good to know you got it working! Yeah fabian has changed the name of the macros several times now. I never supported live switching and that introduced some problems in Crispy (fixed now), to me that's not important. You need to make your launcher select widescreen mode and store the configuration too.

**Comment by JNechaevsky** [comment]
Yeah, macroses is a pain, but not really a pain in such. :) Looks likes I have solved last problems and got a fine working executable (self-reminder: `ST_WIDTH` must be  is `ST_WIDEWIDTH = WIDEORIGWIDTH` in `widescreen`!!!). Just need to make a centered status bar in wide mode.

I think I need to create a separate branch before merging, @drfrag666 I was using your approach with small difference: `screenwidth` and stuff are declared and set once in `SetVideoMode`, i.e.:

```
    // Set the highdpi flag - this makes a big difference on Macs with
    // retina displays, especially when using small window sizes.
    window_flags |= SDL_WINDOW_ALLOW_HIGHDPI;


+++ // [JN] Set widescreen variables
+++ if (widescreen)
+++ {
+++     screenwidth = WIDESCREENWIDTH;
+++     origwidth = WIDEORIGWIDTH;
+++     wide_delta = WIDE_DELTA; // macro, 53 in fact
+++ }
+++ else
+++ {
+++     screenwidth = SCREENWIDTH;
+++     origwidth = ORIGWIDTH;
+++     wide_delta = 0;
+++ }
```

By using this place there is need to declare `screenwidth` in the all rendering functions.

**Comment by drfrag666** [comment]
That's why i told you not to do that but declare SCREENWIDTH (or whatever macro was everywhere initially) as a global variable and initialize it in I_InitGraphics. Same as i did here https://github.com/drfrag666/RUDE/commit/061293f4fb3f17c0437822a1d6b6549492d57880 with WIDEWIDTH_DELTA. It's advisable to declare screenwith and copy SCREENWIDTH there in some functions for loops in r_draw for performance. But hey if it works now and it's done it's okay. It's better to use local or static variables for performance when it matters, also it's not well accepted to abuse global variables.
 And then you could revert your changes to center everything and use my approach here https://github.com/drfrag666/RUDE/commit/e8ea3a954284d691e2f88bdc07bc48f1a0e28714 (mostly the same as fabian did).

**Comment by JNechaevsky** [comment]
Ah, `I_InitGraphics` seems to be more reasonable place, thanks! I've got everything working fine now, in both wide and non-wide modes, just need to double check everything and remove absolute code, no need to revert anything. :)

The only thing I wonder about - in RD I have every feature able to change in hot mode, and was never experimenting with anything that require game restarting. I still want to add menu item in "Rendering" section, but the question is - how should it work, i.e. how should it toggle `widescreen` variable only after restart? Probably I'll need some kind of _temporary_ variable, which will show current mode and will change `widescreen` variable only before game exit.

**Comment by JNechaevsky** [comment]
I could introduce a special screen size (`9`) for wide mode, which will add bezel with keeping 4:3 screen mode. Something like this:
![image](https://user-images.githubusercontent.com/21193394/78454463-cb8bc080-76a0-11ea-872e-f7ec21f4898f.png)

**Comment by fabiangreffrath** [comment]
But why?

**Comment by JNechaevsky** [comment]
I don't have a working borders/bezel in wide mode, and planes and stuff becomes broken. By using this approach I could get traditional 4:3 screen size w/o necessity of game restarting.

**Comment by JNechaevsky** [comment]
I've made it, yay! At the first try, by changing `widescreen` variable in game menu, I was calling for quit confirm, but now I have implemented a temp variable which is catching `widescreen` variable and changing it only before quit. How it looks:

![screenshot-doom-00](https://user-images.githubusercontent.com/21193394/78461739-4de1a800-76d4-11ea-8bf9-c258ae3a766f.gif)

**Comment by JNechaevsky** [comment]
Well, it's all done in https://github.com/JNechaevsky/russian-doom/commit/03ae3e838bcaa08cc227c200ab9ef54a54851651 for Doom. More amusements awaits in Heretic and Hexen. 🤤

**Comment by JNechaevsky** [comment]
It's all done. Still, switching not working in hot mode and requires game restarting - need to spend more time, it does not seems to be impossible. As about Hexen, well, it's outdated in every aspect and should be upgraded entirely.

I think I'll release both Doom and Heretic in upcoming weekend or later, still some longer testing needed.

Finally, I would like to thank @DwarsYT, @drfrag666 and @fabiangreffrath for everything happened here. :)

**Comment by JNechaevsky** [comment]
P.S. Just to make things clear about first post, here's how Heretic now looks in wide mode:

![image](https://user-images.githubusercontent.com/21193394/78908051-361a7300-7a8a-11ea-93df-2b7303c6b88b.png)
