### ISSUE TITLE
Implement back "classic" fuzz, and also: "classic+bw", "improved", "improved+bw"

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#160]
Oh yeah, more custom `COLORMAB` dependence and joys of "`if (infragreen_visor ...)`"!

**Comment by JNechaevsky** [comment]
Even better have four different, by implementing back `improved_fuzz` variable:

* Classic (`0`)
* Classic + B/W (`1`)
* Improved (`2`)
* Improved + B/W (`3`)

**Comment by fabiangreffrath** [comment]
What does "improved" mean?

**Comment by JNechaevsky** [comment]
My current implementation (https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/r_draw.c#L390), which is looking like a "random, tv noise fuzz" and never depends on camera position.

**Comment by JNechaevsky** [comment]
Yay.

![screenshot-doom-01](https://user-images.githubusercontent.com/21193394/73614016-6407b500-460c-11ea-97b8-dde15230e723.png)

![screenshot-doom-00](https://user-images.githubusercontent.com/21193394/73613992-29058180-460c-11ea-8d01-2d0f6656d42b.png)
