### ISSUE TITLE
Hexen on Raspberry Pi: strange slowdowns during gameplay that dont happen on Doom or Heretic

### ISSUE THREAD

**Issue by vanfanel** [Russian-Doom/russian-doom#162]
Another source of small slowdowns I can clearly see on SD-driven SBCs like the Raspberry Pi: in Hexen, game seems to slowdown when walking through certain positions on any level, with no enemies on screen, etc.
It seems like Hexen is more intensive in accesing its WAD during gameplay, which is causing these slowdowns even if the game is, otherwise, rock-solid 60FPS in uncapped framerate modes.

So, is there something I can do in the sources to force the whole WAD to be loaded on startup, modify the amount of cached data, etc?

**Comment by JNechaevsky** [comment]
All we have is this: https://github.com/JNechaevsky/russian-doom/blob/master/src/hexen/h2_main.c#L929

Really no idea why such slowdowns may happen. And by the way, are they happening while some kind of sound is playing? Have to agree, precaching whole IWAD sound like a good idea.

**Comment by vanfanel** [comment]
@JNechaevsky Once more, I am sorry for taking so long to answer, I am somewhat busy these days in real life.

The slowdowns do not seem to be related to sound effects (not even ambient sounds, which are common in Hexen). And anyway, sound effects are now pre-catched (GREAT!!). 

What else is doing Hexen periodically that Heretic and Doom do not do? Appart from accesing the WAD more often...

About pre-caching WAD, I did some experiments to investigate these slowdows that happen in Hexen only: I created a small filesystem in RAM (easy to do on GNU/Linux), copied the hexen.wad there, and made the engine use that WAD. Slowdown was also present that way. 
So, what is doing Hexen that Doom and Heretic do not do? Maybe some geometry or texture cache being periodically cleared? Maybe something else?

**Comment by JNechaevsky** [comment]
@vanfanel 👋, a little bit side question, but could you please try to add this line and see if render still works on Pi? And will it have some performance improvements, at least minimal?
Right below this one: https://github.com/JNechaevsky/russian-doom/blob/master/src/i_video.c#L1561 (it's not a final approach, just for testing):
```
    SetSDLVideoDriver();
+++ SDL_SetHintWithPriority(SDL_HINT_RENDER_DRIVER, force_software_renderer ?
+++                         "software" : "opengles2", SDL_HINT_OVERRIDE);
```

I've made some `-timedemo` benchmark tests on real machines with Win11 and Win10, and surprisingly OpenGles2 showing far better results than default Direct3D on Windows. Gles is working on Linux (well, at least on virtual machine), but I'm not entirely sure is it safe to use on specific devices like Pi.

**Comment by vanfanel** [comment]
@JNechaevsky Did a fast test before going to work and seems to work perfectly well on the Pi!
Not much difference in performance, but works and CPU usage seems lower according to TOP!

**Comment by JNechaevsky** [comment]
Excellent news, thank you very much! I've just merged it: https://github.com/JNechaevsky/russian-doom/commit/057d41239017712365b7f2a073ddb1b8548f87da.

Benefits in short words: in `-timedemo` runs, average FPS increased about ~15-30%. In heavily overloaded game scenes with lots of sprites/visplanes FPS increased about... 1-2-3, i.e. this whole optimization very situational, but it's working. 😍

**Comment by vanfanel** [comment]
@JNechaevsky Your continued work on this is AWESOME. I absolutely love Russian-Everything because of your attention to performance and detail :)

**Comment by JNechaevsky** [comment]
@vanfanel it is a five years of working for now, five years of self-asking "what I'm doing to my life"! 🤪 Thanks for kind words, these are two things I have in priority. Except, the port itself is no more about _"Russian (language)"_, it's about features and visuals, aimed for casual playing. 

Honestly, maybe one day I'll change it's name to something more netrual (already have a new name), but the real reason for it is mostly... personal. No one was complaining about it's name, though, just myself.

**Comment by vanfanel** [comment]
@JNechaevsky As a true admirer for the russian history (after all you build the most advanced society on the planet, back in the 20th century, and millions of russians sacrificed their life to save the rest of the european people in  what you call the "great patriotic war!"), I like it's current name :)

**Comment by JNechaevsky** [comment]
A-alright, comrade @vanfanel, then I can be happy about the fact that one of my respected users is happy with port and it's name. Spasibo! ☺️

Oh and by the way, about this initial issue - does Hexen still have a slowdowns? And is it working at all on Pi? I have ported over two of three significant renderer optimizations: sprite sorting and visplane hashing. Improved column clipping breaks renderer (probably because of polyobjects). Some of recent Hexen changes simplified language hot-swapping a lot, but for some unclear reason, things are going bad under the Linux - game may bomb out at startup with really not obivious reason.

**Comment by vanfanel** [comment]
@JNechaevsky You are totally right: Hexen has stopped working on the Raspberry Pi!
```

pi@raspberrypi:~/heretic $ ./russian-hexen 
                                Russian Hexen 5.0                               
M_LoadDefaults: Загрузка системных стандартов.
Сохранение файла конфигурации:
        russian-hexen.ini
V_Init: Инициализация видео.
Сохраненные игры будут расположены в папке:
        savegames/
Z_Init: Инициализация распределения памяти.
Распределение памяти: 0x7fa521d010, выделено 20 Мбайт.
W_Init: Инициализация WAD-файлов.
 добавление: hexen.wad
MN_Init: Инициализация системы меню.
CT_Init: Инициализация данных режима чата.
S_InitScript: Инициализация системы скриптов.
SN_InitSequenceScript: Регистрация наборов звуковых событий.
I_Init: Инициализация состояния компьютера.
I_InitController: X360 Controller
OPL_Init: Используется драйвер 'SDL'.
NET_Init: Инициализация сетевой подсистемы.
I_SDL_PrecacheSounds: Кэширование звуковых эффектов - [...........................................]
ST_Init: Инициализация загрузочного экрана.
R_Init: Инициализация процесса запуска Hexen..................................
P_Init: Инициализация игрового окружения.
D_CheckNetGame: Проверка статуса сетевой игры.
SB_Init: Загрузка патчей.
Запуск игры: "Hexen".
russian-hexen: malloc.c:4028: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted
```

**Comment by Dasperal** [comment]
It's not just Raspberry Pi but all Linux systems! This crush is discussed in issue #252

**Comment by vanfanel** [comment]
@Dasperal Then I will be following that thread, in case some tests are needed. Thanks!
EDIT: Seems it was fixed! Can't wait to get home and test russian-hexen on my Pi!

**Comment by vanfanel** [comment]
@JNechaevsky I have just tested Russian-Hexen current GIT version and guess what? NO MORE slowdowns/stalls in game! Runs like a charm now!
I am closing this issue, as it's not an issue anymore.. Thanks a lot!

**Comment by JNechaevsky** [comment]
Awesome, thanks! BTH, unlike Doom and Heretic, Hexen is still outdated in many aspects and enhanements. I don't have much interest to it. :/

**Comment by vanfanel** [comment]
@JNechaevsky I understand you, Doom is the king and Heretic is a very, very good game, but Hexen... well, it's Hexen. Not great, not terrible :D
