### ISSUE TITLE
Hexen: add in-game menu item for language switching

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#165]
Everything should be as simple as was done in Heretic, except one thing: `DECORATE`. Some in-game text strings are placed in `DECORATE` lumps, which are an integral parts of maps, and I don't see any ways to switch neither only `DECORATE`, nor whole game map after language swapping.

I'm not even sure that `extern int english_language` will work at all in ACS, and looks like the only way is to print warning like _"Please restart the game to apply changes"_ after language switching.

Fortunately, despite of different text strings and different Korax speech (`delay (xx)`) timings, save games are still compatible between English and Russian.

**Comment by fabiangreffrath** [comment]
DECORATE lumps, in Hexen?

**Comment by JNechaevsky** [comment]
Oops, I was meaning `BEHAVIOR`.

**Comment by JNechaevsky** [comment]
All done here. Thank you very much @Dasperal!
