### ISSUE TITLE
Implement "Level brightness" feature

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#170]
There is pretty useful feature in Unity Doom, called "Level brightness". It increases overall level brightness (not gamma-correction or overall screen brightness): segments, sectors and things.

It is **extremly** useful in one simple case: try to play the game in a train, while sun in shining right to the handheld device. Gamma-correction can help a bit for sure, but very high gamma levels are simply killing game colors.

Possible approach:
A variable `overall_brightness` with four levels: 0, 16, 32, 48. Can be increased by slider in Display menu, each level is a integer value added to places like:

*R_AddSprites*
```
lightnum = ((sec->lightlevel + overall_brightness) >> LIGHTSEGSHIFT)+extralight;
```

![screenshot-doom-04](https://user-images.githubusercontent.com/21193394/75605115-f2c6ff00-5af0-11ea-950a-8f0abf824686.gif)

**Comment by JNechaevsky** [comment]
Comparison between Unity and RD. Looks likes a have a bit better things lighting:

![1](https://user-images.githubusercontent.com/21193394/75605476-3e2edc80-5af4-11ea-9888-3e02c93d5903.png)

![2](https://user-images.githubusercontent.com/21193394/75605532-ba292480-5af4-11ea-8afb-6a2be2243129.png)

**Comment by bradharding** [comment]
Hi Julia! I hope you don't mind, but I think I might commandeer this feature for Doom Retro... :grin:

**Comment by JNechaevsky** [comment]
Hello Brad! Sure thing, it's all yours! After some tests I have discovered two things:

* Light values and final results just a little bit different from Unity edition. Probably because of smoothed diminished lighting.
* In fact, this approach seems to be absolutely same to Unity implementation. For example, glowing lights may still be dark. Notable places for comparison: E1M2 glowing area ([screenshot](https://user-images.githubusercontent.com/21193394/75613862-65f96100-5b43-11ea-9cb9-ff3c23062e34.png)) and turned off lights on MAP27 ([screenshot](https://user-images.githubusercontent.com/21193394/75613886-917c4b80-5b43-11ea-9bb4-43dff1281006.png)) - screenshots from RD are made with maximum `level_brightness` level (+64).
