### ISSUE TITLE
Allow menu items to be toggled by arrow keys

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#171]
Allow menu items to be toggled by arrow keys. Could be useful for more than on/off menu items. Logics should be:

* `ENTER` key scrolls forward.
* `<` left arrow scrolls backward.
* `>` right arrow scrolls forward.

Same to ZDoom. Thanks Lord Taurus for suggestion.

**Comment by JNechaevsky** [comment]
Implemented via https://github.com/JNechaevsky/russian-doom/commit/843a0e29109cefdbd83d00fdc1cd4d2508f6dd6b. @fabiangreffrath, worth to suggest for Crispy?

**Comment by JNechaevsky** [comment]
@fabiangreffrath, I beg for pardon, but may I annoy again with suggesting it for Crispy? There is no much work, but it quite useful.

**Comment by fabiangreffrath** [comment]
Would you like to file a PR?

**Comment by JNechaevsky** [comment]
Oh, sure, but before, a small discussion needed. I'll move into Crispy tracker.
