### ISSUE TITLE
Critical error when using -mmap

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#176]
`russian-doom.exe -mmap`:

![image](https://user-images.githubusercontent.com/21193394/76415250-ede43400-63a9-11ea-95b7-664dbb462ac9.png)

This is in `R_InitTranMap`:
```
    Z_ChangeTag(playpal, PU_CACHE);
```

**Comment by fabiangreffrath** [comment]
https://github.com/JNechaevsky/russian-doom/blob/master/src/w_wad.c#L441

**Comment by fabiangreffrath** [comment]
https://github.com/JNechaevsky/russian-doom/blob/master/src/w_wad.c#L501

**Comment by JNechaevsky** [comment]
Uh-oh, I see, thanks! Proper solution must be this, right?
https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/r_data.c#L1056
```
--- Z_ChangeTag(playpal, PU_CACHE);
+++ W_ReleaseLumpName("PALFIX");
+++ W_ReleaseLumpName("PLAYPAL");

// ...or even this?

+++ W_ReleaseLumpName(usegamma <= 8 ? "PALFIX" : "PLAYPAL");
```

Or, thinking more, I really don't need a `PALFIX` here, I could use only `PLAYPAL` for tranlucency table generation.
