### ISSUE TITLE
Update to SDL 2.0.7 and SDL_mixer 2.0.2 (runtime binaries and dev. libraries)

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#18]
Since both SDL and SDL_mixer has been updated recently, I have to check how it will work and will it fix sound issue of previous releases.

As usual, I will use latest [Code::Blocks](http://www.codeblocks.org/) IDE 16.01 with latest and clean bundle of [TDM-GCC](http://tdm-gcc.tdragon.net/) 5.1.0-3 with updated dev. libraries of:

- [SDL2-devel-2.0.7-mingw.tar.gz](https://www.libsdl.org/release/SDL2-devel-2.0.7-mingw.tar.gz)
- [SDL2_mixer-devel-2.0.2-mingw.tar.gz](https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.2-mingw.tar.gz)
- [SDL2_net-devel-2.0.1-mingw.tar.gz](https://www.libsdl.org/projects/SDL_net/release/SDL2_net-devel-2.0.1-mingw.tar.gz) _(was not updated, but needed for compiling)_

Let's get started...

**Comment by JNechaevsky** [comment]
Alright, it's working fine. But I have noticed one annoying thing with sound - it feels like sample rate is strictly increased to 44100, making sound more sharp and more "noisy" (but not laggy). Decreasing `snd_samplerate` config variable gives nothing, but I've done additional test and can confirm that it was working with SDL 2.0.5. Interesting...

But I definitely can't fix this by myself.

@fragglet, @fabiangreffrath, colleagues, maybe you'll find this information useful. 
Just checked, absolutely same situation happens with both Choco and Crispy.

**Comment by bradharding** [comment]
Hi Julian.

This issue was brought up in the Doomworld forums. There's a few things you can try. First, put this before initializing SDL:

```
SDL_setenv("SDL_AUDIODRIVER", "directsound", true);
```

But that might not work in future versions of SDL.

Instead, what I did to fix this is in this commit: https://github.com/bradharding/doomretro/commit/70ba9115c152d4c109565ad55550643fc41a5337.

The other solution, (that I'm yet to try), is to make use of the new `SDL_HINT_AUDIO_RESAMPLING_MODE` hint, because by default it is "low quality".

**Comment by JNechaevsky** [comment]
Good day, Brad!

Thanks for advice, I'll try them. Not sure that there will be any luck, since I haven't any experience with SDL code previously. But it's still worth to try.

**Comment by JNechaevsky** [comment]
Meanwhile, one more problem found. After starting the game in fullscreen mode and changing it to windowed, game window becomes frameless. Alt+arrows are working fine for changing position.

Problem with missing icon in window title still exist.
