### ISSUE TITLE
Doom: add support for automap line antialiasing

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#186]
Looks awesome and seems to be simple to implement (but better to make it optional). Also note, how colors are getting darker near the edges of the screen:

![изображение](https://user-images.githubusercontent.com/21193394/80179432-3463ba00-8609-11ea-9fed-1ff119af1963.png)

**Comment by JNechaevsky** [comment]
Overlay mode also fine:
![изображение](https://user-images.githubusercontent.com/21193394/80180345-3af33100-860b-11ea-8ec4-c2175c5da650.png)

**Comment by JNechaevsky** [comment]
@fabiangreffrath, remember we have upraised this feature very briefly couple of months ago? How about suggestion for Crispy now? I must admit - it's absolutely awesome.

**Comment by fabiangreffrath** [comment]
Phew, the change looks quite massive.
