### ISSUE TITLE
Add support for 5:4 and 16:10 aspect ratios

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#191]
The idea is not to add buch of macroses, but instead, do some extra simple calculations in `I_InitGraphics` like:

```
    if (widescreen == 1)
    {   // 16:9
        screenwidth = WIDESCREENWIDTH;
        origwidth = WIDEORIGWIDTH;
        wide_delta = WIDE_DELTA;
    }
+++ else if (widescreen == 2)
+++ {   // 16:10
+++     screenwidth = WIDESCREENWIDTH - (42 << hires);
+++     origwidth = WIDEORIGWIDTH - 42;
+++     wide_delta = WIDE_DELTA - 21;
+++ }
    else
    {   // 4:3
        screenwidth = SCREENWIDTH;
        origwidth = ORIGWIDTH;
        wide_delta = 0;
    }
```

At least it's worth to try.

**Comment by JNechaevsky** [comment]
Hell yes, it's working! :heart: Comparison photos of running the game on tablet PC with native screen resolution 1280x800: [16:9](https://user-images.githubusercontent.com/21193394/81210979-61d23f80-8fdb-11ea-88ef-de169cac5e4f.jpg) and [16:10](https://user-images.githubusercontent.com/21193394/81211008-6dbe0180-8fdb-11ea-8395-596488de9a94.jpg). 

@drfrag666, have a look, it might be interesting for you: https://github.com/JNechaevsky/russian-doom/commit/f3e2275446186334e92c7116b00189426fa40972. Variable `widescreen == 2` means 16:10 aspect ratio now. 

The most interesting part is here, at i_video.c: https://github.com/JNechaevsky/russian-doom/pull/192/commits/f3e2275446186334e92c7116b00189426fa40972#diff-7e61dc47251785545445d15441b9a87fR1424. The only thing - be very careful with `V_CopyRect` in status bar functions. If something goes wrong even with few pixels, game will not crash, but after changing the level via `IDCLEV` something odd will happen.

**Comment by JNechaevsky** [comment]
Comparison between 4:3 ([screenshot](https://user-images.githubusercontent.com/21193394/81298447-75ce7d80-907d-11ea-916b-878f8ab8d085.jpg)) and 5:4 ([screenshot](https://user-images.githubusercontent.com/21193394/81298482-80891280-907d-11ea-81d3-99a4d19fc0e8.jpg)) aspect ratios, running on native 1280x1024 screen resolution, which is a pure 5:4. Looks likes everything is done, the only thing left is to do same for Heretic. Yay!

**Comment by drfrag666** [comment]
Thanks but i don't feel like adding this now that it's working, i don't want to add more complexity and there are other gameplay issues in RUDE. But hey well done. :thumbsup:

**Comment by JNechaevsky** [comment]
I wonder what's wrong with 21:9 ratio (which is formally `w:1868` / `h:400`)...

![изображение](https://user-images.githubusercontent.com/21193394/82680989-c3d6aa00-9c55-11ea-8d93-a4964f3e78bf.png)

Things are rendered correctly, but level geometry screwed up near left side and does not showing at all near right side.
