### ISSUE TITLE
Archvile messing up the kill count on automap

### ISSUE THREAD

**Issue by mtvile666** [Russian-Doom/russian-doom#193]
I'm not russian but I just found this source port and it seems to scratch all my itches, I wanted to thank you for including the english language option.
This issue I wanted to report is about how the number of monsters/kills on the automap doesnt raise when some of them are ressurected, so for example, I was playing map14 on Plutonia which has 54 monsters to kill, but at the part where the Archvile ressurects dead shotgun guys, I kill them and instead of the max monster count on the map rising like in Crispy Doom (it displays 54 + x number of monsters ressurected in this case) it didnt raise at all, and towards the end of the map I had 54 kills and was under the impression I killed everything but actually there were about 4 or 5 monsters left. Would love to see this fixed in the future, thank you for what youve done with this epic port

**Comment by JNechaevsky** [comment]
Hello @mtvile666 and thanks for your kind words and your time!

Hm, that's odd, I have checked on simple map, resurrected monsters are counting: initially there was only one Archvile and shotgun guy, and after killing shoutgun guy three times I've got 4/2 kills ratio ([screenshot](https://user-images.githubusercontent.com/21193394/81260797-67fc0680-9043-11ea-88a1-d3e6441a10e0.png)).

Important thing is - Lost Souls (both normal and spawned by Pain Elemental) are not counting in kills ratio. Maybe that was the case?

**Comment by mtvile666** [comment]
Sorry, I should have been more clear, the ressurected monsters do count it's just that I noticed they don't change the number of monsters on the map like this: 
![kills](https://user-images.githubusercontent.com/64933455/81283522-2cf1d700-9033-11ea-9e56-f7297439f6c3.PNG)
That's Plutonia Map15 by the way. A real nightmare, you can see that the Archvile ressurected like 20 monsters and it all goes on the total kill count of the map (It has 108 monsters but when something is ressurected it shows 108 + x). I do believe this would be an optional feature to add, its more of a preference of mine, but with this it becomes way easier to track kills imo.
Thank you for your time 👍

**Comment by JNechaevsky** [comment]
All done!

![изображение](https://user-images.githubusercontent.com/21193394/81292198-d5279000-9073-11ea-9816-45e881113564.png)

![изображение](https://user-images.githubusercontent.com/21193394/81292247-ebcde700-9073-11ea-9fcb-b97b285857a3.png)
