### ISSUE TITLE
Problem with textures in Back to Saturn X episode 1

### ISSUE THREAD

**Issue by mtvile666** [Russian-Doom/russian-doom#194]
![screenshot-doom-06](https://user-images.githubusercontent.com/64933455/81241252-2c7c2080-8fe0-11ea-9258-60685d84cfaa.png)

The textures on everything keep changing into random stuff, no idea why this happens. I checked every other port I have installed and this only happens with Russian Doom

**Comment by JNechaevsky** [comment]
Thanks again! I see, what a mess. :open_mouth: Not sure for now what's happening and what to do.

**Comment by fabiangreffrath** [comment]
Could be that you write past some frame buffer boundaries. Remember this one? https://github.com/fabiangreffrath/crispy-doom/issues/524

**Comment by JNechaevsky** [comment]
Oh yes. But does not seems to be related, there is no tutti-frutti effects, just wall textures are infinitely cycling. Same happens even in 4:3 mode, I suppose something screwed up in internal `animdefs` code.

**Comment by JNechaevsky** [comment]
> I suppose something screwed up in internal animdefs code.

It does! Replacing `animdefs[]` (https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/p_spec.c#L108) with vanilla array fixes this case. Now need to understand what's wrong with current one.

**Comment by JNechaevsky** [comment]
...because of fixed `FIRELAVA` animation texture, I have [done](https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/p_spec.c#L130) long time ago. Replacing `FIRELAV2` with vanilla `FIRELAV3` fixes this case entirely. :scream:

**Comment by fabiangreffrath** [comment]
I have just come to the same conclusion. Why did you change the animation sequence in the first place?

**Comment by JNechaevsky** [comment]
Do you remember "bloodfalls" on E4M5? They are all static in vanilla Ultimate Doom, because of choosen `FIRELAV2` instead of `FIRELAV2` texture.

![screenshot-doom-07](https://user-images.githubusercontent.com/21193394/81268021-0b531880-9050-11ea-8c24-6457b7315df1.png)

In some of earlier version of RD I have decided to fix by changing sequence in `animdefs` and adding missing texture from Romero's Doom Dump. Still not sure what was caused texture cycling, but even reverting this fix not a big problem, I still can correct static bloodfalls via `p_fix` approach.

**Comment by JNechaevsky** [comment]
Fixed! 

![screenshot-doom-08](https://user-images.githubusercontent.com/21193394/81268750-05aa0280-9051-11ea-9760-15835765975a.png)

_self-note: do something about "ultra-nightmare!" patch, it's looking awful with non-standard graphics._

**Comment by fabiangreffrath** [comment]
Turns out Vanilla Doom compatibility is fragile and sensitive. 😉

**Comment by JNechaevsky** [comment]
True, true. It's really interesting how some things may turn into consequences after so much time! 

From another hand, I wish everything was _that_ clear and easy few years ago, when I was just started RD. Many things in the code that was hard and unclear back then, now looks easy and obvious. Many, but not all, of course.
