### ISSUE TITLE
Question: Does Russian Doom have support for Boom, MBF, among some others?

### ISSUE THREAD

**Issue by MrRajhen** [Russian-Doom/russian-doom#206]
If it's a yes, then congrats Nechaevskaya, you made a near-perfect port
If it's a no, then congrats Nechaevskaya, you made a near-perfect port

(Russian Doom is a good port imo :) )

**Comment by JNechaevsky** [comment]
Thanks for good words! Sadly, no, RD does not support BOOM and other advanced specifications, except some DeHacked advantages in Doom. I don't have any plans to implement them, it's too complicated for me, I'm afraid.

P.S. I'm thinking to release an update for all games in the middle of September, that's will be a project's four years anniversary.
