### ISSUE TITLE
Idea: "Russian Strife"

### ISSUE THREAD

**Issue by MrRajhen** [Russian-Doom/russian-doom#208]
I'm a big fan of Strife, but there has never been a source port which keeps the gameplay near intact while offering excellent QoL improvements, after seeing how much Russian Doom can do, I'd suggest the next Russian port would be for Strife, maybe not now, but perhaps sometime soon.

**Comment by JNechaevsky** [comment]
Hello again! Strife was started but very soon I have lost all interest to it. Later, some of my graphical resources were used in separate Russian translation project for GZDoom, which grown well.

I can't guarantee that I will return to work on Strife in RD-like improvements, but neither I don't want to reject this idea. Maybe one day later, but really no idea when exactly.

**Comment by MrRajhen** [comment]
> I can't guarantee that I will return to work on Strife in RD-like improvements, but neither I don't want to reject this idea. Maybe one day later, but really no idea when exactly.

Wow, that's awesome! thank you so much for replying :)
