### ISSUE TITLE
Support dedicated tracks for each map

### ISSUE THREAD

**Issue by DwarsYT** [Russian-Doom/russian-doom#209]
[This pull](https://github.com/fabiangreffrath/crispy-doom/pull/633) of Crispy Heretic added support for dedicated music tracks on each map so that a project like the [RAVEN MIDI Pack project](https://www.doomworld.com/forum/topic/114080-raven-midi-pack-project-complete/) could be played on it. I was wondering if the same thing could be done for this port.

If it isn't done already, the same can potentially apply to the episode 4 tracks for The Ultimate Doom.

**Comment by JNechaevsky** [comment]
Hello @DwarsYT and thanks for suggestion! I've never heard about  dedicated tracks for Doom and Heretic before, but sure, I can apply this - done in https://github.com/JNechaevsky/russian-doom/commit/b3a3d9480e496b30c734e4718546b31e64b09091 (seems to be done already for Doom). 

I'm planning to release update for all three games on 2020-09-16.
