### ISSUE TITLE
Heretic: ENGAGE functionality on Black Plague (and above)

### ISSUE THREAD

**Issue by DwarsYT** [Russian-Doom/russian-doom#211]
IDCLEV## works for Nightmare in Doom in this port, so ENGAGE##  should probably do the same for Black Plague. This was done in Crispy Doom here: https://github.com/fabiangreffrath/crispy-doom/pull/639

**Comment by JNechaevsky** [comment]
Sure, why not. Done via https://github.com/JNechaevsky/russian-doom/commit/bfd48860f54cbdaecc2e064c76873799e83fbd43, thanks for suggestion!
