### ISSUE TITLE
Hexen: endgame graphics not adjusted for 16:9 aspect ratio

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#213]
Exactly what the title says. The `CHESSC`, `CHESSM` and `CHESALL` graphics don't display correctly when the game is played on a 16:9 aspect ratio.

Screenshot of endgame screen, playing as Cleric:
![screenshot-hexen-01](https://user-images.githubusercontent.com/8249996/94365081-7f946400-00a4-11eb-87e0-eb61ece967af.png)

**Comment by JNechaevsky** [comment]
Ouch! Thank you, fixed in https://github.com/JNechaevsky/russian-doom/commit/dc7af5c563f28a7b491d45fae5837fac05d6ca43.
