### ISSUE TITLE
Middle mouse button is not handled while active game menu

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#216]
To be more clear: pressing middle mouse button is not stopping `messageToPrint` routine. Try to start a new game, then press `F9` - appeared message can be stopped by any key, except middle mouse button. This seems to be vanilla behavior.

Possible solution - listen for all `data1` mouse events and send a dummy event, something like this (https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/m_menu.c#L9854):

```
+++         if (ev->data1)
+++         {
+++             key = ev->data1;
+++             mousewait = I_GetTime() + 15;
+++         }

            if (ev->data1&1)
            {
                key = key_menu_forward;
                mousewait = I_GetTime() + 15;
            }

            if (ev->data1&2)
            {
                key = key_menu_back;
                mousewait = I_GetTime() + 15;
            }
```

**Comment by JNechaevsky** [comment]
This also makes possible to bind middle button (finally!). Nasty code draft:
TODO - clear binding by trying to bind same key?

```
//
// Binding routine
//
void M_RD_Mouse_Pitto (int key)
{
    messageToBind = 0;

    switch (key)
    {
        case 1:             mousebforward = 0;  break;
        case 2:             mousebforward = 1;  break;
        case 4:             mousebforward = 2;  break;
        case 173:           mousebforward = 3;  break;
        case 175:           mousebforward = 4;  break;
        case KEY_ESCAPE:                        return;
        default:                                break;
    }

    printf ("%d \n", key);
}

//
// Invoked by menu system
//
void M_RD_Change_Pitto (int choice) 
{
    M_RD_StartBinding(M_RD_Mouse_Pitto);
}
```

@hfc2x, I hope I'm close to the result! :hushed:

**Comment by JNechaevsky** [comment]
Mouse binding menu now fully functional, `MMB` working fine. 
![image](https://user-images.githubusercontent.com/21193394/97539679-749a5f80-19d3-11eb-99cf-d4efb144d766.png)

There is only one strange thing left - re-binding next/prev weapons with side mouse button may have a strange result, like when I'm pressing `LEFT` button, `BUTTON #3` is binded. Probably this because of how prev/next weapon events are handled by menu system. 

Another oddity with side button is magic numbers. Side button up (wheel down) may return different key values, not just initial `173`, but also `8` and `16`, but it also happening while binding prev/next weapon.

```
void M_RD_Mouse_Attack (int key)
{
    messageToBind = 0;

    switch (key)
    {
        case 13:            mousebfire = 0;  break;
        case 127:           mousebfire = 1;  break;
        case 4:             mousebfire = 2;  break;
        case 8:
        case 16:
        case 173:           mousebfire = 3;  break;
        case 175:           mousebfire = 4;  break;
        case KEY_ESCAPE:    return;
        default:            break;
    }
    // printf ("Fire: %d \n", key);
}

void M_RD_Mouse_Bind_FireAttack (int choice) 
{
    M_RD_StartBinding(M_RD_Mouse_Attack);
}
```

**Comment by hfc2x** [comment]
Does this work with mouses that have an arbitrary number of buttons?

**Comment by JNechaevsky** [comment]
Nope :( I have a Razer Viper gaming mouse with two extra side buttons on the right side, six in total. In Setup executable upper button is recognized as fifth button, and lower button is recognized as fourth. In game both extra buttons are recognized as third and fourth buttons respectively. No idea why.

Either Chocolate code does not have a support for 4+ mouse buttons, or I haven't setup up extra buttons properly in Razer utility.
