### ISSUE TITLE
Use `SDL_SetWindowBrightness` instead of gamma-correction?

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#221]
Interestingly, `SDL_SetWindowBrightness` gives an **impressive** results with in-game screen gamma, so I may finally get rid of custom improved palette. From another hand, this trick also changes brightness in whole screen area, not just in game window. Also, screenshots will not be affected by this trick.

Anyway, should be something like this at `SetVideoMode`. Instead of `0.75` some kind of floating value may be used (from gamma-correction slider, maybe?):

```
    texture = SDL_CreateTexture(renderer,
                                pixel_format,
                                SDL_TEXTUREACCESS_STREAMING,
                                screenwidth, SCREENHEIGHT);

+++ SDL_SetWindowBrightness(screen, 0.75);

    // Initially create the upscaled texture for rendering to screen

    CreateUpscaledTexture(true);
```

**Comment by fabiangreffrath** [comment]
Could you probably post some screenshots to compare with regular gamma correction, please?

**Comment by JNechaevsky** [comment]
I wish, but there are no difference in screenshots, they are not affected by this. :-( 
Please, just take a try to add one line of code from my message above, you'll see the difference.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, nope, this is not a _proper_ solution. I'll explain it's pros and cons:

Pros:
* Absolutely lovely results in both darken and brighter gamma. By using `0.05` step and limiting values to `-0.50` and about `2.0` it is possible to get a 100% "eye-candy" picture. Perfect control.
* Far better results than using in-game gamma-correction.
* In-game gamma-correction levels/tables are no longer needed.
* Absolutely independent from `PLAYPAL`.
* Extremely easy to implement.

Cons:
* It's changing monitor's gamma, and thus, barely it is a good idea to use it for windowed mode.
* By using `Alt+Tab`, monitor's gamma will be switching from normal value (`1.0`) to port value. It may be annoying.
* Screenshots are not affected by display gamma, they still will use in-game gamma-correction level. 
* Same to previous, standard gamma-correction will be used in case of user is streaming the game.
* There is chance, that after silent crash (w/o error message) monitor's gamma will stuck at port level. User will need to run the game and close it.

That's it. I see that GL-PrBoom+ is using this approach, and AFAIR, some old games from 2000th were using it.
There is a function in SDL that allows to change window-only brightness, not gamma, but that's not we are seeking for.

Catastrophe. :disappointed:

**Comment by JNechaevsky** [comment]
In fact - no, shouldn't happen. Despite of awesome result, this approach is _completelly_ obsolete. AFAIR, many of first hardware accelerated games were using same gamma mechanics back in 2000th, but since Doom itself is a) not a game to player only in fullscreen, and b) people can stream it, this is not good to go. 

Making a switch of changing gamma via PLAYPAL/Monitor does not looks like smart either, and more of that, it will lead to the code complication. 

![image](https://user-images.githubusercontent.com/21193394/111606672-8e084080-87e8-11eb-97ec-446f3f162f59.png)
