### ISSUE TITLE
Overlayed automap remains on title screen after ending the game

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#225]
Steps to reproduce:

1. Start game normally.
2. Open automap, enable "overlay" mode.
3. End game. Automap remainings will be placed on title screen:
![image](https://user-images.githubusercontent.com/21193394/113502051-54e30680-9532-11eb-8d5a-30a148b15657.png)

@fabiangreffrath, :wave: it also happens same way in Crispy. This is how it can be fixed, but is it correct?

`d_main.c @@ D_Display`
```
    // [crispy] in automap overlay mode,
    // draw the automap and HUD on top of everything else
--- if (automapactive && automap_overlay)
+++ if (gamestate == GS_LEVEL && automapactive && automap_overlay)
    {
        AM_Drawer ();
        HU_Drawer ();

        // [crispy] force redraw of border
        viewactivestate = false;
    }
```

**Comment by fabiangreffrath** [comment]
I'd say `automapactive` should be outright disabled when the game ends.

**Comment by JNechaevsky** [comment]
Oh, sure, so it should be as simple as (tested and working fine):
```
void M_EndGameResponse(int key)
{
    if (key != key_menu_confirm)
    return;

+++ automapactive = false;
    currentMenu->lastOn = itemOn;
    M_ClearMenus ();
    D_StartTitle ();
}
```

Should I file a PR? If so, is there some comment like `// [crispy] ...` needed?

**Comment by fabiangreffrath** [comment]
Yes, please, a PR is appreciated. Though, I'd prefer to have the change in `D_StartTitle()` - and with a short comment, please.
