### ISSUE TITLE
cannot find the codeblock files

### ISSUE THREAD

**Issue by kittibyte** [Russian-Doom/russian-doom#226]
the codeblock project files/codeblock folder do not seem to be inside the git repo, any way of fixing this?

**Comment by JNechaevsky** [comment]
Codeblocks/MSVC project files was outdated and removed long time ago, for now building under Windows is available via [MSYS](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows). 
I have no plans to include back Cb/MSVC.

**Comment by kittibyte** [comment]
ah that explains it, thank you very much
