### ISSUE TITLE
Upgrade full screen graphics to 21:9

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#227]
I need to do a couple of things:

1. Upgrade full screen graphics to 21:9, using GFX by Nash Muhandes. They are far better than I did, and more of that, they are much closer to the original 4:3 ones. Also, I need to recreate Russian text screens, making them also more original-like, not improved.
2. Possibly remove `*-wide.wad` PWADs entirely by placing all graphics into `doom-common.wad`. Some extra checkings for lumps replacement will needed.
3. Draw these full screen graphics by using `V_DrawPatchFullScreen` from one well known respected port. 
4. Draw status bar GFX always centered, matters no how wide it is and which `X` coordinate is given.
5. Double check if my 21:9 aspect ratio is properly covering real 21:9 monitor. Can purchase it, but don't have a room on my desktop for it. VmWare Workstation is a thing, but...

**Comment by JNechaevsky** [comment]
There is also a punctuation typo in "Бизнес директор" (just a "BIZ" in English), as a compound word it should have a hyphen, i.e. "Бизнес-директор". 

Still, it's just a shorten, not a really existing term, because properly it writes as "Директор по развитию бизнеса", but there is no way to fit such a long string in 320x200 pixel canvas.

**Comment by JNechaevsky** [comment]
Just awesome! :heartbeat:
![wi](https://user-images.githubusercontent.com/21193394/114976837-50521280-9e8f-11eb-8c91-84458510c718.gif)

**Comment by JNechaevsky** [comment]
I haven't kept purely original 320:200 parts to be 100% vanilla-like, there are still some shadows beneath texts (although they now looks less intrusive). RD is about visual improvements, not about keeping everything vanilla-like.

@NashMuhandes, thank you very much  for such a Masterwork as well as for approval for using it!
@K0stov was asking for it, since I was not able to contact you directly.

Also, thanks @Dasperal for help with Bunny scrolling code. Honestly, I was never able to handle it.

This job is done now. 

(_p.s. @K0stov :pig_nose::pinching_hand: !!_)

**Comment by nashmuhandes** [comment]
Looks great - glad to know these graphics are useful to you. :)

**Comment by K0stov** [comment]
> (_p.s. @K0stov 🐽🤏 !!_)

Пщ-а!
