### ISSUE TITLE
Parameter to disable Ultra-Nightmare difficulty

### ISSUE THREAD

**Issue by OpenRift412** [Russian-Doom/russian-doom#228]
I think this would be a good compatibility option to have the ability to disable the Ultra-nightmare option in the difficulty menu, that way there isn't any weird clashes with WADs that use custom menu graphics.

**Comment by JNechaevsky** [comment]
There is already a checking condition: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/d_main.c#L1914

It reads like "if loaded PWAD have a replaced M_ROUGH gfx patch, then replace Ultra-Nightmare gfx with empty patch, but still allow to choose it". There is no way to hide it with any possible condition, though.

Adding a command line parameter / ingame switch for disabling an UNM skill level is not an acceptable way to go.

**Comment by OpenRift412** [comment]
> There is already a checking condition: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/d_main.c#L1914
> 
> It reads like "if loaded PWAD have a replaced M_ROUGH gfx patch, then replace Ultra-Nightmare gfx with empty patch, but still allow to choose it". There is no way to hide it with any possible condition, though.
> 
> Adding a command line parameter / ingame switch for disabling an UNM skill level is not an acceptable way to go.

Well how about having it disabled when running the -vanilla parameter?

**Comment by JNechaevsky** [comment]
But what if player want's to play in UNM skill in `-vanilla` mode? :wink: 

UNM skill levels does not affecting gameplay until it's selected. But I've also have to say that "vanilla" mode is not bringing back pure 100% vanilla experience. It's just retains many vanilla bugs, but not all of them, and still, most of rendering code is different as well as static limits are also removed.

**Comment by OpenRift412** [comment]
> But what if player want's to play in UNM skill in `-vanilla` mode? 😉
> 
> UNM skill levels does not affecting gameplay until it's selected. But I've also have to say that "vanilla" mode is not bringing back pure 100% vanilla experience. It's just retains many vanilla bugs, but not all of them, and still, most of rendering code is different as well as static limits are also removed.

Then why go through the effort of removing all the options from the options menu and having it mimic the vanilla menus in that case? If someone wanted to load UNM in vanilla mode they could just do it from the command line anyway.
