### ISSUE TITLE
Message and Automap name text misaligned

### ISSUE THREAD

**Issue by OpenRift412** [Russian-Doom/russian-doom#229]
From what I can tell, the text that shows for both messages in the top-left and the automap name in the bottom-left seems to be off by one "pixel" (pixel relative to the text's resolution itself). 

Here's an example

**Crispy Doom**
![DOOM0007](https://user-images.githubusercontent.com/29780788/115452538-8e7f6700-a1ec-11eb-92f0-ed00c1bfef37.png)

**Russian Doom**
![screenshot-doom-00](https://user-images.githubusercontent.com/29780788/115452566-96d7a200-a1ec-11eb-9978-18c453735b23.png)

**Comment by JNechaevsky** [comment]
True, this is not because of shadows, but because of Russian "Й" character, which takes one extra pixel in height. Not exactly character itself, but it's stroke. To keep both languages in same placement, I've decided to keep them in one line.

**Comment by OpenRift412** [comment]
> True, this is not because of shadows, but because of Russian "Й" character, which takes one extra pixel in height. Not exactly character itself, but it's stroke. To keep both languages in same placement, I've decided to keep them in one line.

Agh damn, that triggers my OCD so bad....

**Comment by JNechaevsky** [comment]
Don't take is serious, this is just a game! :smirk:
