### ISSUE TITLE
Apply brightmap to PLAT1 texture

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#238]
@fabiangreffrath may I ask you for opinion and critical eye? I'm totally confusing about applying / suggesting. :confused:

Despite of big size (128x128), `PLAT1` is not very often guest on Doom 1 and 2 maps, but it exist in shareware version.
It have a small green lamp, well, at least it's looks like lamp, applying `greenonly1` b-map seems to be logical, and most important - it doesn't looking awfully bright.

From another hand, I have an odd feeling "is it really necessary to do" and probably better leave this texture for good.

What do you think? I leave some screenshot examples of: [MAP09](https://user-images.githubusercontent.com/21193394/116744210-acc23f80-aa02-11eb-9491-b6731b7f90de.png), [MAP10](https://user-images.githubusercontent.com/21193394/116744225-b51a7a80-aa02-11eb-883b-1aa7dedbe728.png), [MAP13](https://user-images.githubusercontent.com/21193394/116744247-be0b4c00-aa02-11eb-95a0-b2a403ab2a56.png) and [MAP20](https://user-images.githubusercontent.com/21193394/116744299-cbc0d180-aa02-11eb-8556-3d6ea3535188.png).

**Comment by fabiangreffrath** [comment]
Honestly, I am not sure if this is really supposed to be a lamp. Let's say I never missed a brightmap for this texture, but maybe my opinion changes once I see this in-game.

**Comment by JNechaevsky** [comment]
And I still in doubt. Hard to say really, but what else can it be? A mark or nameplate? Vertical red ones are looks like capacitors.
But it's still a theory, most important how it will look in the game, and feelings are a bit mixed, like: "does not looks bad in single texture, but something not right when texture get repeated".

![image](https://user-images.githubusercontent.com/21193394/117427019-3d31e000-af2d-11eb-9211-1133179ccc0c.png)

This gives me another idea, which is really crazy - add some animations to b-maps, like blinking and storbing. Not on every textures, but only to selective ones, on selective map lines, on selective vanilla maps. But this will require a lot of extra work by reviewing all vanilla maps, and most bad thing - this will bring much complications to the b-map code. Another problem is - Doom itself is not about standing on one place and looking around, it's about moving.

**Comment by JNechaevsky** [comment]
Nope, let's just reject this idea. Having a higher-than-reasonable amount of bmaps is good, but trying to lit everything looking like a lamp or diode probably bad way to go.
