### ISSUE TITLE
Optimize brightmaps even more

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#239]
The idea is to reduce checking conditions in `R_StoreWallRange` (https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/r_segs.c#L866). Checking for game versions must be removed, and `midtexture`/`toptexture`/`bottomtexture` checks should be added. Logic should be "if segment does not have a top texture, don't lookup top brightmap".

Something like this...
```
    if (brightmaps && brightmaps_allowed)
    {
        if (midtexture)
        {
            // Red only
            if (midtexture == bmaptexture01 || midtexture == bmaptexture02}
            walllights_middle = fullbright_redonly[lightnum];
        if (toptexture)
        {
            // same with top segment
        }
        if (bottomtexture)
        {
            // same with bottom segment
        }
    }
```

This literally will be a micro-optimization, current b-map code is working absolutely fine and does not have any hickups.
Also I need to recreate b-map testing maps for D1, D2, TNT and Plutonia, since they are lost.

**Comment by fabiangreffrath** [comment]
> Also I need to recreate b-map testing maps for D1, D2, TNT and Plutonia, since they are lost.

Tada: https://github.com/fabiangreffrath/test-wads

**Comment by JNechaevsky** [comment]
This is exactly I was needed for, thank you very much!
