### ISSUE TITLE
Building on Arch

### ISSUE THREAD

**Issue by DoubleAgentDave** [Russian-Doom/russian-doom#250]
I'm trying to build this on Arch linux, the trouble is I'm getting an error, which maybe related to compiler options of either
d_main.c:2472:31: error: expected ‘)’ before ‘PACKAGE_DOOM_VERSION’
 2472 |     DEH_printf("Russian Doom " PACKAGE_DOOM_VERSION);
      |               ~               ^~~~~~~~~~~~~~~~~~~~~
      |                               )
make[3]: *** [Makefile:539: d_main.o] Error 1
when running the autogen method of compiling or:
d_main.c:1280:34: error: expected ‘)’ before ‘PACKAGE_HERETIC_VERSION’
 1280 |     DEH_printf("Russian Heretic " PACKAGE_HERETIC_VERSION);
      |               ~                  ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                  )
when running cmake,
I'm fairly sure I've got all the dependencies, this just seems to be an error when trying to compile using the function as written in deh_str.c
Is this something other people are seeing? Or have I missed a dependency somewhere?

**Comment by JNechaevsky** [comment]
Hello, thanks for report!

Can reproduce it under Linux, but not happening under Windows/MSYS. Apparently, there are two problems:

1) Missing comma between `"Russian Doom "` and `PACKAGE_DOOM_VERSION`. Once it added, this leading to second problem.
2) 
```
d_main.c: In function ‘D_DoomMain’:
d_main.c:2472:33: error: ‘PACKAGE_DOOM_VERSION’ undeclared (first use in this function); did you mean ‘PACKAGE_VERSION’?
 2472 |     DEH_printf("Russian Doom ", PACKAGE_DOOM_VERSION);
      |                                 ^~~~~~~~~~~~~~~~~~~~
      |                                 PACKAGE_VERSION
```

@Dasperal could you please help us?

**Comment by Dasperal** [comment]
The problem is that there should be `BUILD_*_VERSION` instead of `PACKAGE_*_VERSION`.
Automatic renaming did not affect Unix-specific code and I did not notice this during commit. And also did not test the changes on Linux.

We definitely need to implement CI to avoid these problems in future

**Comment by JNechaevsky** [comment]
@DoubleAgentDave, please, take a try now. Everything should be fine.
