### ISSUE TITLE
Hexen memory allocation crash

### ISSUE THREAD

**Issue by DoubleAgentDave** [Russian-Doom/russian-doom#252]
Last issue solved perfectly :) Heretic plays really nicely! Everything works except some graphical glitches with strife, which I assume is still at an early stage of development, I'll submit a bug report for that only if you want, and Hexen which crashes on startup to a memory dump. I'm not sure if this is an issue my end so if you need more details please ask and i can try again later. Here is the crash report (I've replaced home directory name with ~):

                                Russian Hexen 4.1
M_LoadDefaults: Загрузка системных стандартов.
Настройки программы будут расположены в папке:
 	~/.local/share/russian-doom/
Сохранение файла конфигурации: ~/.local/share/russian-doom/russian-hexen.ini
V_Init: Инициализация видео.
Сохраненные игры будут расположены в папке:
 	~/.local/share/russian-doom/savegames/
Z_Init: Инициализация распределения памяти.
Распределение памяти: выделено 0x7fdff3bc1010 байт.
W_Init: Инициализация WAD-файлов.
 добавление: ~/.doomwads/iwads/HEXEN.WAD
MN_Init: Инициализация системы меню.
CT_Init: Инициализация данных режима чата.
S_InitScript: Инициализация системы скриптов.
SN_InitSequenceScript: Регистрация наборов звуковых событий.
I_Init: Инициализация состояния компьютера.
Невозможно получить доступ для чтения/записи в 0x388: Operation not permitted
	Вероятно, вам придется запустить программу с правами
	суперпользователя (root) для возможности проигрывания
	MIDI музыки в режиме OPL.
OPL_Init: Используется драйвер 'SDL'.
NET_Init: Инициализация сетевой подсистемы.
I_SDL_PrecacheSounds: Кэширование звуковых эффектов..............................................
ST_Init: Инициализация загрузочного экрана.
R_Init: Инициализация процесса запуска Hexen..................................
P_Init: Инициализация игрового окружения.
D_CheckNetGame: Проверка статуса сетевой игры.
SB_Init: Загрузка патчей.
Запуск игры: "Hexen".
russian-hexen: malloc.c:2539: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

Otherwise nice set of ports!

**Comment by Dasperal** [comment]
I have encountered this problem, but I could not track why this is happening. We officially do not support Linux so I left it as is.

Maybe when the Hexen codebase gets updated this issue will be solved or at least be easier to track.

Or maybe @JNechaevsky will find the cause of this problem.

**Comment by DoubleAgentDave** [comment]
OK, I'll do some hunting around myself as well to see if I can find the problem, it'll take me a few weeks to get around to it at the moment. But I'll drop the solution here if I can find one.

**Comment by DoubleAgentDave** [comment]
OK, just notes: if OPL music is disabled, and software rendering is used the memory issue seems to at least be delayed for a while and the game is playable. Though I'm not sure if this is a result of just reducing memory usage or not. I'm just using this thread to record the issue for the moment, if you want to close it because of not supporting linux I'll understand.

**Comment by Dasperal** [comment]
I remembered! This issue happens in full-screen mode. In windowed mode, Hexen runs fine, though I did not play it for long.

I tried to find the cause with the CLion debugger but it only shows that the signal gets fired when the crash happens and some kernel stack trace with no useful information.

I tried to step through the code for several game ticks but no signals got fired. Also, no signals after I "let it go" but the game was still broken with stuck graphics and no reaction on inputs.

Debugging is complicated by the fact that the game captures the cursor and you can't use the mouse in other windows. Though you can't even see other windows if you have only one monitor.

**Comment by DoubleAgentDave** [comment]
Yeah, agreed with the debugging annoyances even with two monitors it's a pain. I am still finding in windowed mode the game crashes with a:

free(): invalid pointer
Aborted (core dumped)

error. I've played with a few compilation options to see if it's an optimisation issue, but I tried -O0 and -Os and the error persists. 
Weirdly the only warning I see when compiling is an issue with strife, which even when solved doesn't help strife run:

p_inter.c: In function ‘P_GivePower’:
p_inter.c:424:19: warning: array subscript 6 is above array bounds of ‘int[6]’ [-Warray-bounds]
  424 |     player->powers[power] = 1;
      |     ~~~~~~~~~~~~~~^~~~~~~
In file included from doomstat.h:36,
                 from p_inter.c:27:
d_player.h:124:25: note: while referencing ‘powers’
  124 |     int                 powers[NUMPOWERS];
      |                         ^~~~~~

I could make this error go away by just replacing   
124 |     int                 powers[NUMPOWERS]; 
with
  124 |     int                 powers[NUMPOWERS+1];

But given that this does nothing to help run strife, let alone hexen, it's not something that really matters. I'll try messing with valgrind or something in a few days.

I think maybe your original idea of waiting for something to change upstream might be the most sensible way to go about this.

**Comment by JNechaevsky** [comment]
`gdb` output of crashing Hexen under Debian:

```
Запуск игры: "Hexen".
[New Thread 0x7fffcbfff700 (LWP 18100)]
[New Thread 0x7fffcb7fe700 (LWP 18101)]
[New Thread 0x7fffcaffd700 (LWP 18102)]
[New Thread 0x7fffca7fc700 (LWP 18103)]
corrupted size vs. prev_size

Thread 1 "russian-hexen" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Нет такого файла или каталога.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c65859 in __GI_abort () at abort.c:79
#2  0x00007ffff7cd03ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7dfa285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7cd847c in malloc_printerr (str=str@entry=0x7ffff7df843a "corrupted size vs. prev_size") at malloc.c:5347
#4  0x00007ffff7cd8aeb in unlink_chunk (p=p@entry=0x5555564d7610, av=0x7ffff7e2bb80 <main_arena>) at malloc.c:1454
#5  0x00007ffff7cda00b in _int_free (av=0x7ffff7e2bb80 <main_arena>, p=0x5555564c75f0, have_lock=<optimized out>) at malloc.c:4342
#6  0x00007fffdcdab87f in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#7  0x00007fffdcd9d9b9 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#8  0x00007fffdcdacc41 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#9  0x00007fffdcdad3b7 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#10 0x00007fffdc78215d in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#11 0x00007fffde082015 in  () at /lib/x86_64-linux-gnu/libGLX_mesa.so.0
#12 0x00007ffff7f3d307 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#13 0x00005555555753fd in I_FinishUpdate () at i_video.c:910
#14 0x00005555555902cf in DrawAndBlit () at h2_main.c:1124
#15 H2_GameLoop () at h2_main.c:1000
#16 0x0000555555590b3d in D_DoomMain () at h2_main.c:735
#17 0x000055555556f898 in main (argc=<optimized out>, argv=<optimized out>) at i_main.c:117
(gdb) Quit
```

**Comment by Dasperal** [comment]
I tried to find a commit that introduced this crush and... the first commit on git f31fe5b7b8b98b78b1f30275fd4eb5d36e6a8bfd still has it.
```
<...>
SB_Init: Загрузка патчей.
Запуск игры: "Hexen".
corrupted size vs. prev_size
```
and gdb output
```
<...>
OPL_Init: Using driver 'SDL'.
NET_Init: Инициализация сетевой подсистемы.
ST_Init: Инициализация загрузочного экрана.
[New Thread 0x7fffe094d700 (LWP 75974)]
[New Thread 0x7fffbe849700 (LWP 75975)]
[New Thread 0x7fffbe048700 (LWP 75976)]
[New Thread 0x7fffbd847700 (LWP 75977)]
[New Thread 0x7fffbd046700 (LWP 75978)]
[New Thread 0x7fffbc845700 (LWP 75979)]
[New Thread 0x7fffa7fff700 (LWP 75980)]
[New Thread 0x7fff9f7fe700 (LWP 75981)]
[New Thread 0x7fffa76bd700 (LWP 75982)]
[New Thread 0x7fffa6ebc700 (LWP 75983)]
[New Thread 0x7fffa66bb700 (LWP 75984)]
[New Thread 0x7fffa5eba700 (LWP 75985)]
R_Init: Инициализация процесса запуска Hexen..................................
P_Init: Инициализация игрового окружения.
D_CheckNetGame: Проверка статуса сетевой игры.
SB_Init: Загрузка патчей.

Thread 1 "russian-hexen" received signal SIGSEGV, Segmentation fault.
0x00007ffff7931a2f in unlink_chunk (p=p@entry=0x555555b9acb0, 
    av=0x7ffff7a84b80 <main_arena>) at malloc.c:1453
```

**Comment by fabiangreffrath** [comment]
This should be it:
```
--- a/src/hexen/h2_main.c
+++ b/src/hexen/h2_main.c
@@ -1287,7 +1287,7 @@ static void PageDrawer(void)
     if (aspect_ratio >= 2)
     {
         // [JN] Clean up remainings of the wide screen before drawing
-        V_DrawFilledBox(0, 0, WIDESCREENWIDTH, SCREENHEIGHT, 0);
+        V_DrawFilledBox(0, 0, screenwidth, SCREENHEIGHT, 0);
     }
 
     V_DrawRawScreen(W_CacheLumpName(pagename, PU_CACHE));
```

**Comment by JNechaevsky** [comment]
Jesus Christ... 😩 Thanks @fabiangreffrath!
