### ISSUE TITLE
Incorrect Message for Blue Skull Key.

### ISSUE THREAD

**Issue by CthulhuInACan** [Russian-Doom/russian-doom#258]
When picking up a Blue Skull Key in Russian Doom 4.7.1 , the Message says "Picked up a Red Keycard."
The skull key is picked up correctly, so there's no gameplay issues, the message is just wrong.

**Comment by JNechaevsky** [comment]
Thanks for spotting out! Fixed in https://github.com/JNechaevsky/russian-doom/commit/8969d8d7e326a19dc810eae3d97c192aa4c0863b.
