### ISSUE TITLE
Russian Doom gameplay feature documentation

### ISSUE THREAD

**Issue by cubebert-github** [Russian-Doom/russian-doom#259]
So I've been adding documentation of the available gameplay features for Russian Doom and it's almost complete. I just have a couple of questions to ask regarding some of the features.

1. What does the "Corpses Sliding From The Ledges" feature do? Is it the thing where monsters can sometimes fall down if they are killed next to a ledge?

2. Could you show me an example of the "Fix Errors Of Vanilla Maps" option?

So far, I think I've got it down. Unfortunately, I'm not fluent in Russian, so either someone else will have to translate it for the Russian text file or it will have to be omitted.

![2021-07-19_105207](https://user-images.githubusercontent.com/24487663/126205184-5fad2784-8b53-47f6-b5da-fc691214a381.png)

**Comment by JNechaevsky** [comment]
Awesome! Here's explanations for pointed out features:

**Corpses Sliding From The Ledges**
This is a small emulation of realistic physics by Lee Killough. In vanilla Doom, when you kill a monster standing on some kind of ledge even by few pixels, it will not fall down if there is no momentum applied. Something like this, to be more clear:

![image](https://user-images.githubusercontent.com/21193394/126519459-3e0ca76d-b976-45d7-85cf-f52261878929.png)

When this feature is enabled and monster's center of mass is not placed on floor, a small momentum will be applied to corpse so it can "slip" from ledge.

**Fix Errors Of Vanilla Maps**
This technique allows to do some corrections in vanilla maps and created by Brad Harding. This applies various fixes to lines (textures, offsets, effect, flags), sectors and vertexes. Sometimes fixes are _too_ fanatical, especially with texture offsets, but all of them are "canonical". Here's most notable examples between comparison with on and off:

MAP01:
![image](https://user-images.githubusercontent.com/21193394/126520569-2dd111f9-bc2c-4f28-9ece-f7805f78216a.png)
MAP18:
![image](https://user-images.githubusercontent.com/21193394/126521079-93a9d6b8-b49b-4df0-9734-a58dfe5f92bb.png)
MAP10:
![image](https://user-images.githubusercontent.com/21193394/126521604-598739b9-2213-4c16-a8ec-1884d9181f71.png)

There are literally about **4500** various fixes, I'm totally addicted on pixel-perfection.

Please do not care about Russian translation, this is the thing I will handle.

**Comment by cubebert-github** [comment]
Alright, I've gotten it finished. Let me know if you have any questions or comments about the document.

[gameplay_features.txt](https://github.com/JNechaevsky/russian-doom/files/6862142/gameplay_features.txt)

**Comment by JNechaevsky** [comment]
You have did an incredible job, thank you **very much**!  The only thing is - few items were moved in Gameplay menu and few new ones are added ([screenshot](https://user-images.githubusercontent.com/21193394/126829568-1dd0beb2-4391-4b93-a95f-c35fd828440a.png)). This version is mostly done for release, but still some things have to be done.

Should I make a test build for you? And if so, which version - win-32 or win-64?

**Comment by cubebert-github** [comment]
Hmm, well I could look at the test build to check for new features to document. I'll go ahead and get the Win64 version.

**Comment by JNechaevsky** [comment]
Here it is: [rusdoom-5.0-dev.zip](https://github.com/JNechaevsky/russian-doom/files/6872194/rusdoom-5.0-dev.zip)

There are both Doom and Heretic packed. I haven't composed changelogs yet, but in _very_ short words:
* Performance of drawing huge amount of sprites and visplanes now significantly improved.
* Automap lines redrawing while movement now much smoother.
* Heretic now have a lot of new features and far better mod compatibility (Curse of D'Sparil now working fine, except level names which are stored in unsupported `MAPINFO` lump format), as well as lots of other small improvements. I'm sure you like it. :)

**Comment by cubebert-github** [comment]
Alright, I've updated the document for the new version and wrote down what the new features do. While I was testing the coloring for the HUD elements, I did come up with a possible suggestion; whenever the "Level Select" menu is open and the health, armor, and ammo values are being changed, could the color used for the amount be changed to whatever the coloring setting is? I think that it would make a nice visual touch.

![screenshot-doom-01](https://user-images.githubusercontent.com/24487663/126879353-f0fc6df1-c931-4517-9e1f-af66cc8a552a.png)

[gameplay_features_new.txt](https://github.com/JNechaevsky/russian-doom/files/6872986/gameplay_features_new.txt)

**Comment by JNechaevsky** [comment]
I apologize for my awful sclerosis! First of all, thank you **very much** for such a massive effort with documentation! How do you think, maybe instead of couple of .txt files it is worth to switch to GitHub wiki system? I'm not familiar with it yet, but there have to be a way to keep pages with two languages.

As about coloring, well, why not? In case of status bar is not colored, here's how it will look:
![image](https://user-images.githubusercontent.com/21193394/130120564-7906b2be-ffdf-4ace-9695-30bb1c9541b9.png)

**Comment by cubebert-github** [comment]
Hmm, I never used the wiki system that Github has, but I could see how it would be useful. I'll be focusing on my academics for the rest of the year, so I may not have as much time for rewriting the documentation into the wiki; that being said, I'll still try to look into doing so.

**Comment by JNechaevsky** [comment]
No-no, no need to worry, I've done it already: https://github.com/JNechaevsky/russian-doom/wiki
Some formatting still raw, but general, it was a right idea.

Wishing you all the good about education, nothing can be more important than real life!

**Comment by cubebert-github** [comment]
I've checked the wiki and it looks great! :smiley: There is one thing that I want to request and I hope that I don't sound a bit too pushy: can you credit me for the gameplay feature documentation?

**Comment by JNechaevsky** [comment]
With my pleasure, you have put a lot attention and time to the project, so here you go, just scroll down this page: https://github.com/JNechaevsky/russian-doom/wiki/ReadMe
