### ISSUE TITLE
Typo in rocket pickup message (Easy)

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#260]
Small typo in English pickup message when picking up a single rocket on ITYTD (easy) difficulty.

Wrong text: "Picked up a two rockets"
Correct: "Picked up two rockets"

Dunno about Russian translation, but maybe a similar mistake was made there. Better check it as well.

**Comment by JNechaevsky** [comment]
Hello @NightFright2k19 and thanks for correction! 

Fixed in https://github.com/JNechaevsky/russian-doom/commit/8dab6c73853f55bb10d0687b7ede3fd34e936887. Russian string is fine, since there is absolutely no "a/an" article analogs in Russian language.

**Comment by NightFright2k19** [comment]
Outstanding!
