### ISSUE TITLE
Heretic: "chicken mode" should not have bobbing

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#28]
At the moment it have halfed bobbing while both moving and attacking, which is not correct.
Beak is not a holdable weapon, it's an integral part of the head _(oh God...)_, thus it must remain constant with player's view.

However, absolutely constant beak will not be looking fine either, that's why I applied bobbing.

Maybe it should have just a barely notable vertical only bobbing, need to experiment.

**Comment by AXDOOMER** [comment]
> Maybe it should have just a barely notable vertical only bobbing, need to experiment.

The bobbing could be made to emulate a bird's head movement. The head would stay a the same height, but would move from back to front.

![http://static2.businessinsider.com/~~/f?id=52f3c139eab8ea90356ea82c](http://static2.businessinsider.com/~~/f?id=52f3c139eab8ea90356ea82c)

**Comment by JNechaevsky** [comment]
Yep, I've already done something similar by making vertical bobbing less notable and horizontal barely notable (I don't want to disable it completely - there have to be just a little randomness in pixel movement).
