### ISSUE TITLE
[Bug] Russian-heretic can't find it's WAD data files

### ISSUE THREAD

**Issue by vanfanel** [Russian-Doom/russian-doom#293]
### Russian Doom version

Current GIT code

### What Operating System are you using?

Linux

### What Build variant of Russian Doom are you using?

Other

### If Other OS or Build variant, please describe

Debian

### Relevant hardware info

X86_64/ARM/ARM64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi!

I have just built the latest GIT version, and it seems to look for `heretic-common.wad` in `/usr/local/share/russian-doom/`.

I have `heretic-common.wad` (and all the other included WADs) in ~/heretic/base, so it should work, it was working with previous versions without installing anything to /usr.

@JNechaevsky Can you take a look please?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Try to run russian-heretic without putting wads in `/usr/local/share/russian-doom/`
2. See the error:
```

V_Init: Инициализация видео.
Z_Init: Инициализация распределения памяти.
Распределение памяти: 0x7fab3ca010, выделено 20 Мбайт.
W_Init: Инициализация WAD-файлов.
 добавление: heretic.wad
Внутренний ресурс "/usr/local/share/russian-doom/heretic-common.wad" не найден!
```

### Your configuration

Not relevant for this issue.

### Provide a Log

V_Init: Инициализация видео.
Z_Init: Инициализация распределения памяти.
Распределение памяти: 0x7fab3ca010, выделено 20 Мбайт.
W_Init: Инициализация WAD-файлов.
 добавление: heretic.wad
Внутренний ресурс "/usr/local/share/russian-doom/heretic-common.wad" не найден!

**Comment by Dasperal** [comment]
If you want a portable version you should build with the CMake option `BUILD_PORTABLE` set to `ON`. This is described in the [COMPILING.MD](https://github.com/JNechaevsky/russian-doom/blob/master/COMPILING.md#step-21-building-with-cmake-1)

Though I think that install rules for portable version are incorrect. I'll fix them soon.

**Comment by vanfanel** [comment]
@Dasperal Ah, that did the trick. Thans a lot! Sorry, it seems I hadn't read the build instructions properly.... So really, thanks for taking the time to explain even so.
