### ISSUE TITLE
Heretic: BLOCKMAP limit must be removed

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#30]
The engine is now enforced pretty well to draw some complex geometry without notable errors like wiggle/wobble and slime trails. But yet still, there is one notable weak point - `BLOCKMAP` limit, which prevents loading of really big levels by simple crashing game executable.

I need one more attempt for porting BLOCKMAP limit removing from Crispy:
https://github.com/fabiangreffrath/crispy-doom/commit/423debf9c9ef18dfc794317a6104120adea39ee8

My first attempt was unsuccessful, but I **must** to figure out what should be done to get it working.
Otherwise all limit-removing efforts will be pretty dull.

For proper checking this case I will use NOVA.WAD's map31, adapted for Heretic (without sprites, level/geometry/textures only).

Lock and load.

**Comment by fabiangreffrath** [comment]
You will also have to add code to *rebuild* a BLOCKMAP in memory if it is missing or just too big to make sense.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, I've figured it out! So the problem was in Raven's code p_setup.c:
`count = lumplen / 2;` 
...must be set before:
`blockmaplump = Z_Malloc(sizeof(*blockmaplump) * count, PU_LEVEL, NULL);`

(https://github.com/JNechaevsky/russian-doom/commit/da1ee97b8f252aab3a1b910dcee92bb5b37f10fb#diff-ada8146d60dabd9d292cdc5392b14597R461)

Got Nova's map running:

![](http://screenshot.ru/upload/images/2017/11/30/nova_1c40ac.png)

But it's not done yet by two reasons:

1. I can walk freely in the right huge opened area of the map without crashes, but with some HOM effects.
2. While walking in the left section of the map in highly detailed corridor, it is possible to catch `R_FindPlane: no more visplanes`, which means that MAXVISPLANES (as well as other stuff) also require attention. Increasing static limits to Doom+ level is not good enough here.

![](http://screenshot.ru/upload/images/2017/11/30/nova_29cf2d.png)

**Comment by JNechaevsky** [comment]
Victory! Here is Nova's map full view in all its gorgeous:

![](http://screenshot.ru/upload/images/2017/11/30/nova_113c82.png)

And overdetailed corridor no longer bombs out:

![](http://screenshot.ru/upload/images/2017/11/30/nova_27e74b.png)

But I need to make one more, real stress-test...

**Comment by JNechaevsky** [comment]
Here's my test. Performance suffers a bit because of sparks animation, they are not a static picture sequences and requires some additional CPU's calculations:

- https://youtu.be/wRPxaLPTCEQ

Map view in Doom Builder:
- http://screenshot.ru/upload/images/2017/11/30/dbuildercb7ad.png

Guess now limit-removing part is really done. At least, I have no idea what else should be applied, and this is much, much more than enough for vanilla IWAD. And needles to say that all of this absolutely must be in Crispy Heretic!

Closing this issue because of my aims are reached (for now). It was an awesome ride, though. :)
