### ISSUE TITLE
[Idea] Transparent automap background

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#302]
Looks kinda useful, still feels as original Automap and allow player to see their surroundings.

Quick draft for color darkening:
```
    int y;
    int darkness_factor = 16; // Means 50% of 0...31 COLORMAPS (🤤).

    for (y = 0; y < screenwidth * (SCREENHEIGHT - (32 << hires)); y++)
    {
        I_VideoBuffer[y] = colormaps[darkness_factor * 256 + I_VideoBuffer[y]];
    }
```
![screenshot-doom-01](https://user-images.githubusercontent.com/21193394/149823808-e859966c-729e-4dfd-8367-e9f0b893cc23.png)

Problems are:
1. There is no place in current Automap and Statistics menu.
2. It must be friendly with various screen sizes / weapon placements if status bar is on or off.

**Comment by JNechaevsky** [comment]
Thinking more: having an extra or separate option will bring a lot of headache for existing `automapactive` and/or `automap_overlay`, as well as will be an _"extra feature for one feature of two features"_ 🤯.

Far better approach is to extend `automap_overlay`, i.e. parametrize it with darkness level. This also allows to have as small possible diff as possible and will let avoiding problems with status bar / HUD darkening:
```
    // draw the view directly
    if (gamestate == GS_LEVEL && (!automapactive || automap_overlay) && gametic)
    {
        R_RenderPlayerView (&players[displayplayer]);

+++     if (automapactive)
+++     {
+++         const int screenheight = screenblocks > 10 ? // TODO - make global + Jaguar status bar is 40 pixel tall...
+++                                  SCREENHEIGHT : SCREENHEIGHT - (32 << hires);
+++ 
+++         for (y = 0; y < screenwidth * screenheight ; y++)
+++         {
+++             I_VideoBuffer[y] = colormaps[(automap_overlay - 1) * 256 + I_VideoBuffer[y]];
+++         }
+++     }
```

Probably maximum upper level of `automap_overlay` should be `24`. In higher levels game level simply barely visible and not really looking good because of limited amount of colors. Menu item is still under the question, ideally it should be a slider, but again, need to remove something existing or divide Automap and Statistics to two pages.

@fabiangreffrath, could it be possibly interesting for Crispy?

**Comment by NightFright2k19** [comment]
Will Heretic and Hexen also get this? Looks like current autobuilds don't have it.

**Comment by JNechaevsky** [comment]
Oops, totally forgot about H&H. Sure, I'll do this. I was thinking about making a parchment background translucent, but almost immediately rejected this idea - it looks more like a dirty glass rather than something good looking. Clean dark background must be the only reasonable choice ([screenshot](https://user-images.githubusercontent.com/21193394/151496299-d5adf542-7573-4380-b962-9eaf54c71851.png)).

Will commit changes in the evening, making an menu item will take much more time than darkening code itself.

**Comment by NightFright2k19** [comment]
Outstanding! It's a great feature in Doom and all games should profit from this.
BTW: Looks like Hexen also still doesn't have any means to show level stats (kills, secrets etc). Just in case it was also forgotten.

**Comment by JNechaevsky** [comment]
Yep, indeed. There is simply no "stats" meaning in Hexen, as well as no tally screen to show them. There are some secret areas across the levels, but they are not registered as secrets in both map and engine meaning. 

As about kills, it's pretty much same: no "kills per level" meaning, and in most maps monsters are often gets resurrected from time to time, so "kill on current level" simply will not be informative or useful. 

Few ideas, though:
1. "Total monsters killed" stat. Probably useless and just for fun, since player aren't getting any benefits by killing monsters. No experience/level-up or something. This will probably require some extra job by revisiting `MF_COUNTKILL` set for actors (it isn't removed from game, yay!), otherwise counter can be increased if player destroys some kind of tree. 😱

2. Show discreet "total time: HHHH:MM:SS" string somewhere on the bottom of the second finale screen with _"there are mightier players..."_ text. Due to some bug fixes and improvements, port no longer can be considered as a standard for speedrunning, but even for casual playing this can be useful.

**Comment by NightFright2k19** [comment]
I agree regarding the kills stats. Constant respawns make it kind of impossible to ever reach 100% here (at least permanently), so it's kinda redundant. 

Come to think of it: Are there even secrets in Hexen? Can't tell right now, but they probably won't matter that much. Guess the system clock feature is still the best widget of all, at least in Hexen... :)

**Comment by JNechaevsky** [comment]
All done! 

Yes, there are few hidden areas, not somehow registered as a secrets. For example, here, right in starting area in Death Kings ([screenshot](https://user-images.githubusercontent.com/21193394/151626948-cf2a12e8-308f-427f-b01d-398434307c28.png)). Another example is hidden room with Ruby Planet, again in DK, Blight level. Can't remember any others, but I know for sure there are must be some!

Oh yes, system clock is definitely useful one! AFAIR, it was inspired by Diablo II automap + back in 2018th I was needed some OSD time indication while coding in the morning, right before going to job. And this is despite of I have a separate LED clock near the monitor. 🤓

**Comment by NightFright2k19** [comment]
Works and looks good. Excellent!
