### ISSUE TITLE
[Feature] Специальный lump для перевода уровней в heretic

### ISSUE THREAD

**Issue by Kenon2** [Russian-Doom/russian-doom#310]
### Is your feature request related to a problem? Please describe.

Предлагаю сделать специальный lump как аналог DEHACKED в котором можно было бы переименовывать уровни для Heretic, Назвать к примеру HEHACKED (ну или по другому) и сделать нечно подобное как дехакед:

```
[STRINGS]
HUSTR_E1M1 = E1M1: temple of madness
HUSTR_E1M1_RUS = T1V1: [hfv ,tpevbz
```
В общем как для дума, но чтобы в Heretic работало :)

**Comment by JNechaevsky** [comment]
Помоему, Hehacked порт умеет поддерживать, но у меня нет его примера под рукой, и версия Hehacked для DOS упорно запускаться не хочет. Посмотрю по возможности что можно будет сделать.

**Comment by Kenon2** [comment]
@JNechaevsky порт hhe файлы поддерживает и подключается как
`-deh [файл].hhe -hhever 1.3`
как пример файла тут есть: https://www.doomworld.com/idgames/levels/heretic/g-i/ichor

**Comment by Dasperal** [comment]
Я думаю лучше оставить это на [`UMAPINFO`](https://doomwiki.org/wiki/UMAPINFO) и [`LANGUAGE`](https://zdoom.org/wiki/LANGUAGE), поддержка которых в итоге появится

**Comment by JNechaevsky** [comment]
Помнится, @kmeaw показывал как можно менять текст в dehacked без привязки к какой-либо секции. Что-то типа явного указания `"текст1 текст2"`, но у меня этого примера не осталось. Возможно, это сработает и тут, но врядли - названия уровней на карте к dehacked, похоже, вообще никак не привязаны.

**Comment by Dasperal** [comment]
Вот я и думаю что лучше их привязать уже к `UMAPINFO` и `LANGUAGE`, а не плодить дехакед строки
