### ISSUE TITLE
[BUG] Hexen: Dark Bishop projectiles use wrong palette and tend to crash the game

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#314]
### International Doom version

International Hexen 5.0

### What Operating System are you using?

Windows 10

### What Build variant of International Doom are you using?

x64 (amd64, x86_64, win64)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Whenever Dark Bishops appear in a map, their projectiles can have weird colors, or can outright cause a silent crash. Easily viewable on HEXDD.WAD second internal demo.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Deathkings of the Dark Citadel (HEXDD.WAD)
2. Wait until DEMO2 plays
3. Dark Bishop projectiles will flash in strange colors, or the game will crash.

### Your configuration

[inter-hexen.ini.txt](https://github.com/JNechaevsky/inter-doom/files/8148092/inter-hexen.ini.txt)

**Comment by JNechaevsky** [comment]
Thanks! My bad, an oversight in drawing logic for "Extra translucency" feature. Should be fixed now, just use executable from latest dev. build: https://github.com/JNechaevsky/inter-doom/actions
