### ISSUE TITLE
[Feature] Update Heretic statusbar

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#315]
[Nash has provided newer widescreen versions](https://github.com/nashmuhandes/WidePix) of the Heretic statusbar which looks a bit better than the one which is currently included in this release. The demon horns have a slightly lower profile, obstructing a bit less screen space. 

However, the side parts would have to be extended a bit to cover the entire width of the screen. I have attached an edited version of Nash's BARBACK lump which provides an additional 12px on both sides:
[heretic_widefix.zip](https://github.com/JNechaevsky/inter-doom/files/8197960/heretic_widefix.zip)

Update Mar 8:
Nash will probably make his own extension for the Heretic statusbar after I pointed it out to him. Will keep it under observation and tell you once it's done.

**Comment by Dasperal** [comment]
@JNechaevsky You are currently working on the Heretic, so this may be interesting to you.

**Comment by JNechaevsky** [comment]
If I'm not mistaking, I was asked even before about this. Well, personally I preffer to leave current status bar "as is", it's more conservative and gives more vanilla-feeling to my eyes.

Hovewer! Just not be an arse and conclude everything as "no", there is a good news: first versions of widescreen Inter-Heretic were using some custom, non-IWAD gfx for status bar. Later, the situation was improved and even released version have proper support for custom status bars, both wide and standard. So, if user wants a custom status bar, they are absolutely able to load it with PWAD.
