### ISSUE TITLE
[Feature] Small inconsistency with stats naming

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#317]
Rather an inconsistency than a feature request or bug, but I have to categorize it somehow:
In the optional level stats display, the "Secret" label should be plural ("Secrets"), also to be in sync with the other stats which are plural ("Kills", "Items").

**Comment by JNechaevsky** [comment]
In general I'm agreed, but "Secret" is a vanilla naming:
![screenshot-doom-01](https://user-images.githubusercontent.com/21193394/157305993-9fa02549-d916-4f8a-8cd0-152b2a512edf.png)

Another problem is "Secrect**s**" word is notably longer comparing to "Kills" and "Items", and thus, isn't looking very nice:
![screenshot-doom-02](https://user-images.githubusercontent.com/21193394/157306637-7cba38c1-e8f9-478c-8419-8247e6f40e02.png)

P.S. I'll try respond to other suggestions later, sorry for such delay.

**Comment by NightFright2k19** [comment]
True, haven't thought about that. It would actually rather make sense to make it shorter, like "Secrt", to be more in line with the other word lengths. Then again, this is like splitting hair, so... ;)

Another idea would be to use symbols/icons instead of words, to save more screen space. In the Unity port, they use a skull for kills, a health vial for items and a question mark for secrets.

**Comment by NightFright2k19** [comment]
Come to think of it, Crispy just uses "K/I/S" letters. That's short and gains a bit of screen space. Plus you still know what it means. 

Then again, I don't want to turn this into a feature steal from another project just because I like it more.

**Comment by JNechaevsky** [comment]
Yes, make a huge sense, especially for 4:3 display size:
![изображение](https://user-images.githubusercontent.com/21193394/163662459-3f023148-a1b5-4a95-aa9d-ccf053fefca4.png)

"Skill" string probably should also go optional. It's useful in some cases, but in some cases are not, especially if player always playing in UV skill.
