### ISSUE TITLE
[Bug] Invulnerable enemy (clipping through walls)

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#319]
### International Doom version

International Doom (Continuous Integration #707)

### What Operating System are you using?

Windows 10

### What Build variant of International Doom are you using?

x64 (amd64, x86_64, win64)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While playing "Mutiny" (Doom 2 mod), it happened to me that a Cacodemon became invulnerable and could apparently clip through walls. I doubt this is related to game code.

For reproduction purposes, I have included a savegame and a copy of the actual pwad. The savegame puts you right in front of the buggy monster.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load Doom II with attached PWAD. Make sure you are using the Inter-Doom build described above.
2. The Cacodemon in front of you should be immune to attacks. Projectiles will pass through, it can clip through walls.
3. Wonder what could be going on.

[Mutiny Download](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mutiny)
[Savegame for testing](https://github.com/JNechaevsky/inter-doom/files/8231588/mutiny_bugtest.zip)

**Comment by fabiangreffrath** [comment]
Probably this?
https://doomwiki.org/wiki/Ghost_monster

**Comment by NightFright2k19** [comment]
It's possible. There were two Archviles in the area before that fight and I didn't see what they were doing. The Caco is also transparent, which indicates it might indeed be a ghost version. 

I guess Inter-Doom wouldn't fix this if it wants to remain faithful.

**Comment by fabiangreffrath** [comment]
Yep, then that's it:
https://github.com/JNechaevsky/inter-doom/blob/d28fda9e7f6e29584f78a2af3fd21dba2d87e14e/src/doom/p_enemy.c#L1449

Not a bug, but a faithful preservation of a... bug. 😉

**Comment by NightFright2k19** [comment]
Alright. Almost forgot about that one. Only care about it when it's done intentionally, like in that one level in Icarus, for example.

**Comment by JNechaevsky** [comment]
Oh yes, this is not just a _bug_ it's a real quirk and mapping trick.

@NightFright2k19, sorry, I'm still not responsive last days. Thank you very much for all your suggestions! For now I want to focus exclusively on Hexen, there is still huge potential for aesthetic improvements, as well as lots of remaining unresolved things (those damn unsmoothed sky scrolling and jerky 35 fps polyobjects!). Is it okay if we'll come back to your issues later?
