### ISSUE TITLE
[NOT AN ISSUE] Thanks for inter-heretic!!!

### ISSUE THREAD

**Issue by vanfanel** [Russian-Doom/russian-doom#322]
### Is your feature request related to a problem? Please describe.

Hello @JNechaevsky 

I have just discovered that Russian Doom was renamed to inter-doom. 
I have also discovered that recently movement was fixed and now I find it's PERFECT with uncapped framerate. Thanks for all your dedication and work on this, really. It's my way to play HERETIC and I need it always on my GNU/Linux systems. 

Also, it somewhat saddens me that Russian-Doom was renamed to inter-doom: I love russian culture and history, and I hope recent events have nothing to do with the renaming, because every russian can be proud of it's country's literature, music, technological and social advancements, and a long etcetera.

So, really, thanks for your dedication on this! You keep Heretic alive for me and everyone with a good taste for the finest sourceport!

**Comment by JNechaevsky** [comment]
Hi @vanfanel! Glad you still like it! :)

Let's consider this was done for good reasons. Having a cultural legacy is good. Having nothing more than cultural legacy is not... What is happening today in this country is a crime, dirty play on good past mixed with shitty taste of reign's propaganda.

Anyways, the project is still same, there is no and never will be any hidden banners, texts or hashtags regarding end of February's events.

And by the way, check out how scrolling floors now working in both Heretic and Hexen. Finally it's scrolling smoothly, not by per-texture pixel!

**Comment by vanfanel** [comment]
@JNechaevsky Yep, movement has been perfected in every aspect, incredible work really :)

I will do massive play on the following days, so I will report anything I can find!
