### ISSUE TITLE
[Hexen] F5 key kills the player instead of changing detail

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#368]
### International Doom version

7d719ae

### What Operating System are you using?

Linux

### What Build variant of International Doom are you using?

x64 (x86_64, win64, amd64)

### Please describe your specific OS version

Manjaro Linux (5.15.57-2 kernel)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I know this is a vanilla Hexen function, so I don't think this necessarily counts as a bug to have it happen. However, the binding for changing the graphic detail is set to F5 by default, and it doesn't work, because the suicide option takes priority.

Probably switching the priority around and/or unbinding the graphic detail default key would be a better option.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start up a game of Hexen
2. Press F5
3. Graphic detail doesn't change, and instead the player is asked if they want to die

**Comment by Dasperal** [comment]
Hexen currently don't have graphic detail feature.
In "Customize controls" menu the binding named properly - "Suicide".
In backend it uses `bk_detail` as it previously was the name of hard-coded binding for F5.

**Comment by Dasperal** [comment]
Found out there also was "Detail level" binding in menu also linked to `bk_detail`. Now "Suicide" have its own binding `bk_suicide` and "Detail level" now functions as intended.
