### ISSUE TITLE
[Feature] Bigger 1080p like resolution

### ISSUE THREAD

**Issue by Zaratul555** [Russian-Doom/russian-doom#377]
### Is your feature request related to a problem? Please describe.

Its possible to add less pixelated high resolution like in PBboom\DSDA? With this feature this port would be perfect for me(and others).

**Comment by JNechaevsky** [comment]
Honestly, it will be lovely to have something like "Native pixel size / Crispy 640x480 / Nostalgic 320x200", but there are two problems:
1. It will require serious rewriting of rendering and most drawing functions. Barely it is possible to simply copy-paste some code from Pr+ or DSDA and got fine working result.
2. It will require more extensive knowledge/understanding for video system is working. Far more serious than I have now.

Maybe one day, and I hope that such day will come.  😑
