### ISSUE TITLE
Let Demos Play while in menus

### ISSUE THREAD

**Issue by OpenRift412** [Russian-Doom/russian-doom#387]
I don't know if this is a bug or a feature, but it would be nice to have demos start playing while in the options menu and such, otherwise you're stuck at the title screen hearing the same short MIDI over and over while you change your settings.

It's a small thing, but I think it definitely matters for making a clean-feeling port.

**Comment by JNechaevsky** [comment]
It's a bug, unfortunately. I can reproduce it in Crispy Doom.

@fabiangreffrath, please have a look, if I'm getting things right, this condition is preventing internal demos to be played while menu is opened: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1359-L1365

To fix it, we need to replace last one GS:
```
--- if ((paused & 2 || (!demoplayback && menuactive && !netgame)) && gamestate != GS_LEVEL)
+++ if ((paused & 2 || (!demoplayback && menuactive && !netgame)) && gamestate == GS_INTERMISSION)
```

I've made a brief test with pausing on tally and intermission screen on custom [map06.zip](https://github.com/JNechaevsky/inter-doom/files/9640271/map06.zip), as well as done some `nodraw` long demo runs, and it seems to be working correct. But I'm still not sure it's a correct approach.

**Comment by fabiangreffrath** [comment]
The code in question has been added by @tpoppins, backported from PrBoom+ IIRC. Let's ask him if this is intended behavior.

**Comment by tpoppins** [comment]
I was not aware of this side effect. Not being the code's author I cannot provide a definitive answer to Fabian's question; I am inclined to view this issue as a bug, though.
