### ISSUE TITLE
International Hexen Not Support Deathkings Of The Dark Citadel? 

### ISSUE THREAD

**Issue by MrRumbleRoses** [Russian-Doom/russian-doom#397]
as someone who's trying to get use to how there's 3 ports from the International side of things, i've been trying out the Hexen version for a bit. and i was just wondering, is there no true support for the Hexen expansion or whatever Deathkings Of The Dark Citadel is?

**Comment by Dasperal** [comment]
"Hexen: Deathkings Of The Dark Citadel" is supported and translated.

Use `inter-hexen -iwad HEXEN.WAD -file HEXDD.WAD` command line (`-iwad` option can be skipped if Inter-Hexen can find `HEXEN.WAD` automatically). Or use [directory based autoload](https://github.com/JNechaevsky/inter-doom/pull/391) in version newer than 5.1 (not released yet).

**Comment by MrRumbleRoses** [comment]
> "Hexen: Deathkings Of The Dark Citadel" is supported and translated.
> 
> Use `inter-hexen -iwad HEXEN.WAD -file HEXDD.WAD` command line (`-iwad` option can be skipped if Inter-Hexen can find `HEXEN.WAD` automatically). Or use [directory based autoload](https://github.com/JNechaevsky/inter-doom/pull/391) in version newer than 5.1 (not released yet).

ah ok. thanks for your help :)
