### ISSUE TITLE
[Feature] for HeXen pieces of last weapon in max viewsize 

### ISSUE THREAD

**Issue by WhiteMagicRaven** [Russian-Doom/russian-doom#398]
while you enlarge viewsize of screen to maximum
it would be cool to still possible to see what pieces of weapon you have. (the last weapon number 4)

**Comment by JNechaevsky** [comment]
Sounds good and It is possible, but the huge problem is - original STbar weapon graphics are not transparent and have gray stone background which takes a lot of unnecessary space, especially in original 4:3 screen mode.

Quick not-pixel-perfect example:
![image](https://user-images.githubusercontent.com/21193394/197355341-764820b7-f519-42e2-a72a-701dd4f681b8.png)

**Comment by JNechaevsky** [comment]
Or, I can implement an optional "Assembled Weapon widget" with unscaled graphics, just like I've done for Heretic's ammo widget. Something like this, but with shadow it will be much nicer:
![screenshot-hexen-03](https://user-images.githubusercontent.com/21193394/197355787-799065f7-85ef-4ae1-a389-8b1e2d6437bc.png)

**Comment by WhiteMagicRaven** [comment]
![screenshot-hexen-01](https://user-images.githubusercontent.com/876874/197358293-f3275ad1-41c9-4799-9cc8-6785f9e23da1.jpg)

or something like this i guess

**Comment by Dasperal** [comment]
I think this can be done if we draw sprites, but it requires careful memory management. I can do it when I will be working on the Hexen stuff.

**Comment by JNechaevsky** [comment]
Indeed, indeed. Must be something same to Berserk Pack drawing code in Doom ([link](https://github.com/JNechaevsky/inter-doom/blob/master/src/doom/st_bar.c#L1580-L1605)). I'll prepare drawing code for both "horizontal" and "vertical" drawing, but will not merge it until new menu API to prevent branch desyncs.

**Comment by JNechaevsky** [comment]
I definitely would like to go with both approaches, but vertical seems to be much nicer. I have placed it on top of mana widgets to make pixel size in horizontal row same, that's aesthetical thing.

Horizontal:
![horizontal](https://user-images.githubusercontent.com/21193394/197379232-5d1369ef-7e72-40d9-878f-0422008ae402.png)

Vertical:
![vertical](https://user-images.githubusercontent.com/21193394/197379238-c634b132-c022-415e-8588-be9b74ae4a6e.png)

**Comment by WhiteMagicRaven** [comment]
oh wow, that was great, i suggested this more than ten years ago for various source ports, nobody done it before , thank you very much <3

**Comment by JNechaevsky** [comment]
It feels logical and it's a part of original status bar. Not really needed if playing on "muscule memory", but still, it's probably a part of original game Idea - to collect most powerful weapon. I'll merge this feature today, in the evening. Hexen is still extremly far from new release, but it will be availabe in development auto build.

**Comment by WhiteMagicRaven** [comment]
thanks)
