### ISSUE TITLE
[BUG] Knee-Deep in KDiZD don't work

### ISSUE THREAD

**Issue by rfomin** [Russian-Doom/russian-doom#405]
### International Doom version

International Doom 6.0.1

### What Operating System are you using?

Windows 10

### What Build variant of International Doom are you using?

x64 (x86_64, win64, amd64)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In [Knee-Deep in KDiZD](https://www.doomworld.com/forum/topic/132407-knee-deep-in-kdizd-released-its-kdizd-for-doom2exe/) MAP13 first switch don't work for some reason. It works fine in Choco/Crispy/Woof from my testing. This PWAD has a lot of cool mapping tricks and I think it will be quite popular.

### Steps to reproduce the behaviour.

1. Run PWAD, idclev to MAP13 (technical limitation, there is support for UMAPINFO)
2. Go to the first switch, the door will not open.

**Comment by rfomin** [comment]
It works in Strict Vanilla Mode or with Original Collision Physics (thanks to Dasperal)

**Comment by Dasperal** [comment]
Set "Collision Physics" option to "Original" to fix this issue.

Although, I recommend setting "Strict Vanilla Mode" option to "On" to avoid maximum number of problems because this wad is full of vanilla mapping hacks witch may rely on imperfections of original engine. Or even vanilla bugs that are fixed in this port, so we can't guarantee that this wad will work properly.

**Comment by JNechaevsky** [comment]
Спасибо за наводку. В данном случае коллизия из Хексена не даёт вуду-игроку сработать в спец. секторе и открыть дверь. В Хексене убрана возможность "разгоняться" при беге "в объект" - с одной стороны логично, с другой стороны этот код не идеальный и позволяет получить noclip при упоре в стенку, стоя на какой-нибудь декорации (благо, в Думе и Еретике этого нет).

Отключение не совсем хороший вариант, т.к. не решит сутевую часть проблемы. "Collision physic" это комплексный фикс, который делает сразу несколько исправлений/улучшений, и небезопасные с точки зрения маппинга можно просто убрать. Демки в расчёт не беру, в них плейстейтовые фичи всегда неопционально отключены, как при проигрывании, так и при записи

Список такой:
* Коллизия с акторами как в Хексене.
_:no_entry_sign: Убирает возможность разгона (бега на месте) при упоре в solid-актор. Однозначно убрать._
* Фикс блокмапа. 
_:white_check_mark: Лучше оставить, т.к. многим нравится и стрельба из SSG при нём намного проще. Хотя и не совсем безопасный с точки зрения коллизии с монстрами..._ 
* Застревание монстров в дверных проёмах.
_:white_check_mark: Можно оставить, застревание рандомное и не может использоваться как маппинг-трюк._
* Улучшенная коллизия с диагональными blocking-двусторонними линиями.
_:no_entry_sign: У decino есть уровень, где игроку нужно протриггерить 15 арчвайлов для прыжка и разгона, и в полёте дополнительно разогнаться о blocking-решётку. Сложный трюк, и сам уровень для Boom, но в ванили такое потенциально возможно.  Лучше убрать,._
* Фикс валл-раннинга по S-N стенам. 
_:no_entry_sign: Придётся убрать, т.к. исправление убирает разгон игрока при столкновениями с такими линиями. Может где-то специально использоваться для ускорения бега._
* Фикс пролётов фаерболлов через стены на сложности Nightmare.
_:white_check_mark:  Можно оставить, меньше страданий будет._

Для Еретика, наверное, аналогично, только там ещё и исправляется застревание, вызываемое летающими монстрами.

**Comment by rfomin** [comment]
Я знаю что в Knee-Deep in KDiZD широко используются [micoportlas](https://doomwiki.org/wiki/Mikoportal) в основном для [vanilla conveyor](https://doomwiki.org/wiki/Vanilla_conveyor), они работают корректно в inter-doom? Еще я вижу трюки с прозрачностью и палитрами (графика Options меню немного глючит). С остальным пока не разбирался.

**Comment by JNechaevsky** [comment]
По идее да, должны. Камеры точно работают (челюсть уже с пола пришлось поднять), остальное пока не знаю, нужно садиться и играть после правок коллизии.

С палитрой в меню беда - видимо, вся стандартная графика меню переведена на новую палитру. На вскидку, два возможных решения:
* Полностью отказаться от кастомных шрифтов и использовать только оригинальный ` STCFN`, но меню сильно потеряет в красоте и это не сработает для русского языка.
* Рисовать меню ID с фоновой картинкой и накладывать захардкоженную оригинальную палитру, достаточно только первой. `I_SetPalette` не трудозатратный, но будет морока с перекидыванием палитры туда-сюда.

**Comment by Dasperal** [comment]
Битую палитру меню пока предлагаю отложить до того момента когда я доделаю обновления для rd_menu и rd_text.
На заметку себе: рассмотреть возможность выбора палитры меню.

Тут ещё сильно бы помогло если бы фрейм буфер был трукалорный. Тогда можно было бы текст одной палитрой рисовать, а всё остальное другой.

А в русском языке там ещё и титульник неправильный включается и там тоже палитра не туда.

**Comment by JNechaevsky** [comment]
Я только за, тут если быстро, то только разного рода костыли. В русском никогда ничего правильно в плане модов не будет, его уже выкинуть давно пора - толку всё равно особого нет, только тянет за собой кучу головной боли.

**Comment by JNechaevsky** [comment]
Ещё проблема: у игрока может быть 200 (400 с рюкзаком) ракет. Видимо, пришло с переписыванием статус-бара и корректировкой оригинальной нумерации. Поправлю, это не сложно.

**Comment by JNechaevsky** [comment]
@Dasperal я ещё день-два KDKDIZD погоняю, и предлагаю сделать перевыпуск. По еретику у меня тоже всё, наверное.

**Comment by Dasperal** [comment]
Я почти доделал переход с libpng на miniz, так что лучше подождать пока волью. Получится выкинуть ещё `zlib` и сраный `libgcc_s_dw2-1.dll`, который ломает Make, CLion и другие тулы просто находясь в рабочей директории. Плюс там ещё часть либ от SDL_mixer уберётся так как их заменили на внутреннюю реализацию.

Кстати, почему ченджлоги был разделены на 2 файла?

> В русском никогда ничего правильно в плане модов не будет, его уже выкинуть давно пора - толку всё равно особого нет, только тянет за собой кучу головной боли.

Ты забыл пеку поставить Peka

Ну с доп языками хорошо работать будут только вады которые сделаны с поддержкой этих языков или если вмести с ними грузить доп вады добавляющие эту поддержку, наши или сторонние. Для остальных вадов мы можем только подтюнить выбор ресурсов, не показывать переведённые ассеты, если они были заменены неизвестным вадом.

Ну и в ACS много геморроя, в основном со строчками, которые не влезают в экран поэтому разбиты на несколько. Может если запилить многострочные сообщения получится избавиться от лишних инструментаций и задержек. Это и совместимости с демками поможет, хоть и не везде так как есть ещё коракс и необходимость синхронизировать задержки с его речью и кадрами текстуры. Ну и багфикс серпентов на MAP23 тоже меняет логику.

**Comment by JNechaevsky** [comment]
> Кстати, почему ченджлоги был разделены на 2 файла?

Оптимизация. 😁 Там ченджлог разросся настолько, что в какой-то момент хром начал с ума сходить по загрузке процессора при редактировании. Но мб есть смысл обрано воедино сшить, для удобства.

В KDiZD осталась последная явная проблема - цвета на карте выглядят битыми из за того индексы цветов захардкожены на оригинальную палитру. Фикс почти готов, вечером волью, надо только всё оптимизировать, застатиковать и обязательно законстантить. 🚑

И вроде всё запланированное готово. Была ещё идея опционально раскрасить вспышки получения артефактов в разные цвета, но HSV не даёт симпатичного результата, а писать таблицы под это дело слишком муторно.

**Comment by rfomin** [comment]
> В KDiZD осталась последная явная проблема - цвета на карте выглядят битыми из за того индексы цветов захардкожены на оригинальную палитру.

Кстати в KDiKDi_B.wad есть `OPTIONS` ламп, в котором заданы цвета карты и настройки совместимости. Поддерживается в MBF21 и оригинальном MBF/Woof, еще в Eternity Engine.

**Comment by Dasperal** [comment]
> Там ченджлог разросся настолько, что в какой-то момент хром начал с ума сходить по загрузке процессора при редактировании. Но мб есть смысл обрано воедино сшить, для удобства.

Не, склеивать не надо. Я у меня тоже большой ченджлог при некоторых операциях подвисал (у меня репозиторий вики склонирован и я его в том же CLion редактирую, а не в браузере). Я предлагаю их ротировать. В маленьком будут текущий релиз и его поинт релизы для каждой игры и будущие версии для каждой игры. А после релиза новой версии старую будем скидывать в большой ченджлог. Я когда-нибудь напишу скрипт, который будет сам это делать при релизе новой версии.

**Comment by JNechaevsky** [comment]
> Я предлагаю их ротировать. В маленьком будут текущий релиз и его поинт релизы для каждой игры и будущие версии для каждой игры. 

Хорошая идея, я только за. 👍

**Comment by JNechaevsky** [comment]
> Кстати в KDiKDi_B.wad есть OPTIONS ламп, в котором заданы цвета карты и настройки совместимости. Поддерживается в MBF21 и оригинальном MBF/Woof, еще в Eternity Engine.

Полезная штука, но лучше отложить до лучших времён и поддержки Boom*.

P.S. Видео decino с разгоном о blocking-линию: https://youtu.be/64pyo_WJs-8?t=1858 (после прыжка от 15и арчвайлов).

**Comment by JNechaevsky** [comment]
Ещё небольшая идея - раскрашивать кровь не через таблицу `RED2BLUE` / `RED2GREEN`, а через HSV. Сейчас с палитрой KDiZD "табличная" цветная кровь выглядит так:
<details>

![image](https://user-images.githubusercontent.com/21193394/202029944-6d7bd438-9f53-41a9-b70e-57ce81b5578f.png)

</details>

С HSV выглядит как нужно:

<details>

![image](https://user-images.githubusercontent.com/21193394/202030061-ef63a47b-0a37-4509-b88e-f63c3188c664.png)

</details>

Но это актуально только для крови. Если раздавленные трупы раскрашивать через HSV, они станут одноцветными и пропадёт симпатичный эффект, т.е.:

"Табличный" труп:
<details>

![image](https://user-images.githubusercontent.com/21193394/202030568-87c06405-c562-47a1-8879-fba94db10d97.png)

</details>

HSV труп:

<details>

![image](https://user-images.githubusercontent.com/21193394/202030649-d261b78c-89a9-4292-b74b-8dd9abe10dbe.png)

</details>

**Comment by JNechaevsky** [comment]
@rfomin мне нужно бежать, но думаю, есть смысл вынести проблему с цветной кровью в отдельный тикет, т.к. наверняка актуально для Woof и Crispy. На вскидку, вот этот блок: https://github.com/JNechaevsky/inter-doom/blob/master/src/doom/r_things.c#L872 должен стать вот таким:

```
    // [crispy] colored blood
    if (colored_blood && !vanillaparm && thing->target)
    {
        if (thing->target->type == MT_HEAD)
        {
            if (thing->type == MT_BLOOD)
            {
                vis->translation = cr[CR_BLUE2];  // HSV
            }
            else
            if (thing->state - states == S_GIBS)
            {
                vis->translation = cr[CR_RED2BLUE];  // Tabified
            }
        }
        else
        if (thing->target->type == MT_BRUISER
        ||  thing->target->type == MT_KNIGHT)
        {
            if (thing->type == MT_BLOOD)
            {
                vis->translation = cr[CR_GREEN];  // HSV
            }
            else
            if (thing->state - states == S_GIBS)
            {
                vis->translation = cr[CR_RED2GREEN];  // Tablified
            }
        }
    }
```
