### ISSUE TITLE
[BUG] International DOOM 6.2 Cacodemon and Baron of Hell bleeding with wrong colors

### ISSUE THREAD

**Issue by Meerschweinmann** [Russian-Doom/russian-doom#424]
### International Doom version

International DOOM 6.2

### What Operating System are you using?

Windows 11

### What Build variant of International Doom are you using?

x64 (x86_64, win64, amd64)

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

AMD Ryzen 6800HS with integrated Graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hello.

I am sorry to say, but Colored Blood in your 6.2 release seems wrong. Cacodemons bleed green and Barons of Hell bleed grey.

When i download the compiled "Artifact" under "Actions" from the "Draw sliding hint on fps cap, not vsync #1704" issue, everything is fine.

Greetings
Meerschweinmann

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

Unzipped the Inter-DOOM Zip-file in a new folder and put DOOM.WAD in. So inter-doom.ini was created new and unchanged for testing.

**Comment by Dasperal** [comment]
It is because 8454ac4c511e06b23e29c105e84055eb360cc5fc added `CR_BLACK` translation to enum but didn't add table for it to `cr` array. This caused shift of the indexes and wrong translation tables were used for the colored blood and other things that use predefined translation tables.

**Comment by JNechaevsky** [comment]
🤤 There is always something. Thanks for pointing out and fix!

@Dasperal making a re-release is a bit long, probably worth to just replace an executables in released versions and make a simple post about it?

**Comment by Dasperal** [comment]
@JNechaevsky In this case replace executables for all 3 games. I'll patch the Arch Linux packages.

**Comment by JNechaevsky** [comment]
Got it, thanks. From another hand, everything is done already for launching a proper re-release. Probably it is too late to update executables backdate.

**Comment by Meerschweinmann** [comment]
By the way, nice to see that you could fix the bug so fast. Thank you.

**Comment by JNechaevsky** [comment]
Thanks for pointing out and fix! It's a bad tradition already, when I'm making a big release with my small oversight left in the code. 🤯

**Comment by Meerschweinmann** [comment]
Mistakes can happen, we all are humans, not machines. Inter-DOOM 6.2.x is a strong release :)
