### ISSUE TITLE
[BUG] No vertical look on gamepad in Heretic

### ISSUE THREAD

**Issue by PatrykIBM** [Russian-Doom/russian-doom#427]
### International Doom version

International Heretic 6.1.1

### What Operating System are you using?

Windows 10

### What Build variant of International Doom are you using?

x64 (x86_64, win64, amd64)

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

CPU i5-7300U, 32gig ram, IntelHD graphics 620, lenovo l570

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

No vertical look on xbox controller with right stick.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Connect controller
2. Run game then ofc restart becasue triggers wont work on clean instalation with first run
3. set mouse look to on
4. right stick do not control vertical camera movement (altough in doom and hexen it works ok)

### Your configuration

config_version = 3

[General]
english_language = 1
autoload_root = ""
use_mouse = 1
use_controller = 1
snd_musicdevice = 3
snd_sfxdevice = 3
chatmacro0 = "(null)"
chatmacro1 = "(null)"
chatmacro2 = "(null)"
chatmacro3 = "(null)"
chatmacro4 = "(null)"
chatmacro5 = "(null)"
chatmacro6 = "(null)"
chatmacro7 = "(null)"
chatmacro8 = "(null)"
chatmacro9 = "(null)"
fullscreen = 1
rendering_resolution = 1
aspect_ratio = 2
opengles_renderer = 0
video_display = 0
vga_porch_flash = 0
startup_delay = 35
resize_delay = 70
window_title_short = 1
window_ontop = 0
window_width = 852
window_height = 480
window_border = 1
fullscreen_width = 0
fullscreen_height = 0
grabmouse = 1
mouse_acceleration = 2.000000
mouse_threshold = 10
snd_samplerate = 44100
snd_cachesize = 67108864
snd_maxslicetime_ms = 28
snd_musiccmd = ""
snd_dmxoption = "-opl3"
opl_io_port = 0x388
show_endoom = 0
vanilla_keyboard_mapping = 1
video_driver = ""
window_position_x = 693
window_position_y = 390
player_name = "Lenovo"
libsamplerate_scale = 0.650000
fluidsynth_sf_path = ""
timidity_cfg_path = ""
gus_patch_path = ""
gus_ram_kb = 1024
vsync = 1
preserve_window_aspect_ratio = 1
uncapped_fps = 1
show_fps = 0
smoothing = 0
max_fps = 200
smoothlight = 1
png_screenshots = 1
flashing_hom = 0
screenblocks = 10
extra_level_brightness = 0
brightness = 1.000000
usegamma = 7
color_saturation = 1.000000
show_palette = 1
r_color_factor = 1.000000
g_color_factor = 1.000000
b_color_factor = 1.000000
local_time = 0
show_messages = 1
messages_alignment = 0
messages_timeout = 4
message_fade = 1
message_color_pickup = 0
message_color_secret = 15
message_color_system = 0
message_color_chat = 6
draw_shadowed_text = 1
automap_rotate = 0
automap_overlay = 0
automap_overlay_bg = 0
automap_follow = 1
automap_grid = 0
automap_grid_size = 128
automap_mark_color = 6
stats_placement = 0
stats_kis = 1
stats_skill = 0
stats_level_time = 1
stats_total_time = 0
stats_coords = 0
stats_level_name = 0
stats_color = 1
sfx_volume = 10
music_volume = 10
snd_channels = 8
snd_monomode = 0
snd_pitchshift = 1
mute_inactive_window = 0
always_run = 1
mlook = 1
mouse_sensitivity = 5
novert = 1
mouse_y_invert = 0
artiskip = 0
strict_mode = 0
brightmaps = 1
fake_contrast = 0
translucency = 1
colored_blood = 1
swirling_liquids = 1
invul_sky = 1
linear_sky = 1
randomly_flipcorpses = 1
flip_weapons = 0
negative_health = 0
sbar_colored = 0
sbar_colored_gem = 0
ammo_widget = 0
ammo_widget_colored = 1
z_axis_sfx = 0
noise_alert_sfx = 0
secret_notification = 1
show_all_artifacts = 0
show_artifacts_timer = 0
improved_collision = 1
torque = 1
floating_powerups = 1
weapon_bobbing = 1
crosshair_draw = 0
crosshair_shape = 0
crosshair_type = 1
crosshair_scale = 0
crosshair_opacity = 8
default_skill = 2
fix_map_errors = 1
flip_levels = 0
pistol_start = 0
breathing = 0
demotimer = 0
demotimerdir = 0
demobar = 0
no_internal_demos = 0

[Keybinds]
Forward = "k_W", "m_MIDDLE"
Backward = "k_S"
Turn_left = "k_LEFT"
Turn_right = "k_RIGHT"
Strafe_left = "k_A"
Strafe_right = "k_D"
Fly_up = "k_PAGE_UP"
Fly_down = "k_INSERT"
Fly_stop = "k_HOME"
Speed = "k_LSHIFT", "k_RSHIFT", "c_LEFT_TRIGGER"
Strafe = "k_LALT", "k_RALT", "m_RIGHT"
Toggle_autorun = "k_CAPSLOCK"
Use = "k_E", "k_SPACE", "c_A"
Fire = "k_LCTRL", "k_RCTRL", "m_LEFT", "c_RIGHT_TRIGGER"
Weapon_1 = "k_1"
Weapon_2 = "k_2", "c_DPAD_UP"
Weapon_3 = "k_3", "c_DPAD_DOWN"
Weapon_4 = "k_4"
Weapon_5 = "k_5"
Weapon_6 = "k_6"
Weapon_7 = "k_7"
Weapon_prev = "m_SCROLL_UP", "c_LEFT_SHOULDER"
Weapon_next = "m_SCROLL_DOWN", "c_RIGHT_SHOULDER"
Look_up = "k_PAGE_DN"
Look_down = "k_DELETE"
Look_center = "k_END", "c_RIGHT_STICK"
Toggle_mlook = "k_`"
Inv_left = "k_[", "c_DPAD_LEFT"
Inv_right = "k_]", "c_DPAD_RIGHT"
Inv_use_artifact = "k_ENTER", "c_Y"
Arti_tome = "k_BACKSPACE"
Screen_inc = "k_="
Screen_dec = "k_-"
Help = "k_F1"
Msave = "k_F2"
Mload = "k_F3"
Mvolume = "k_F4"
Qsave = "k_F6"
End_game = "k_F7"
Qload = "k_F9"
Quit = "k_F10"
Gamma = "k_F11"
Screenshot = "k_SYS_RQ"
Pause = "k_PAUSE"
Finish_demo = "k_Q"
Toggle_crosshair = "k_X"
Messages = "k_F8"
Detail = "k_F5"
Spy = "k_F12"
Multi_msg = "k_T"
Multi_msg_player_0 = "k_P"
Multi_msg_player_1 = "k_Y"
Multi_msg_player_2 = "k_K"
Multi_msg_player_3 = "k_B"
Map_toggle = "k_TAB", "c_BACK"
Map_zoom_in = "k_=", "c_RIGHT_SHOULDER"
Map_zoom_out = "k_-", "c_LEFT_SHOULDER"
Map_zoom_max = "k_0"
Map_follow = "k_F"
Map_overlay = "k_O"
Map_rotate = "k_R"
Map_grid = "k_G"
Map_mark = "k_M"
Map_clearmark = "k_C"

[Controller_0300b9786f0e00001413000000007200]
LX_Binding = STRAFE
LX_Invert = 0
LX_DeadZone = 16
LX_Sensitivity = 8
LY_Binding = MOVE
LY_Invert = 1
LY_DeadZone = 16
LY_Sensitivity = 8
RX_Binding = TURN
RX_Invert = 0
RX_DeadZone = 16
RX_Sensitivity = 8
RY_Binding = VLOOK
RY_Invert = 1
RY_DeadZone = 16
RY_Sensitivity = 6
LT_Binding = NONE
LT_Invert = 0
LT_DeadZone = 1
LT_Sensitivity = 8
RT_Binding = NONE
RT_Invert = 0
RT_DeadZone = 1
RT_Sensitivity = 8

**Comment by Dasperal** [comment]
It was broken in 09159cd326c9d40fd2ab7f4e105afdc22018e11a. Not sure, is it just a copy-paste error or related to demo desyncs.
