### ISSUE TITLE
Crushed player is able to see level "out of bounds" beneath closed door

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#45]
This is a vanilla behavior, need to fix it somehow. Reproducable in any map, here's an example in Doom 2's Underhalls, after opening/closing automap:

![](http://screenshot.ru/upload/images/2018/01/18/0f61f128ef62dc6de8feb.png)

**Comment by JNechaevsky** [comment]
Hm. It is possible to make some manipulations in `P_CalcHeight` like:
```
    if (player->playerstate != PST_LIVE && player->viewz < player->mo->floorz)
        player->viewz = player->mo->floorz;
```
But it is not correct, because this way is almost nothing is rendered at all, except one horizontal line in the center of the screen. 

Making `player->mo->floorz+1` is also not correct, because this way only floor is rendered as one huge pixel, while ceiling is not rendered at all ([screenshot](http://screenshot.ru/upload/images/2018/01/18/df392f2c1bc1d39fc0520.png)).

Is there any other ways without making any changes in the rendered? Probably not.

**Comment by JNechaevsky** [comment]
Actually, first approach is not as bad as it looks, but the problem is - "out of maps bounds" is't rendered as black color in my project. Probably it should be done first.

**Comment by JNechaevsky** [comment]
Almost! 

Looking pretty well, and here's that 1px line:
```
    if (player->playerstate != PST_LIVE && player->viewz < player->mo->floorz)
        player->viewz = player->mo->floorz;
```
![](http://screenshot.ru/upload/images/2018/01/18/eebd5cea211b649674496.png)

Looking bad:
```
    if (player->playerstate != PST_LIVE && player->viewz < player->mo->floorz)
        player->viewz = player->mo->floorz + 1;
```
![](http://screenshot.ru/upload/images/2018/01/18/23efce.png)

**Comment by JNechaevsky** [comment]
There must be a way to reduce sector's brightness to `0` when door is closed...

**Comment by JNechaevsky** [comment]
Done. Frankly, this approach is not very smart - I'd better use sector brightness instead of wall lights, but can't handle "remembering" of initial brightness in `r_bsp.c` after reopening/reclosing door. 

At least it working. :confused: 

@fabiangreffrath, may I suggest this idea/bug for Crispy?

**Comment by fabiangreffrath** [comment]
> may I suggest this idea/bug for Crispy?

You may suggest anything you like! If we find it unsuitable, we can still close the requests after discussion. :+1:

**Comment by JNechaevsky** [comment]
@fabiangreffrath, excellent, thanks! I will not able to provide technically perfect solution, but the whole topic is very interesting to discuss and investigate. Will post suggestion shortly.
