### ISSUE TITLE
Inter-Heretic with heretic neural texture pack

### ISSUE THREAD

**Issue by 55TeMeR55** [Russian-Doom/russian-doom#450]
Хочу спросить удивился когда увидел как может выглядит игра в вокселях, пробовал бросить в папку с игрой, не получил должного эффекта, предвидится что то типа того для вашей сборки?
https://www.moddb.com/addons/heretic-neural-texture-pack

![heretic_neuro_textures_17](https://github.com/Russian-Doom/russian-doom/assets/48158561/86e40673-eaac-4900-9def-fe8d0f553567)

**Comment by Dasperal** [comment]
Во-первых, Neural Texture Pack это не воксели, а HD текстуры.
Во-вторых, Russian Doom это не сборка, а порт, причём из группы консервативных. Тут нет хардварного рендера (и не будет), только софтварный. Я не знаю, насколько сложно в софтварный рендер добавить поддержку HD текстур и целенаправленно в этом разбираться я не хочу.

Так что вероятность появления поддержки HD текстур крайне мала.
