### ISSUE TITLE
[Idea] Make some additional back screens for Wolf3D levels

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#54]
I.e. for it's intermission text. For example, it could be blue for entering Wolfenstein and red for entering Grosse. Wolfenstein 3D itself have a necessary background, but there must be done some work on the colors (contrast, gamma-correction, etc.) for proper according Doom palette and textures (which are more darken than in Wolf3D). Could be something like this:

![](http://screenshot.ru/upload/images/2018/02/23/Untitled-1b0189.png)

Not sure I like it much, though...

**Comment by JNechaevsky** [comment]
Done with graphics. I think it's much better now, probably I will implement this idea.

![](http://screenshot.ru/upload/images/2018/02/23/ok_1cea29.png)
![](http://screenshot.ru/upload/images/2018/02/23/ok_22c699.png)

**Comment by AXDOOMER** [comment]
Nice
