### ISSUE TITLE
changing music volume during pause unmutes music again

### ISSUE THREAD

**Issue by fabiangreffrath** [Russian-Doom/russian-doom#57]
Hey, finally I can contribute back to your port with a bug report! If you pause the game, the music is mute, but if you go to the menu and change the music volume while the game is paused, it will become hearable again.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, :fearful:, verified, confirmed. Thank you!

Look likes I will need to take care about `paused` in my hack, I can handle this. Ah, btw, this morning I was having a crazy idea regarding this case in libopl (just for fun, **not** a suggestion!): when volume is `0` maybe it is possible to "flow" music into something like `dev/null`. 

Pros: it will act close to vanilla, where music was not paused in zero volume.
Cons: `dev/null`? Whaa--?!

**Comment by JNechaevsky** [comment]
Errrmm-hhhhm. Seems to be working.
```
    if (musicVolume == 0)
    {
        I_PauseSong();
        mus_paused = true;
    }
--- else
+++ else if (musicVolume > 0 && !paused)
    {
        I_ResumeSong();
        mus_paused = false;
    }
```

**Comment by fabiangreffrath** [comment]
> when volume is 0 maybe it is possible to "flow" music into something like dev/null.

:scream: `/dev/null` sounds scary. ;)

I'd rather follow @nukeyt and your advise and pause the music if the volume has been set to zero (will have to take care of the music being paused because of an actual pause as well). What I don't like about this approach is its reversed logic: If the music is paused, its volume should be zero, not the other way round:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/i_sdlmusic.c#L1012

**Comment by JNechaevsky** [comment]
I see. But almost everything there seems to be declared as `static`, not sure I can do anything better than I have done. Isn't it a perfect time for me to say: "Now it's your turn"? :Ъ
