### ISSUE TITLE
Corpses are not falling from the ledges sometimes

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#59]
I was thinking that it's a Torque related, but in fact it's not. Here's what is happening:

- https://www.youtube.com/watch?v=WyRUU0-vYLE

Caco's corpses are falling only after saving and reloading the game. If my memory is not tricking me, it is a vanilla bug, and even Torque can't solve it. In WinMBF situation even worse: corpses are not falling in cases like this.

Quick working and probably very unsafe approach:
```
void A_Fall (mobj_t *actor)
{
    // actor is on ground, it can be walked over
    actor->flags &= ~MF_SOLID;
+++ // [JN] Prevent corpses being bumped into walls and unable to fall:
+++ actor->flags |= MF_NOCLIP;

    // So change this if corpse objects
    // are meant to be obstacles.
}
```

Smarter approach is to make a `MF_NOCLIP` flag only active while Torque's `MIF_FALLING` is set...

Much deeper investigation needed.

**Comment by JNechaevsky** [comment]
No, setting a `MF_NOCLIP` is bad idea, this way corpses can clip into walls... As I suspected, this is a vanilla behavior. It is happening same way in Crispy Doom, but not in Doom Retro and WinMBF. 

- Crispy Doom: https://youtu.be/NY9ZE-jX4NQ
- Doom Retro: https://youtu.be/7q0H99OByI0

Ideally, this corpse should fall right after it becomes a corpse, i.e. not after game is being reloaded. :skull:

@fabiangreffrath, @bradharding, colleagues, maybe you have some thoughts about this case?

**Comment by fabiangreffrath** [comment]
This is really a strange phenomenon! I wonder if some mobj flags are different for the Caco before and after restoring the savegame or if the mobj thinker function works on it again after it has abandoned it before (because it was dead and has reached the floor already)?

**Comment by JNechaevsky** [comment]
Sounds like a perfect starting point! I will need to dig into **p_saveg.c**, have a feeling that the answer is hidden in `P_UnArchiveThinkers`, which is calling `P_SetThingPosition`.

**Comment by JNechaevsky** [comment]
Played around with different parts of code. Not much luck, however, commenting out this like making a sense, dead Caco is not falling this way:

```
	    P_SetThingPosition (mobj);
	    mobj->info = &mobjinfo[mobj->type];
	    // mobj->floorz = mobj->subsector->sector->floorheight;    // <--- this one
	    mobj->ceilingz = mobj->subsector->sector->ceilingheight;
	    mobj->thinker.function.acp1 = (actionf_p1)P_MobjThinker;
	    P_AddThinker (&mobj->thinker);
```

But it's totally opposite way, I need it to fall right after it's being killed. ><

**Comment by JNechaevsky** [comment]
**p_mobj.c** @@ `P_MobjThinker`, worked for me:

```
    // killough 9/12/98: objects fall off ledges if they are hanging off
    // slightly push off of ledge if hanging more than halfway off
    if (singleplayer)
    {
        if (mobj->z > mobj->dropoffz        // Only objects contacting dropoff
        && !(mobj->flags & MF_NOGRAVITY)    // Only objects which fall
        && (mobj->flags & MF_CORPSE))       // [JN] And only for corpses
        {
            P_ApplyTorque(mobj);            // Apply torque
+++         mobj->floorz = mobj->subsector->sector->floorheight;
        }
        else
        {
            mobj->intflags &= ~MIF_FALLING, mobj->gear = 0;  // Reset torque
        }
    }
```

But it's still not correct, there must be something not in Torque-related code.

**Comment by JNechaevsky** [comment]
Non-Torque related approach, same `P_MobjThinker`:

```
    // killough 9/12/98: objects fall off ledges if they are hanging off
    // slightly push off of ledge if hanging more than halfway off
    if (singleplayer)
    {
        if (mobj->z > mobj->dropoffz        // Only objects contacting dropoff
        && !(mobj->flags & MF_NOGRAVITY)    // Only objects which fall
        && (mobj->flags & MF_CORPSE))       // [JN] And only for corpses
            P_ApplyTorque(mobj);            // Apply torque
        else
            mobj->intflags &= ~MIF_FALLING, mobj->gear = 0;  // Reset torque
    }

+++ // [JN] AHEM! It should be applied ONLY to the corpses, otherwise some bad thing starts to happen :O
+++ mobj->floorz = mobj->subsector->sector->floorheight;

    // cycle through states,
    // calling action functions at transitions
    if (mobj->tics != -1)
    {
	mobj->tics--;
		
	// you can cycle through multiple states in a tic
	if (!mobj->tics)
	    if (!P_SetMobjState (mobj, mobj->state->nextstate) )
		return;		// freed itself
    }
```

It's working, but now there is major question of this phenomenon: is falling monsters _really_ a bug? Or non-falling? Having a look into WinMBF, I haven't noticed anything like `mobj->floorz = mobj->subsector->sector->floorheight;` in `P_UnArchiveThinkers`: https://github.com/fabiangreffrath/WinMBF/blob/master/Source/p_saveg.c#L384

Not sure I can understand why id added `mobj->floorz` into `P_UnArchiveThinkers` - even without `floorz`, if I kill Caco and save/load game while it's still falling, it will fall to the ground normally. Was it done just for sure then?

I need to experiment more deeper and see, is my addition looking properly in the game. If so, I'll commit it. If not... Well.

**Fabian**, I'm afraid I can't suggest it for Crispy in any way. Moving a corpses must be totally unsafe for compatibility.

**Comment by fabiangreffrath** [comment]
No, I do not consider fixing this for Crispy Doom -- just think of Archvilles resurrecting dead monsters. But it will be interesting to know where this originates from anyway.

**Comment by JNechaevsky** [comment]
Yeah, exactly! Another important thing here: the corpse itself is definitely not a _safe-to-operate_ object, another possible case is turning sliding corpse into pool of blood, which is meaning totally different map object. You are probably remember, I have left some thoughts while Torque implementation in https://github.com/JNechaevsky/russian-doom/issues/11#issuecomment-353996656.

Now about `mobj->floorz = mobj->subsector->sector->floorheight;`. Still not sure that my theory is correct, but I'm thinking it was done just as "fail safe" condition, or simply just for sure. 

Must admit, that I was incorrect about WinMBF, actually we have a _Bingo!_ here (`P_UnArchiveThinkers` again):

```
      // killough 2/28/98:
      // Fix for falling down into a wall after savegame loaded:
      //      mobj->floorz = mobj->subsector->sector->floorheight;
      //      mobj->ceilingz = mobj->subsector->sector->ceilingheight;
```

As about my approach, I think I preffer to stuck with:
```
        if (mobj->z > mobj->dropoffz        // Only objects contacting dropoff
        && !(mobj->flags & MF_NOGRAVITY)    // Only objects which fall
        && (mobj->flags & MF_CORPSE))       // [JN] And only for corpses
        {
+++         mobj->floorz = mobj->subsector->sector->floorheight;

            P_ApplyTorque(mobj);            // Apply torque
        }
```

Because I want corpses being fall, not stuck in a half way and bumped into wall. The only thing I left to do: test it deeper to make sure it's looking good. Sadly, this case is not a common one and require different places and situations, which are sometimes not easy to catch.

**Comment by JNechaevsky** [comment]
My approach is working fine but there is one bad thing: on diagonal segments it is possible to note small vertical shaking while the corpse is ready to fall, probably because of how Torque is working by circular checking for `floorz` position: "Now I found, now I don't".

Fair enough to don't use it, and I need a different approach. However, enforcing should be done with very strict conditions (only for corpses without any movement momentums) and should be called right after Torque has been done, i.e. for 100% still corpse. Got a working solution, but to need to test it again in the evening.

**Comment by JNechaevsky** [comment]
```
    // cycle through states,
    // calling action functions at transitions
    if (mobj->tics != -1)
    {
	mobj->tics--;
		
	// you can cycle through multiple states in a tic
	if (!mobj->tics)
	    if (!P_SetMobjState (mobj, mobj->state->nextstate) )
		return;		// freed itself
    }
    else
    {
+++	// [JN] Also enforce Z-positioning. Fixes vanilla bug when monster's
+++	// corpses weren't falling from the edges in some instances.
+++	if (mobj->z > mobj->dropoffz              // Only objects contacting dropoff
+++	&& !(mobj->flags & MF_NOGRAVITY)          // Only objects which fall
+++	&& (mobj->flags & MF_CORPSE)              // Only for corpses
+++	&& (mobj->gear == 0)                      // Only if Torque has beed stopped
+++	&&  mobj->momx == 0 && mobj->momy == 0 )  // And only if there is no momentum
+++	{
+++	    mobj->floorz = mobj->subsector->sector->floorheight;
+++	}
        
	// check for nightmare respawn
	if (! (mobj->flags & MF_COUNTKILL) )
	    return;
```

**Comment by fabiangreffrath** [comment]
I still don't understand it...
`P_ZMovement()` is only called from `P_MobjThinker()` if `(mobj->z != mobj->floorz) || mobj->momz )`, but `mobj->momz` should be zero anyway for a dead monster and `mobj->floorz` should have been set to `mobj->subsector->sector->floorheight` already when the monster hit the floor, so what makes the difference?

**Comment by fabiangreffrath** [comment]
Do you have a test map for this?

**Comment by JNechaevsky** [comment]
> Do you have a test map for this?

Nope, it's not needed. I'm testing in a very specific place with diagonal lines at MAP17. I know few more suitable places, but they are interesting primary and only for Torque.

Instead of thousand thoughts:

**1.** Uncorrected (vanilla) behavior: https://youtu.be/00cxK75QaNg
___

**2.** Incorrect approach by operating the corpse while Torque (convulsions): https://youtu.be/2PmkVYpS4MI

```
        if (mobj->z > mobj->dropoffz        // Only objects contacting dropoff
        && !(mobj->flags & MF_NOGRAVITY)    // Only objects which fall
        && (mobj->flags & MF_CORPSE))       // [JN] And only for corpses
        {
+++         mobj->floorz = mobj->subsector->sector->floorheight;

            P_ApplyTorque(mobj);            // Apply torque
        }
```
___

**3.** Preferred approach: https://youtu.be/aMiXv33I4Wk

```
	// you can cycle through multiple states in a tic
	if (!mobj->tics)
	    if (!P_SetMobjState (mobj, mobj->state->nextstate) )
		return;		// freed itself
    }
    else
    {
+++ // [JN] Also enforce Z-positioning. Fixes vanilla bug when monster's
+++ // corpses weren't falling from the edges until the game was reloaded.
+++ if (mobj->z > mobj->dropoffz              // Only objects contacting dropoff
+++ && !(mobj->flags & MF_NOGRAVITY)          // Only objects which fall
+++ && (mobj->flags & MF_CORPSE)              // Only for corpses
+++ && (mobj->gear == 0)                      // Only if Torque has beed stopped
+++ &&  mobj->momx == 0 && mobj->momy == 0 )  // And only if there is no momentum
+++ {
+++     mobj->floorz = mobj->subsector->sector->floorheight;
+++ }
        
	// check for nightmare respawn
	if (! (mobj->flags & MF_COUNTKILL) )
	    return;
```

**Comment by fabiangreffrath** [comment]
My personal favourite solution would be the Killough way and just leave the `floorz` value intact when restoring a savegame. I still have no idea why this is mangled in the first place -- I mean, the value is explicitly saved in the savegame, so why override it again at all?

**Comment by JNechaevsky** [comment]
No-o, I have commented out values in saved games already: https://github.com/JNechaevsky/russian-doom/commit/c0fe6aa13b56144cf6822b65cbbe9740f045f2a8.

So all I wish to have now - to "push down" some corpses thats can be actually pushed down. This should be a good addition to the Torque, despite of it is not working correct with Torque directly (sounds awesome, isn't it? `/o\`).

**Comment by fabiangreffrath** [comment]
I think I've got it: If you kill a Caco and it falls to the ground, it may happen that it sticks to the edge of a sector and cannot fall further down, because it is "too fat" (i.e. its radius touches the sector's edges). Now when you save the game, the content of the Caco's `mobj_t` struct are written to the save file. This struct has a `subsector` field which holds a pointer to the subsector that the map object currently resides in. However, when restoring the savegame, this pointer is invalidated and the game engine has no idea anymore in which subsector the map object resides. Thus, it has to reconstruct this information from the objet's coordinate.

Now comes the critical point: When checking which subsector the map object resides in, the engine uses the object's center coordinates. When the Caco was stuck to the edge of the higher sector A because of its radius preventing it from falling further down, its map center was already in the other sector B down deeper. So, before saving the game, the Caco was stuck to the edge of sector A and after restoring the game, the Caco was assigned to the lower sector B.

And now, the engine updates the map object's floor and ceiling values with the values of sector B, which means the Caco is well above floor level and thus starts falling down.

A simple test map is attached. If you kill the Caco, chances are high that its corpse remains stuck on the higher sector and falls down to the ground of the lower sector after a save and restore cycle.

The most obvious cure to this issue is doing what Killough did and just leaving the map object's floor and ceiling values as they were when the game was saved.

[test.zip](https://github.com/JNechaevsky/russian-doom/files/1855340/test.zip)

**Comment by JNechaevsky** [comment]
Awesome, thanks for analysis!

I checked out your map with and without my correction, very briefly, because I'm at dinner break now. Results:

- Without addition: Caco remains "on air" and not falling to the hole where it comes from.
- With addition: Caco falling to the hole where it comes from.

I believe it is proper for Caco to fall, since it was able to climb out from that hole. In other words: if it is able to get out, why it should be impossible to get back? Of course, I'm speaking about corpse only, not about all possible objects.

Killough did a good thing, but it mostly related to fixing a bug of falling player into wall after reloading game, if player was saved almost on the air. I'm, however, trying to do a _"proper"_ falling for corpses.

The last thing I'm wondering about - is it safe for Archvile resurrections? From one side - probably not much. From another - I'm not changing monster's radius to make it smaller and fit possible holes, I'm only enforcing Z position. 

Pretty good place for testing with tons of monsters and Archviles is Plutonia MAP32, in the evening I'll try to investigate what will happen there with and without correction.

**Comment by JNechaevsky** [comment]
**Fabian**, you was right, `mom`entums are not necessary here. Thank you for testing map, after some changes I finally figured out what is happening in the meaning of game view.

Let's make a small change by reducing the size of the pit and make an Imp to be placed there. Note that "dividing line" is placed just a little bit left from Imp's "center of mass" (erm, is it `FRACUNIT`?):

![](http://priscree.ru/img/fbe48e922e1a0b.png)

Because of engine specifics and despite of this new pit is kinda small, Imp will be spawned on pit's floor in both Doom Builder and source port:

![](http://priscree.ru/img/4793b5c690bb5e.png) ![](http://priscree.ru/img/3458af76780938.png)

**Comment by JNechaevsky** [comment]
...which is meaning that Imp can "exist" in that pit.

Now most interesting part. Without my correction, Imp is able to get out from that pit, but it will not fall down there after death. With my correction it will fall.

And here's the critical point: my correction is leading to another infamous clipping bug:

![](http://priscree.ru/img/84444259f1f381.png)

**Comment by JNechaevsky** [comment]
Guess I have to make a choice. From one side, ability to fall for monster's corpses is a proper behavior in some aspects. From another, having no any visual glitches is much more important for me, and I believe also for all the players.

Better to don't apply it until vanilla [clipping bug](https://doomwiki.org/wiki/Sprites_improperly_clipped) will be fixed somehow. I'll leave this working code just to don't loose it:

**p_mobj.c**
```
	// you can cycle through multiple states in a tic
	if (!mobj->tics)
	    if (!P_SetMobjState (mobj, mobj->state->nextstate) )
		return;		// freed itself
    }
    else
    {
+++ // [JN] Also enforce Z-positioning. Fixes vanilla bug when monster's
+++ // corpses weren't falling from the edges into some holes sometimes.
+++ if (singleplayer                        // Leave compatibility alone
+++ && mobj->z > mobj->dropoffz             // Only objects contacting dropoff
+++ && !(mobj->flags & MF_NOGRAVITY)        // Only objects which fall
+++ && (mobj->flags & MF_CORPSE)            // Only for corpses
+++ && (mobj->gear == 0))                   // Only if Torque has beed stopped
+++ {
+++     mobj->floorz = mobj->subsector->sector->floorheight;
+++ }

	// check for nightmare respawn
	if (! (mobj->flags & MF_COUNTKILL) )
	    return;
```
