### ISSUE TITLE
Update player's view when on moving platform

### ISSUE THREAD

**Issue by bradharding** [Russian-Doom/russian-doom#60]
Now it's my turn! 😝 Here's an idea you might be interested in that I've been meaning to let you know about. I fixed it a while ago in DOOM Retro.

In Vanilla DOOM, when you're on a lift, the player's height isn't immediately updated until one tic later. This causes the player's view to noticeably jolt when the lift they are on reaches the top or bottom. To test, get on a lift (such as the small one in DOOM2.WAD MAP01) so that you can see the floor at the same time. Compare how your port handles it with mine. (Incidentally, ZDoom fixes this as well but I assume in a completely different way.)

All it requires is an additional call to `P_CalcHeight()` in `P_ThingHeightClip()` like I do [here](https://github.com/bradharding/doomretro/commit/345899ec14b3facd0196666648bcc609bdb18bd3). I'm not sure if this would affect demo compatibility, however. (@fabiangreffrath, you might be interested in this as well.)

**Comment by JNechaevsky** [comment]
Oh yes, that's the case, thanks! Sure, I remember about view height on the moving platforms and must admit that constant view is looking&feeling much better, so I will gladly commit it in the evening.

Thanks again!

**Comment by JNechaevsky** [comment]
Not good idea: to make a view height changing softly (like in a Build engine). Not sure it is possible or even worth - changing of view height must by synchronized with `floorz`, and soft changing will be looking as notable delay which is not correct.

**Comment by bradharding** [comment]
> Not good idea: to make a view height changing softly (like in a Build engine). Not sure it is possible or even worth - changing of view height must by synchronized with floorz, and soft changing will be looking as notable delay which is not correct.

Sorry, Julia. I have no idea what you're trying to say.

**Comment by fabiangreffrath** [comment]
I guess this affects if a projectile hits the player's head or not while he is standing on a moving platform, so this is probably out of scope for Crispy.

**Comment by JNechaevsky** [comment]
**Brad**, I was meaning smooth changing of view height while moving on lifts. Ah, nevermind, that's my another morning's _grandiose_ thought, plus I seems to be incorrect. Now, trying to remember what was happening in Duke3D/Blood games on moving platforms:

- Player's view is not changing.
- Player's HUD weapon vertical position is changing smoothly, depending of where you are moving (up or down).

Something like this. **Fabian**, in theory, can this be connected somehow to the "squat down weapon" feature? Or it's too abstract?

**Comment by fabiangreffrath** [comment]
This might be demo-safe (though probably incomplete, as it ignores the bob value - which in turn must not get changed anyway)

```
--- a/src/doom/p_map.c
+++ b/src/doom/p_map.c
@@ -633,6 +633,10 @@ boolean P_ThingHeightClip (mobj_t* thing)
     {
        // walking monsters rise and fall with the floor
        thing->z = thing->floorz;
+       if (thing->player)
+       {
+           thing->player->viewz = thing->z + thing->player->viewheight;
+       }
     }
     else
     {
```

**Comment by bradharding** [comment]
This is a much simpler, faster solution, Fabian. Thank you.
