### ISSUE TITLE
Heretic: music don't resume playing

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#62]
Music don't resume playing after unpausing the game in following conditions:

1. Pause the game
2. Enter volume menu
3. Hit `ESC` (no need to change anything)
4. Despite of game is unpaused, music don't resume playing.

Surprisingly, it's a vanilla bug which I can reproduce in Chocolate Heretic.

**Comment by JNechaevsky** [comment]
First one was related to the game menu, here's another one case:

1. Pause the game
2. Hit `F10`
3. Press `N` or `ESC`
4. Despite of game is unpaused, music don't resume playing.

**Comment by JNechaevsky** [comment]
Interesting. I've got an odd bug with Chocolate Heretic. @nukeykt, could you please take a look? It is happening with both OPL2 and OPL3 sythts, and it's not happening in Heretic for DOS. Could it an Nuked OPL bug then?

- https://youtu.be/mFb8lYxB3pY

Steps to reproduce:

1. Start any level normally.
2. Pause the game.
3. Hit `F7` and confirm game ending.
4. Music will lock up in first note (на первой музыкальной ноте, могу ошибаться в терминологии).

@fabiangreffrath should I post this issue in Chocolate tracker?

**Comment by JNechaevsky** [comment]
It's not exactly an OPL bug, it's a mess of this: 
- https://github.com/chocolate-doom/chocolate-doom/blob/master/src/heretic/g_game.c#L1025

This is happening because of some missing logics of setting `paused` to `false` in some cases later... I'm not sure how to fix this more proper than I did in https://github.com/JNechaevsky/russian-doom/commit/20b73cb7d10890a42ad580efdf64334269b19120, but at least it's working and don't calling `S_ResumeSound` every game tic.

**Comment by fabiangreffrath** [comment]
> should I post this issue in Chocolate tracker

Is this is contrary to the upstream Heretic experience, this is probably the best thing to do. But make sure to keep @nukeyt in the message.

**Comment by JNechaevsky** [comment]
Okay, thanks, I'll do as you say. Will post an proper issue in Chocolate tracker in the Monday or, uhhh... well... Tuesday.
