### ISSUE TITLE
Implement optional crosshair

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#64]
Should be in two variants:

- Static (red)
- With player's health indication (green - yellow - red)

Only cross-style is planned: http://priscree.ru/img/9012ad67d8a714.png

**Setup.exe**

Should be something like this. If initial crosshair feature is active, second one with health indication will appear:

```
TXT_NewSeparator("Геймплей"),
    TXT_If(gamemission == doom,	TXT_NewCheckBox("Отображать прицел", &draw_crosshair)),
        TXT_If(gamemission == doom,
            TXT_NewConditional(&draw_crosshair, crosshair_health,
            TXT_NewHorizBox(
            TXT_NewStrut(4, 0),
            TXT_NewCheckBox("Индикация здоровья игрока", &crosshair_health), NULL))),
```

**Vanilla game mode?**

Since it's an optional tactical feature, no crosshair in vanilla!

**In the code**

Further investigation needed. At the moment, I have placed simple `V_DrawPatch` into `ST_drawWidgets`, and it seems to be wrong, because in case of using traditional HUD, crosshair is no longer appearing.

**Comment by JNechaevsky** [comment]
Should be something like this:

```
    if (!vanillaparm && !automapactive && crosshair_draw)
    {
        if (crosshair_health)
        {
            if (plr->health >= 66)
            {
            V_DrawPatch(ORIGWIDTH/2,
                ((screenblocks <= 10) ? (ORIGHEIGHT-32)/2 : ORIGHEIGHT/2),
                W_CacheLumpName(DEH_String("XHAIRG"), PU_CACHE));
            }
            else if (plr->health >= 33)
            {
            V_DrawPatch(ORIGWIDTH/2,
                ((screenblocks <= 10) ? (ORIGHEIGHT-32)/2 : ORIGHEIGHT/2),
                W_CacheLumpName(DEH_String("XHAIRY"), PU_CACHE));
            }
            else if (plr->health <= 32)
            {
            V_DrawPatch(ORIGWIDTH/2,
                ((screenblocks <= 10) ? (ORIGHEIGHT-32)/2 : ORIGHEIGHT/2),
                W_CacheLumpName(DEH_String("XHAIRR"), PU_CACHE));
            }
        }
        else
        {
            V_DrawPatch(ORIGWIDTH/2,
                ((screenblocks <= 10) ? (ORIGHEIGHT-32)/2 : ORIGHEIGHT/2),
                W_CacheLumpName(DEH_String("XHAIRR"), PU_CACHE));            
        }
    }
```

Offsets should be done in the sprite lumps. And by the way, many thanks to @fabiangreffrath for the `ORIGWIDTH` and `ORIGHEIGHT` values! I was almost close, but totally forgot about necessity of status bar height.

**Comment by JNechaevsky** [comment]
All done.

- Unscaled, health indication: http://priscree.ru/img/2cb27d7ef24540.png
- Unscaled, no health indication: http://priscree.ru/img/c95d6180d60272.png
- Scaled, health indication: http://priscree.ru/img/fc84a1f72cb129.png
- Scaled, no health indication: http://priscree.ru/img/fc84a7d1ffcf4d.png

**Comment by SoDOOManiac** [comment]
Is this crosshair a sprite contained in some additional WAD?

**Comment by JNechaevsky** [comment]
Yep, it's inside `src/russian/russian-doom-common.wad`, lumps XHAIR**.

**Comment by JNechaevsky** [comment]
This got's interesting. Although I like blue crosshair in Crispy, in RD I found it totally bad looking from aesthetic POV. It's does not harmonize with red HUD digits, and obviously requires a colored HUD, which I'm not planning to implement. Red and blue colors are opposite, and having _"much of red"_ and _"few of blue"_ making some disbalance in my vulnerable artistic imagination. Duh. :(

![doom09](https://user-images.githubusercontent.com/21193394/39674503-8d3032ac-5155-11e8-8f0f-8bb2aec977ca.png)
