### ISSUE TITLE
[Idea] No opening sound for opened door

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#66]
Okay, it's a weekend and perfect time to get tipsy and figure out some odd ideas.

The idea is - if player is opening the door from one side, he's hearing opening sound. This is absolutely okay. But while door is opened and player press `USE` from opposite side (i.e. using another door-related linedef), it is possible to hear opening sound, despite that the door is opened already.

Technically this is correct, because we are operating two (or more) different linedefs. But just for some aesthetically terms, it may be fixed somehow.

No, I'm not thinking about rejecting to use second++ door's linedef, this is not acceptable for both demo compatibility and game mechanics. But if there will be just no sound, it could be good.

**EDIT:** This seems to be related only to the doors, thats stays opened.

Kindly notifying @fabiangreffrath and @bradharding to don't make a cross-posting for this idea.

**Comment by JNechaevsky** [comment]
Yeah, it's related only to the doors, that's stays opened. To be more clear, a notable place on MAP06 of Hell on Earth:

- https://youtu.be/dmYAfcQOm4k

**Comment by fabiangreffrath** [comment]
You could check if the sector that is affected by the linedef already has its `specialdata` field set. But beware, there may be more than one linedef with the same tag as a specific sector and there may be more than one sector with this tag as well.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, may I ask for advice? Doors are still something unlearned for me. So initially, opening sound for door from video is playing here: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/p_doors.c#L502

And the code should be something like this:
```
      default:	// LOCKED DOOR SOUND
+++ if (door_not_in_raised_state)
+++ {
+++     S_StartSound(&sec->soundorg,sfx_doropn);
+++ }
	break;
```

But the problem is, I don't see how to properly define raised state, also have no idea how to operate with `specialdata`. There are also bunch of other instances with `sfx_doropn`, but I need just a starting point please.

**Comment by fabiangreffrath** [comment]
Whenever a reversible action is applied to a sector, it's `specialdata` field is pointing to the thinker that takes care of that action. So, if a door is raised and waiting to close again, the sector's `specialdata` field will point to a `vldoor_t` object which has a thinker assigned to it (this happens a few lines after the code that you refer to, for example).

So, in short words, if a sector acts as a door, it has its `specialdata` field point to *something* as long as it is in its raised state and needs some thinker that counts the tics until it closes again. 

```
if (!sec->specialdata)
{
    S_StartSound(&sec->soundorg,sfx_doropn);
}
```

**Comment by JNechaevsky** [comment]
Thank you! I was trying to do something like `if (sec->specialdata != NULL)` (or other values), and oddly difine a _door_, which is defined later as a new thinker.

Will dig, erm, will knock in the evening, :door:

**Comment by JNechaevsky** [comment]
Hmph. Still have a sound with this (both red key door sides are linedef effect `33`, falls under the condition):

```
    default:	// LOCKED DOOR SOUND
+++ if (!sec->specialdata)
+++ {
        S_StartSound(&sec->soundorg,sfx_doropn);
+++ }
    break;
```

Using a `if (sec->specialdata)` gives no opening sounds at all.

**Comment by JNechaevsky** [comment]
Condition `if (!door->topheight)` seems to be working, but whole `for proper sound` is moved below `new door thinker`. Need to test it deeper.

```
    // new door thinker
    door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
    P_AddThinker (&door->thinker);
    sec->specialdata = door;
    door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
    door->sector = sec;
    door->direction = 1;
    door->speed = VDOORSPEED;
    door->topwait = VDOORWAIT;

    // for proper sound
    switch(line->special)
    {
      case 117:	// BLAZING DOOR RAISE
      case 118:	// BLAZING DOOR OPEN
	S_StartSound(&sec->soundorg,sfx_bdopn);
	break;
	
      case 1:	// NORMAL DOOR SOUND
      case 31:
	S_StartSound(&sec->soundorg,sfx_doropn);
	break;
	
      default:	// LOCKED DOOR SOUND
+++ if (!door->topheight)
	S_StartSound(&sec->soundorg,sfx_doropn);
	break;
    }
```

**EDIT:** Nope, not working properly.

**Comment by bradharding** [comment]
Try this?

```
    // new door thinker
    door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
    P_AddThinker (&door->thinker);
--- sec->specialdata = door;
    door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
    door->sector = sec;
    door->direction = 1;
    door->speed = VDOORSPEED;
    door->topwait = VDOORWAIT;

    // for proper sound
    switch(line->special)
    {
      case 117:	// BLAZING DOOR RAISE
      case 118:	// BLAZING DOOR OPEN
+++ if (!sec->specialdata)
	S_StartSound(&sec->soundorg,sfx_bdopn);
	break;
	
      case 1:	// NORMAL DOOR SOUND
      case 31:
+++ if (!sec->specialdata)
	S_StartSound(&sec->soundorg,sfx_doropn);
	break;
	
      default:	// LOCKED DOOR SOUND
+++ if (!sec->specialdata)
	S_StartSound(&sec->soundorg,sfx_doropn);
	break;
    }

+++ sec->specialdata = door;
```

**Comment by JNechaevsky** [comment]
Un-uh, all the same. :/

**Comment by JNechaevsky** [comment]
Oh, there is a `door = sec->specialdata`, few lines above `S_StartSound`: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/p_doors.c#L430. That's a possibly good point.

**Comment by JNechaevsky** [comment]
Brad, I haven't noticed your last edit, It seems to be working! I've just made a little correction, so now it is:
```
    // new door thinker
    door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
    P_AddThinker (&door->thinker);
--- sec->specialdata = door;
    door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
    door->sector = sec;
    door->direction = 1;
    door->speed = VDOORSPEED;
    door->topwait = VDOORWAIT;

    // for proper sound
    switch(line->special)
    {
      case 117:	// BLAZING DOOR RAISE
      case 118:	// BLAZING DOOR OPEN
+++ {
+++     if (!sec->specialdata && door->type != vld_open)
        S_StartSound(&sec->soundorg,sfx_bdopn);
+++   }
	break;
	
      case 1:	// NORMAL DOOR SOUND
      case 31:
+++   {
+++     if (!sec->specialdata && door->type != vld_open)
        S_StartSound(&sec->soundorg,sfx_doropn);
+++   }
	break;
	
      default:	// LOCKED DOOR SOUND
+++   {
+++     if (!sec->specialdata && door->type != vld_open)
        S_StartSound(&sec->soundorg,sfx_doropn);
+++   }
	break;
    }

    switch(line->special)
    {
      case 1:
      case 26:
      case 27:
      case 28:
	door->type = vld_normal;
	break;
	
      case 31:
      case 32:
      case 33:
      case 34:
	door->type = vld_open;
	line->special = 0;
+++ sec->specialdata = door;
	break;
```

I have a bad feeling that placing `sec->specialdata = door;` into `case 31-34` will break some things. Need to try to use only `door->type != vld_open` as a playing sound conditions.

**Comment by JNechaevsky** [comment]
Apparently, figured it out (three years, oh my god!). In Heretic it never happens because of this line: https://github.com/JNechaevsky/russian-doom/blob/master/src/heretic/p_doors.c#L139

However, Heretic's `S_StopSound` gets `void *_origin`, while in Doom it's a `mobj_t *origin`. Have to figure out what to do next, either make copy of `S_StopSound`, or just give it `void` type. Probably second one approach, since it's same way as it is done in Heretic and it's seems to be working fine.
