### ISSUE TITLE
Inaccurate vertical shooting

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#72]
Vertical shooting angle is inaccurate, and the problem in this code, value `173`:
```
bulletslope = (mo->player->lookdir / MLOOKUNIT << FRACBITS) / 173;
```

Since now I have crosshair, it it possible no note that shooting with maximum angles up and down have some notable inaccuracy. Crosshair is placed correctly in the center of the screen:

![](http://priscree.ru/img/6e289492d1c72b.png)

**Comment by JNechaevsky** [comment]
Value `146` seems to be precise enough:

![](http://priscree.ru/img/737eb81d32af59.png)

**Comment by JNechaevsky** [comment]
I can't say for sure, was it a Raven's mistake or brought by `MLOOKUNIT` smoothing. Apparently, Raven haven't tested enough this value, but since vanilla Heretic and Hexen wasn't having a crosshair, barely it was possible to test at all. But I don't want to blame anyone, it's a bad and unacceptable ethics.

Kindly asking @fabiangreffrath and @bradharding to check their respected projects for this issue! :stuck_out_tongue:

**Comment by fabiangreffrath** [comment]
Have you tried this?
```
bulletslope = (mo->player->lookdir << FRACBITS) / (173 * MLOOKUNIT);
```

**Comment by JNechaevsky** [comment]
Just tried, un-uh, not working correct with both status bar on and off. :( 
- http://priscree.ru/img/dcf53648d21208.png

**Comment by fabiangreffrath** [comment]
It should be possible to somehow calculate this from e.g. the `yslopes[]` array...

**Comment by JNechaevsky** [comment]
Maybe, maybe. In PrBoom+ aiming working fine (except bullet puffs are sliding from the floors/ceiling to the nearest walls), but I don't want to investigate it farther. At the moment, both crosshair and hitscan/missiles trajectories are calibrated well.

**Comment by fabiangreffrath** [comment]
In PrBoom+ vertical aiming is derived from OpenGL rendering. This is a different approach from the y-shearing that I have adapted from Heretic.

> At the moment, both crosshair and hitscan/missiles trajectories are calibrated well.

Yes, but I don't like the concept of a "magic number" that "somehow" works.

**Comment by JNechaevsky** [comment]
Uh? OpenGL drawing even in PrBoom.exe, not in GlBoom.exe? 

Sure, I can understand the difference between camera movement in software-like and OpenGL (AFAIR, in OpenGL camera never changes it's position - only game world is scaling/shifting/rotating and so on), it's totally different things. 

Just a nice example, try one day to extend `mlook` limits to something like 360°. Ueah, you will be able to see "floor/ceiling only", but with such an odd angles... Kinda awful, but dang, it will work at some points! Ah yes, you will also need to move mouse a lot after some angle. :)

As about magic numbers, yeah, frankly speaking I'm also don't like this approach (and the values are all different for Doom, Heretic and Hexen). But that's the best I can do _without much pain_.

And hey, I do not blame you at all, don't get me wrong!

**Comment by fabiangreffrath** [comment]
Sorry, my previous comment was misleading!

Mouse look came very late to PrBoom+'s software renderer, it was formerly restricted to the OpenGL renderer exclusively. Then, at some piont, e6y realized that vertical looking in the software renderer is not much more than shifting the `yslope` for the current view and he implemented it. However, vertical looking for the OpenGL renderer was already there and is based on OpenGL's 3D polar coordinates. Thus, the code to add vertical looking into the software renderer had to use the same "values" for the looking angle as the previous implementation for OpenGL.

So, the approaches are different. PrBoom+ uses different numbers for the view angle to achieve the same thing that Heretic's approach used with its lookdir numbers (which I scaled by MLOOKUNIT).

**Comment by fabiangreffrath** [comment]
PS: I think it's mostly that looking exactly into the vertical direction means angle = 0 in the OpenGL implementation, whereas it is rather impossible in Heretic's y-shearing approach, where lookdir = 0 means to look exactly into the horizontal plane.

**Comment by JNechaevsky** [comment]
Thanks for clarifications, this explains much things!

Taking opportunity to thank you for `MLOOKUNIT`, which brings a lot of smoothness to vertical angles. But mostly ideal smoothing comes with two other things: 

a) uncapped framerate mode (I think we should have a different term for it, like "vsynced mode" :),
b) `lookdir` _or_ `lookfly` deltas. 

If I'll forget to demonstrate unlimited mlook in the evening, please kick me. That's a funny thing like "cool to see", but "never try to do this at home"!

**Comment by fabiangreffrath** [comment]
lookfly deltas are really only for looking by pressing buttons. You press one button and your looking angle changes by the exact same amount each time you press. This is impossible to work smoothly with a mouse where you want your looking angle to change exactly as far as you move the mouse.

I am looking forward to seeing how unlimited vertical looking looks. ;)

**Comment by JNechaevsky** [comment]
Ah, hm, I was sure that they are also smoothing mouse usage. In any way, until I have not merged [this](https://github.com/JNechaevsky/russian-doom/commit/6092bde691a61fd1a833c8dd8dff2d03b5690988) and [this](https://github.com/JNechaevsky/russian-doom/commit/064f700826f6fd028f47d846d553c0f33063b294) commits, verical mlook wasn't smooth enough in _vsynced_ mode. Good thing now everything working fine, no more changes needed!

Ta-da! You can check it by yourself by simple changing of two values @ r_data.h:
```
#define LOOKDIRMIN	11000 // [crispy] -110, actually
#define LOOKDIRMAX	9000
```
- https://youtu.be/ke6WcdrbjMk

Looks likes it's not unlimited, but hard to say for sure. Probably, after achieving 180° of up and 180° of bottom, pixels just go crazy by scaling, so it is not possible to make 360° rotation of vertical looking.

I wonder if this can be improved somehow (i.e. making floor/ceiling textures looking more good while extending vertical mlook angles), but it's seems to be that viewing calculations should be extended by somekind of a pure geometry/trigonometry formulas, so better don't think about it. I always was having a C grade on exact sciences, so there is definitely nothing smart I can suggest. :)

**Comment by fabiangreffrath** [comment]
Wow, thanks for the video, that's really impressive!

Especially here:
https://youtu.be/ke6WcdrbjMk?t=178

Notice how the vertical line strictly refuses to go anywhere but vertical. ;)

**Comment by JNechaevsky** [comment]
Yeah! I even haven't noticed this. Now I'm trying to raise my head and notice - are the real corners in my room are also remain vertical? And what is `MLOOKUNIT` and camera deltas inside the eyes? The only thing I know for sure: eyes have frame interpolation while changing looking direction! Sick. :)

_P.S. Meanwhile, it's getting late, time to take care about PR for proper music resume in Choco._

**Comment by JNechaevsky** [comment]
**Fabian**, FYI: only your static crosshair is affected by this inaccuracy, projected is fine (obviously, because crosshair itself is a "trajectory"). But that's not the point, I want to suggest another thing - make projected corsshair's vertical movement more smooth.

It's absolutelly fine while horizontal movement, but in vertical there is some notable shaking. It's barely notable in capped framerate, but pretty much notable in vsynced.
