### ISSUE TITLE
Interesting comment in P_NoiseAlert

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#76]
```
//
// P_NoiseAlert
// If a monster yells at a player,
// it will alert other monsters to the player. <--- [JN] hmm!?
//
```

To make this original idea working, all that is necessary is to add this line to the `A_Look`, just like this:

```
...
    else
        S_StartSound (actor, sound);
    
+++     P_NoiseAlert (actor->target, actor);
    }

    P_SetMobjState (actor, actor->info->seestate);
}
```

Obiviously, as non-optional it will be a demo killer, so it's lovely to have this as an optional, single player only feature.

@bradharding, maybe it will be interesting to you.

**Comment by bradharding** [comment]
Interesting. It would affect gameplay quite a bit though...

**Comment by JNechaevsky** [comment]
Oh yes, it will eliminate any possibility to run stealthy in ~some~ many places. But I like this idea by two reasons:

1. It was original id's idea, so it can be considered as canonical.
2. It may bring some difference in the gameplay without breaking game mechanics. Also, it's seems to be impossible to achieve this effect by modding (surely for Dehacked, not surely for Decorate, but Decorate is completely different kitchen).

Still haven't played around much with it, my priority No. 1 is Jaguar for now. And there is exactly one self-question: should be a tactical or audible feature? First one is more technically correct, but second one will be more clear for players. =|

**Comment by fabiangreffrath** [comment]
https://youtu.be/7V8mmoKWJNE

**Comment by JNechaevsky** [comment]
Bleh. Some things should be documented on Doomwik as welli, not just on YouTube.

**Comment by fabiangreffrath** [comment]
It changes the entire gameplayer literally from the first second on and thus has never been picked up by any other source port. Maybe this would be a nice addition to your Nightmare+1 skill level?

**Comment by JNechaevsky** [comment]
Hm-hmm. Just played with it a little bit longer (10 minutes instead of 2). Can't say that there is a significant difference, but there is still a difference. Sounds like a neat idea, I have to to try this combination. Just need to finish englification first. Thanks for suggestion!
