### ISSUE TITLE
Lightning bug on E2M4

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#78]
It's not exactly a technical bug, it's a rather design bug. Despite of all three sectors have effect 12 and same light levels, second one (with a door) drops brightness to 0 while lights are off. All existing ports seems to be affected.

![bad](https://user-images.githubusercontent.com/21193394/45780042-5646cf00-bc65-11e8-9d18-2983e51a8d7d.png)

I don't see any possible ways to fix this entirely (and frankly, not sure it is possible at all), but simple condition could make some perfection:

**p_lights.c @@ P_SpawnStrobeFlash**
```
    if (flash->minlight == flash->maxlight)
    {
        // [JN] Special fix for E2M4:
        if (canmodify && gamemission == doom && gameepisode == 2 && gamemap == 4)
        flash->minlight = 112;

        else
        flash->minlight = 0;
    }
```

_Edit:_ add a sector number for more strict checking.

Need to think more, is it really worth to commit this...

**Comment by JNechaevsky** [comment]
I have to do this in the weekend: I need to inspect every map of Doom 1 / 2 / TNT / Plutonia for sector effect 12 and see, is this problem happens somewhere else.

**Comment by JNechaevsky** [comment]
@bradharding, I have inspected all maps of D1/D2/TNT/Plutonia. There are some places, where lighting is dropped to `0` instead of surrounding lighting, but it isn't looking like a map error. I think I'll stick with exclusive E2M4 fix.

**Comment by bradharding** [comment]
I looked into this and couldn't determine a more general fix, so I guess a specific hack for E2M4 is the only way.

**Comment by fabiangreffrath** [comment]
It would be interesting to know why `P_FindMinSurroundingLight()` returns `0` in this specific case. Does the sector in question consist of separate areas? Or else, which is the sector in the `P_FindMinSurroundingLight()` loop that returns `0` for its `lightlevel`?

**Comment by JNechaevsky** [comment]
I have few thoughts about this, and the half of answer can be found by using Doom Builder. Please wait until evening, I'll post some info.

**Comment by JNechaevsky** [comment]
**Brad**, **Fabian**, first of all, thanks for the interest to this case! Let's see what I have found... It's not much, but could be interesting at some point.

Let's take a look at E2M4 first, using Doom Builder:

![1](https://user-images.githubusercontent.com/21193394/45963110-19932300-c02b-11e8-80f6-9f333969135d.png)

As you may see, all three sectors are same on lighting and effect. So what's causing the problem in second door-sector? Probably something missing in `P_FindMinSurroundingLight()` - it can't find surrounding sector and then lighting is dropped to `0`? Not sure... Let's try to fix on the map itself. To do this, I'll join (not merge) all three sectors into one, and as a result, there secret door will be missed:

![2](https://user-images.githubusercontent.com/21193394/45963902-02edcb80-c02d-11e8-9ced-7bb69bb62b9d.png)

Bad idea. Let's take another approach, by adding "control" zero-height sectors for secret door. It must have zero-height, otherwise the door will not open properly (floor & ceiling height should be equal to the outer surrounding ceiling height):

![3](https://user-images.githubusercontent.com/21193394/45964224-d71f1580-c02d-11e8-924e-3001f2952699.png)

Not working. And it will not work even if control sectors will be not zero-height. So I believe, height does not matter here. Even if secret door will be slightly opened initially, it will not change the situation.

![doom21](https://user-images.githubusercontent.com/21193394/45964448-80fea200-c02e-11e8-8cbd-154ae6687749.png)

And this is where I'm out of ideas. :(

But there is more interesting stuff to check out. Fun thing - on Atari Jaguar Doom, E2M4 have a number `12` (just like a sector effect), and mostly same happens there, but with some difference. Here's how it looks in Calico:

![4](https://user-images.githubusercontent.com/21193394/45964697-2f0a4c00-c02f-11e8-94c4-8c838f683c3d.png)

As far as i understand, Jaguar version using a different color model or rendering mechanics. I was trying to seek it out, but most of the code seems to be assembled and totally unreadable for me (here's a repository: https://github.com/JNechaevsky/jaguar-doom). But in my TC this problem is looking as it...should:

![5](https://user-images.githubusercontent.com/21193394/45964918-b788ec80-c02f-11e8-990d-088cf1f36ea8.png)

____________

Now about the other maps where this problem happens. I have checked all of D1/D2/Plutonia/TNT maps, it was not very big deal by using a Doom Builder, but one moment seems interesting for me - in D2 there are just a few maps with effect 12: MAP12 _(oh, again!)_,MAP13 and MAP18, while in D1 effect 12 is used very often. Could it because of newly introduced effect 17 in D2(random flickers)? Hmmm.

Anyway, some problematic places can be found only in TNT:

MAP07:
![6](https://user-images.githubusercontent.com/21193394/45965540-6974e880-c031-11e8-8388-102348224353.png)

MAP09:
![7](https://user-images.githubusercontent.com/21193394/45965578-89a4a780-c031-11e8-8b31-0d763a4e3fc6.png)

![8](https://user-images.githubusercontent.com/21193394/45965625-a7720c80-c031-11e8-9c3e-714d682b6144.png)

![9](https://user-images.githubusercontent.com/21193394/45965659-beb0fa00-c031-11e8-9dbf-dcfae20465c7.png)

and MAP19:

![10](https://user-images.githubusercontent.com/21193394/45965705-e2744000-c031-11e8-9f51-0719924043c5.png)

... but they are looking more like "designer's solution", so fixing this bug entirely may be not good idea. 

**Edit:** what is a CRY palette after all? Is it "Cyan / Red / Yellow"?
https://github.com/team-eternity/calico-doom/blob/master/src/r_phase5.c#L10

**Comment by fabiangreffrath** [comment]
I am afraid there is not much you can do. The surrounding sectors have the exact same initial light levels as the sector in question, so there is nothing to fade out against but `0`.

**Comment by JNechaevsky** [comment]
Oh. And if I change brightness of one of surrounding sector to 207, here's what will happen... :unamused:

![doom28](https://user-images.githubusercontent.com/21193394/45974448-080d4380-c04a-11e8-8421-b31e8c605e2a.png)

I have fixed it by adding small and very strict condition: https://github.com/JNechaevsky/russian-doom/commit/800a5b8e39f420d988987fec9d93cb714358bb7e. Not a very good approach, but in terms of pixel-perfection, I think I'm okay with it.

![doom29](https://user-images.githubusercontent.com/21193394/45974603-7b16ba00-c04a-11e8-8810-edb3e1ffafa7.png)

**Comment by JNechaevsky** [comment]
From another side, I have a bad feeling that this small condition may eat few bits of performance, by continuous checking (every tic?) for E2M4... Could it be so?

**Comment by fabiangreffrath** [comment]
Probably in the order of µs.

**Comment by JNechaevsky** [comment]
Uh? "µs" is a microsecond?

**Comment by fabiangreffrath** [comment]
Yes, sure. You are adding a single comparison. Computer are *very fast* at comparing numbers, y'know? ;)

If you want to go sure, put the comparison first that's least probable to evaluate to `true`, bcause the following ones are not checked if the first one is already false.

**Comment by JNechaevsky** [comment]
> Computer are very fast at comparing numbers, y'know? ;)

I'm afraid you are still thinking to good about my programming-and-so-on skills. :/

If I got you right, running program will check conditions from left to right, and if left / first one is `false`, other ones will not be checked? If so, the condition should be reformatted to:
```
        if (gameepisode == 2 && gamemap == 4 && gamemission == doom && canmodify && fix_map_errors &&)
        flash->minlight = 112;
        else
        flash->minlight = 0;
```
Legend:

`canmodify` - internal boolean. Becomes `true` when playing vanilla, unmodified maps and gives possibility to apply map fixes at all.
`fix_map_errors` - outer boolean for optional feature. `true` allows map fixes (but never in `-vanilla` mode).

Both of these booleans are mostly always true, so I have moved them to the end. `gameepisode 2` seems to be the most rare case, as well as `gamemap 4`, so now they are checked first. Is it better now, yep?

**Comment by fabiangreffrath** [comment]
Should save you some microseconds, yes. :wink:

**Comment by JNechaevsky** [comment]
Phew... It feels like "level up" and looks likes I've forgot everything in this summer. Better don't do any breaks in the work with code! Thank you! Will commit changes soon.

**Comment by JNechaevsky** [comment]
For the record: acording to the Jaguar Technical Reference Manual, CRY is a "cyan, red and intensity":
https://www.hillsoftware.com/files/atari/jaguar/jag_v8.pdf (see page 25).
