### ISSUE TITLE
Doom: implement brightmaps for SW2SATYR, SW2LION and SW2GARG

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#79]
By very careful touching of the tan colors, it should be something like this... Need to experiment, perhaps some of them should not be lit in full brightness - GARG (right one) for sure.

![boom](https://user-images.githubusercontent.com/21193394/45970759-06d71900-c040-11e8-8e76-4d22ba8b9a08.png)

_Edit: actually, GARG can be looking pretty well. Updated mockup._

**Comment by JNechaevsky** [comment]
Seems to good. :relieved:
There is a "trash pixel" on Garg's face, and I can't do nothing about it - this pixel is placed on a textue patch.

![doom27](https://user-images.githubusercontent.com/21193394/45972421-51f32b00-c044-11e8-8d9b-2d963c826c36.png)

**Comment by JNechaevsky** [comment]
Brightmap itself:

![pitto](https://user-images.githubusercontent.com/21193394/45973005-e4e09500-c045-11e8-95b7-73df780b7e9e.png)


@fabiangreffrath, @bradharding,

Following colors are highlighted: `56`, `58`, `60`, `61`, `62`, `64`, `65`, `67`, `69`, `139`, `143`, `147`, `148`, `150`. So in tablified  `PLAYPAL` implementation it should be this:

```
static byte brighttan[256] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
	1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
	0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
```

All three textures are present in all the games: D1, D2, Plutonia and TNT, but not existing in shareware.
I've made a testing map, where you can check all three textures in different lighting: 
[brighttan.zip](https://github.com/JNechaevsky/russian-doom/files/2412524/brighttan.zip)

**Comment by fabiangreffrath** [comment]
Would you recommend this for Crispy?

**Comment by JNechaevsky** [comment]
Sure thing, that's why I have posted a tablified approach! There are only two things I'm asking for:

1) Let's double check table values in the game. For `COLORMAP` approach I've made all colors in full bright (i.e. with out diminishing) it's a couple of minutes with Photoshop amusement. But I'm not very familiar with `PLAYPAL` approach, and not sure how to properly implement it in Crispy.
2) Of course, final decision about adding it into Crispy must be done by you.

...or you mean a suggestion in Crispy tracker?

**Comment by fabiangreffrath** [comment]
Yes please.

**Comment by bradharding** [comment]
Thanks Julia! I might nab this for DR.

**Comment by fabiangreffrath** [comment]
If you un-highlight the one color that causes the stray pixel on the Garg's face, does it make a difference for the other textures as well?

**Comment by JNechaevsky** [comment]
Here's what will happen. Sadly, few important pixels will be missing. Click to enlarge:

![ohno](https://user-images.githubusercontent.com/21193394/46026694-ad7cf180-c0f4-11e8-87c3-7bff891c09c5.png)

**Comment by SoDOOManiac** [comment]
>There is a "trash pixel" on Garg's face, and I can't do nothing about it - this pixel is placed on a textue patch.

Let's consider it a wart or a pimple XD

**Comment by fabiangreffrath** [comment]
> Let's consider it a wart or a pimple XD

:+1:
