### ISSUE TITLE
Russian DOOM 2.2 release plan

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#8]
### Step 1: Fix remaining stuff
- ✔️Fix sound breaks (additionaly fix Chainsaw)
- ✔️Update Launcher's version
- ✔️Add Deathmatch 3.0 (plus add Alexandre-Xavier to the THANKS.md and readme files)
- ✔️Fix saving and restoring gametic to preserve Revenant's homing missiles (will be in 2.3, thanks to Fabian for his Amazing solution!)

### Step 2: Release
- ✔️Create new screenshots.
- ✔️Update readme files in both Russian and English.
- ✔️Update change logs in both Russian and English.
- ✔️Update my translated online help for setup executable with new features.
- ✔️Update project's web pages.
- ✔️Upload binary and source code archives on the net.

### Step 3: Web
- ✔️Upload project's web page and online help.
- ✔️Put online changelog files.
- ✔️Update [iddqd.ru](http://i.iddqd.ru/viewtopic.php?t=1044) forum thread.
- ✔️Update page on [Chocolate Doom Wiki](https://www.chocolate-doom.org/wiki/index.php/Russian_Doom). (small screenshot problem, reported to Simon)
- ✔️Update page on [Doomwiki](https://doomwiki.org/wiki/Russian_Doom).
- ✔️Make a post on [VKontakte.ru](https://vk.com/wall178065674_199) social network.

**Comment by JNechaevsky** [comment]
### Version 2.2 released!

Binaries for Windows: [russian-doom-2.2-win32.zip](http://sourceforge.net/projects/jnechaevsky/files/Russian%20Doom/2.2/russian-doom-2.2-win32.zip/download)
Source codes: [russian-doom-2.2-source.zip](http://sourceforge.net/projects/jnechaevsky/files/Russian%20Doom/2.2/Source/russian-doom-2.2-source.zip/download)
Full changelog: [changelog_eng.html](http://jnechaevsky.users.sourceforge.net/projects/rusdoom/files/changelog_eng.html)

### Couple of ideas for future

- Translate Freedoom
Gladly, but I'll have to wait for stable release. All translated graphics is done, but Freedoom updates very often, changing levels and their orders, so even if I will done translation now, for next release of Freedom it might have some obvious inaccuracy.

- Translate Strife
I never was and never will be fan of Strife, so I can't put my soul to this translation. Actually, working on this already, only dialogues and scripts left to translate.

- Add UTF-8 Cyrillic array to textscreen library
I still remember my given word, but still don't have any proper results. It's not a big problem to copy-paste capital chars for Windows-1251 source files, lowercase can be typed as is, without problems. Another thing that scares me - lack of ENDOOM editors, that accepts input of Cyrillic symbols.

- Brightmaps
The more I thinking about them, the more I want them. Code from Strife seems to be easiest solution, but there must be a lot of corrections, like using bright colors strictly for defined texture patches. I'll have to think, try, experiment, suffer. But only this way I'll get something. Dammit.

- Package for OS X
Interesting, but even if I figure out how to make a build, barely I can test it properly. I don't have a real Mac and testing on VmWare Hackintosh certainly not a right way to go.

- Proper "make install" for Linux
Gonna learn Linux more first. There is also some mess with man pages, but binaries are working just fine, and now there is no need to separately download translated wads, they are included to the source code.

- Uncapped/higher framerate
No. In my opinion, it's just destroying feeling of the original games.

- Try to fix some more small Vanilla bugs.
Like [gamma correction resets palette](https://doomwiki.org/wiki/Gamma_correction_resets_palette). There is no critical necessary for that, though, but sounds like an interesting challenge.

- Add support for Philips Ambilight
Gonna have this kind of monitor first and ship it to Jon. :)

#### I have to say...

@fabiangreffrath, @bradharding, @fragglet, @jmtd, @chungy, @capnclever, @AXDOOMER,

Dear Colleagues, guys, friends. Thank you for all your help, advices, patience and kindness. You never refused to help me and without all your assistance my project would never have gone this far. I did not even dream about it. 

That's why having a Contributor title for all three projects: Chocolate, Crispy and Retro is so valuable for me, and that's why I'm always glad to help in proportion to my skills. This is an extremely unique situation of how help to translation-specific project comes from around the world!

With all my kindest regards and huge spasibo!

-Julian

**Comment by bradharding** [comment]
I'm more than happy to help! And thank you for your assistance as well!

BTW, the "gamma correction resets palette" issue is easy to fix. In `m_menu.c`, you'd just change:

```
if (lcd_gamma_fix)
    I_SetPalette (W_CacheLumpName (DEH_String("PALFIX"),PU_CACHE));
else
    I_SetPalette (W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE));
```

to:

```
if (lcd_gamma_fix)
    I_SetPalette ((byte *)W_CacheLumpName (DEH_String("PALFIX"),PU_CACHE) + st_palette * 768);
else
    I_SetPalette ((byte *)W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE) + st_palette * 768);
```

**Comment by JNechaevsky** [comment]
All is done, now to the Strife translation. Still have no maniacal interest, but I must do this because I can. Or I can do this because I must. All graphics done, only dialogues and scripts left to translate.
