### ISSUE TITLE
Doom: implement brightmaps for BRICKLIT and BSTONE3

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#80]
Well, these ones are complicated. Full brightness will make them awful, so I can't suggest a `PLAYPAL` approach... In `COLORMAP` approach with some diminishing it could be something like this...

![pitto](https://user-images.githubusercontent.com/21193394/45977938-9f2ac900-c053-11e8-849f-215b7f43df78.png)

But I'm really not sure that it's is possible or worth it. On the mockup my hands are free by having true colors, but in 256 colors palette things will be significantly different.

**Comment by fabiangreffrath** [comment]
Maybe the `yellowonly[]` translation table could be applied here?

**Comment by JNechaevsky** [comment]
Un-uh. Even my `orangeandyellow` not working properly. The problem is - it's a tan colors...

![doom04](https://user-images.githubusercontent.com/21193394/46035459-bf1dc380-c10b-11e8-80e1-85283fea7d1d.png)

But `brighttan` is even worse. 

![doom05](https://user-images.githubusercontent.com/21193394/46035537-ed030800-c10b-11e8-9590-a7c32ee693cb.png)

Dang. If only we could have a PNG bmaps, it could be something like this:

![duh](https://user-images.githubusercontent.com/21193394/46035735-70bcf480-c10c-11e8-8006-706519fcf629.png)

Oh well. I have to continue color research...

**Comment by JNechaevsky** [comment]
Here's what will happen in case of using full bright for pixels, and that's why I can't suggest `PLAYPAL` approach.
![doom06](https://user-images.githubusercontent.com/21193394/46036794-20936180-c10f-11e8-8802-2880584c182d.png)

Half-bright (support for diminishing) also terrible.

![doom07](https://user-images.githubusercontent.com/21193394/46036913-6e0fce80-c10f-11e8-83b6-22871de3f360.png)

Maybe I should try to lit up a light-bulb with only 1/3 of brightness... Moving on.

**Comment by JNechaevsky** [comment]
1/3 of brightness. Seems to be better, but frankly, it's looking rather unusual than proper. Ultimately not even close to be considered "good enough to be merged". Maybe this looking will be interesting for some mods or custom maps and stuff, but not for vanilla maps - it will simply destroy positive impressions about current bmaps.

![doom10](https://user-images.githubusercontent.com/21193394/46037218-35bcc000-c110-11e8-9162-ec74f48e0d08.png)

1/4 of brightness (becomes almost unnoticeable):
![doom11](https://user-images.githubusercontent.com/21193394/46037576-2ee27d00-c111-11e8-9023-f71ba263f541.png)

I don't want to give up for now, but don't have any farther ideas. Well, actually there is one. As a suggestion №100 - request full support for PNG bmaps, with support for downscaling, multisampling and different blending modes.
:smiling_imp:

**Comment by JNechaevsky** [comment]
Okay, I'm giving up. I don't see any ways to make these bmaps looking good.
Just to make my soul calm down, some Photoshop art:

![untitled-1](https://user-images.githubusercontent.com/21193394/46038933-1bd1ac00-c115-11e8-9b6e-c8acec9e2a48.png)
