### ISSUE TITLE
Implement few extra brightmaps

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#83]
There are few remaining textures, which probably deserve brightmapping. Let's see...

Name | Texture | Result | Where | Comment
-----|---------|--------|-------|--------
EXITDOOR | ![](http://priscree.ru/img/4e59130a35bd8a.png) | ![](http://priscree.ru/img/c9c3486a9f3675.png) | D1 and D2 | Sectors with exit door are mostly always bright, but sometimes lighing is blinking.
TEKWALL2 | ![](http://priscree.ru/img/9398aabedf1ec2.png) | ![](http://priscree.ru/img/9398a18af29bc8.png) | D1 only, including shareware | No way to make a green lights bmapped, bright green pixels will be mixed.
TEKWALL5 | ![](http://priscree.ru/img/9398aada204709.png) | ![](http://priscree.ru/img/8cc9d304f0a8ec.png) | D1 only, including shareware | No way to make a green lights bmapped, bright green pixels will be mixed.
METAL3   | ![](http://priscree.ru/img/8cc9d44512d27f.png) | ![](http://priscree.ru/img/19626bd8bebb7a.png) | D2 only | No way to make a yellow pixels bmapped, bright pixels will be mixed with High Voltage sign. Not sure about this texture.
PANBOOK  | ![](http://priscree.ru/img/fae93f7e13dce2.png) | ![](http://priscree.ru/img/13b849e56c74c6.png) | D2 only | Will not be looking good with `PLAYPAL` approach, the only way make it half-brighted. Not sure it will look good, anyway.
SPCDOOR4 | ![](http://priscree.ru/img/8cc9d6e36ae4f0.png) | ![](http://priscree.ru/img/8cc9d77489017c.png) | D2 only | Hmm...
SW2HOT   | ![](http://priscree.ru/img/8c76a0cc8989d0.png) | ![](http://priscree.ru/img/3f26dd8d0a89c5.png) | D1 and D2, not in Shareware | Few red pixels still can be hightlighted independently, but overall quality is not good enough.
TEKLITE  | ![](http://priscree.ru/img/c9c349114147d1.png) | ![](http://priscree.ru/img/8c76ae3565c008.png) | D2 only | Not sure it is worth it, may look too odd.
TEKLITE2 | ![](http://priscree.ru/img/9398af594e5e0d.png) | ![](http://priscree.ru/img/8cc9d19c224bb0.png) | D2 only | Green pixels are highlithed already, not sure it is worth to highligh small tan ones.

**Comment by JNechaevsky** [comment]
`EXITDOOR`, `TEKWALL2` and `TEKWALL5` in action:

- [Screenshot 1](https://user-images.githubusercontent.com/21193394/46481303-c58ef800-c7fb-11e8-8398-1f2ed73bd2b1.png)
- [Screenshot 2](https://user-images.githubusercontent.com/21193394/46481314-cb84d900-c7fb-11e8-982a-ca0d9f115dcd.png)
- [Screenshot 3](https://user-images.githubusercontent.com/21193394/46481328-d2abe700-c7fb-11e8-961f-4f5cfaaa1ad3.png)

Sadly, current `redonly` was highliting few unnecessary pixels ([screenshot](http://priscree.ru/img/01cc1183fe2368.png)), so I was forced to make a new bmap.
_______

Brightmap itself:
![](http://priscree.ru/img/2daa00d2de428f.png)

@fabiangreffrath, @bradharding, following colors are highlighted: `42`, `43`, `45`, `46`, `47`, `173`, `184`, `186`, `188`, `190`, `191`. In case you are interested in these textures, here's a tablified implementation:

```
static byte redonly1[256] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
```

Testing map for Doom 1 (E1M1): [E1M1.zip](https://github.com/JNechaevsky/russian-doom/files/2446844/E1M1.zip)

**Comment by fabiangreffrath** [comment]
Hm, not sure, too many single bright pixels for my taste.

**Comment by bradharding** [comment]
Agreed. TBH I don't think any of the textures in your table above should have brightmaps, Julia.

**Comment by JNechaevsky** [comment]
Thanks for feedback, colleagues! It makes a huge sense - for now, already a three authoritative for me persons literally have said: "don't do this", so I better follow this recommendation.

Luckily, one well-known mod for GZDoom have these textures brightmapped, so I don't need to do additional job just to check out how it will look in the game:

- [Screenshot 1](http://priscree.ru/img/e118e70f050475.png)
- [Screenshot 2](http://priscree.ru/img/fcf77fa8536170.png)
- [Screenshot 3](http://priscree.ru/img/fcf77297298b18.png)
- [Screenshot 4](http://priscree.ru/img/7af1e263bc5481.png)
- [Screenshot 5](http://priscree.ru/img/877224d34bed5d.png)

Well, it's not as awful, but neither it is not really good. They are looking pretty cool in not very dark areas, but in dark, they are turning into something like "sparks on the screen". More of that, "sparks" will be notably awful _(or awfully notable)_ on 640x400 emulation resolution, especially on middle/far distance. And this should not happen.

`EXITDOOR` was inspired from Doom 3, where some massive doors having highlighted red lights. But again, red color there is bright, so those doors are supposed to have a b-maps. Here, in D1/2, it's not quite clear - is it light or is it...what? And after making a fresh look, it is obvious that b-map here looking odd ([screenshot](http://priscree.ru/img/c4c99f926351ba.png)).

As about `TEKWALL2` and `TEKWALL5`, I need to think a little more before rejecting. Despite of texture's size (128x128), both these textures are not often guests in whole D1, and can be found only in few maps of Episode 1 and 2 (and Map 3 in Press Beta). I've also liked the idea of having only red light, it's like "oh, we have a demon invasion. Turn off all systems, it's a Foxtrot Uniform!". Let's call it a little exception. :Ъ

**Comment by JNechaevsky** [comment]
Actually, to get my thoughts right, have taken a pic today which shows that even few single red lights is not as bad as it may be. :)

![1538842548818](https://user-images.githubusercontent.com/21193394/46573822-168d2080-c9a3-11e8-83bf-dcf909319385.png)
