### ISSUE TITLE
Extra bloody god mode faces

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#85]
Not for implementation, just wondering how could they look.

**STFx1**
![stfst11g](https://user-images.githubusercontent.com/21193394/46532079-355abc80-c8a8-11e8-9ed2-84eea44c217b.png) ![stfevl1g](https://user-images.githubusercontent.com/21193394/46532077-34c22600-c8a8-11e8-89e0-741b3cfc07ec.png) ![stfkill1g](https://user-images.githubusercontent.com/21193394/46532078-355abc80-c8a8-11e8-9e9a-68e1d42fe4a5.png)

**STFx2**
![stfst21g](https://user-images.githubusercontent.com/21193394/46532105-473c5f80-c8a8-11e8-98e6-e5248538ef1e.png) ![stfevl2g](https://user-images.githubusercontent.com/21193394/46532103-473c5f80-c8a8-11e8-96a1-88abb7552fa4.png) ![stfkill2g](https://user-images.githubusercontent.com/21193394/46532104-473c5f80-c8a8-11e8-9fc3-0c1a3cdd6439.png)

**STFx3**
![stfst31g](https://user-images.githubusercontent.com/21193394/46544261-cf802c00-c8cb-11e8-885e-505895137bf4.png) ![stfevl3g](https://user-images.githubusercontent.com/21193394/46532126-58856c00-c8a8-11e8-9434-c0a2e1563c14.png) ![stfkill3g](https://user-images.githubusercontent.com/21193394/46532127-58856c00-c8a8-11e8-9a75-8cfc3804db06.png)

**STFx4**
![stfst41g](https://user-images.githubusercontent.com/21193394/46535042-d9496580-c8b2-11e8-9afe-f0871a875188.png) ![stfevl4g](https://user-images.githubusercontent.com/21193394/46532210-9aaead80-c8a8-11e8-865a-2663a142f5bc.png) ![stfkill4g](https://user-images.githubusercontent.com/21193394/46532211-9aaead80-c8a8-11e8-887f-0dfe9b3f70a6.png)

PNGs: [godfaces.zip](https://github.com/JNechaevsky/russian-doom/files/2450913/godfaces.zip)

**Comment by JNechaevsky** [comment]
Slightly better.

![stfst31g](https://user-images.githubusercontent.com/21193394/46532128-591e0280-c8a8-11e8-9eb5-065d83e70177.png) -> ![stfst31g](https://user-images.githubusercontent.com/21193394/46544261-cf802c00-c8cb-11e8-885e-505895137bf4.png)

![stfst41g](https://user-images.githubusercontent.com/21193394/46532212-9b474400-c8a8-11e8-9563-b360b95a574e.png) -> ![stfst41g](https://user-images.githubusercontent.com/21193394/46535042-d9496580-c8b2-11e8-9afe-f0871a875188.png)

**Comment by fabiangreffrath** [comment]
What is this supposed to achieve?

**Comment by JNechaevsky** [comment]
Nothing in general, just thinking how could these faces will look as an addition to current the rampage/grinning golden eyed face while in god mode. Maybe it's worth to try to implement, maybe not, I really don't know. Not everything may be that easy in the status bar code.

**Comment by JNechaevsky** [comment]
Hmmm. That's... hilarious, or unusual. Not sure what is the right word here and what is my first impressions. Anyway, some pixel perfection is still needed, especially on STFx3's eyebrows.
- https://www.youtube.com/watch?v=64ImtSauHlQ

Good thing, to get all of them working, all I have to do is to comment out this:
```
        // invulnerability
        if ((plyr->cheats & CF_GODMODE) || plyr->powers[pw_invulnerability])
        {
            // priority = 4; <---
            // painoffset = 0; <---
            faceindex = ST_GODFACE;
            st_facecount = 0;
        }
```

But obliviously, deeper testing is needed.
