### ISSUE TITLE
Too fast loading in uncapped mode?

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#86]
@fabiangreffrath, take a look please, this is also happening in Crispy. Steps to reproduce:

1. Start game, warp to any level with lovering/raising platform.
2. Stand near such platform.
3. Save game, then quit game.
4. Load saved game by `-loadgame x`.
5. After loading there will be a very short notable moment, where you can see that platform in initial height.

To be more clear, a video example of both RD and Crispy (with some slowdowns), on my beloved MAP18.

- https://youtu.be/3UOOp938Ku4

This seems to be happening only while first loading by using `-loadgame` in `uncapped` mode. By loading saved game from game menu everything seems to be fine. I have checked - wiping does not matter.

Possible quick&dirty solution is... 

**g_game.c @@ G_DoLoadLevel**
```
    P_SetupLevel (gameepisode, gamemap, 0, gameskill);    
+++ // [JN] Sleep for a moment, let the level be properly loaded in uncapped mode.
+++ I_Sleep (15);
    displayplayer = consoleplayer;		// view the guy you are playing    
    gameaction = ga_nothing; 
    Z_CheckHeap ();
```

**Comment by JNechaevsky** [comment]
P.S. @bradharding, DR seems to be fine.

**Comment by bradharding** [comment]
Thanks for letting me know. I'm not sure what the solution would be for this, but I don't think using `I_Sleep()` would help in this instance. `P_SetupLevel()` will run in its entirety regardless of what's on the next line. I would investigate the use of `interpfloorheight` somewhere.

**Comment by JNechaevsky** [comment]
Thanks, Brad! Searching for `interpfloorheight` brings me to `R_MaybeInterpolateSector`:

```
        // Only if we moved the sector last tic.
        sector->oldgametic == gametic - 1)
```

Removing `- 1` seems to solving this case, but also removing interpolation. Hmph. Definitely not right way to go, but have no other ideas. Maybe I'm on wrong track at all.

**Comment by bradharding** [comment]
Maybe initialize `oldgametic` for each sector in `p_setup.c` to `-1`? I'm not sure, because DR doesn't use `oldgametic`.

**Comment by fabiangreffrath** [comment]
That did the trick, thanks Brad!

**Comment by JNechaevsky** [comment]
Awesome, thanks for help!
