### ISSUE TITLE
E4M8 having too loud sounds

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#89]
That's because of:
```
    if ((gamemap != 8 || gamemode == commercial) && approx_dist > 
        S_CLIPPING_DIST)
    {
        return 0;
    }
```

@fabiangreffrath, AFAIR, we have investigated S_CLIPPING bug and fixed it. Loud sounds are okay on Episode 1, 2 and 3, but on E4M8 it's pretty notable, when all the monsters making noise far from player. Maybe we should make full volume only for Barons, Cyberdemon and Spider on 8th maps?

**Comment by fabiangreffrath** [comment]
Wait a minute. The fix was not to play at full volume on Doom 2 MAP08, right? And now you suggest to fix not *all* monsters on Doom 2 ExM8 to play at full volume but only "boss" monsters?

**Comment by JNechaevsky** [comment]
Yeah, something like that. Or -- simply play all sounds normally on E4M8. Just try to play it normally and pay doubled attention to the sounds, it's distance. Does not feels good.

**Comment by fabiangreffrath** [comment]
I see. Do you suggest a fix based on episode/map or on monster type?

**Comment by JNechaevsky** [comment]
That's a really good question. I think... Per-monster could be more interesting, for example - we really don't need to hear Lost Souls on E2M8.  But this approach will probably require more conditions? So far, following monsters should b full-volumed on following maps:

- E1M8: Barons of Hell
- E2M8: Cyberdemon
- E3M8: Spider Mastermind
- E4M8: Spider Mastermind

Just not having full volume on E4M8 seems to be easiest way.

**Comment by JNechaevsky** [comment]
... and the question of the day: are only sounds from monster's mouth should be full-volumed? I.e., should be Cyberdemon rocket attack sound be also full-volumed? Or Spider's chaingun?

I think - yes. Otherwise, it will be strange: we can hear Cyber's hoof sound from far side of the map. We can hear his pain and death sound. But if we will not hear his attack sound - I think it is not very correct, right?

**Comment by JNechaevsky** [comment]
Seems to be so?

s_sound.c @@ S_AdjustSoundParams
```
    // volume calculation
    if (approx_dist < S_CLOSE_DIST)
    {
        *vol = snd_SfxVolume;
    }
+++ else if (gamemap == 8 && logical_gamemission == doom &&
+++ (source->type == MT_BRUISER || source->type == MT_CYBORG || source->type == MT_SPIDER))
    {
        if (approx_dist > S_CLIPPING_DIST)
        {
            approx_dist = S_CLIPPING_DIST;
        }
```

**Edit:** slightly corrected. Also, it is nice how mosnter's sounds still have a little "diminishing" effect, i.e. 
they are not always in full volume.
**Edit 2:** not working for Bruisers, Cyber's firing sound is not played in very far distance. Doh.

**Comment by fabiangreffrath** [comment]
This is awful! I think, when this strange "boss level at full volume" feature was introduced there was no idea of a future Doom 2 and not even of an Ultimate Doom episode 4. So, in my opinion, it is (1) safest and (2) easiest and (3) probably reflects the original authors' idea best to restrict this on episode 4 just as we do for Doom 2.

**Comment by JNechaevsky** [comment]
After few my last attempts & thoughts of _"how else we can make all the things harder"_, I think I'm happily agree with all your three points.
