### ISSUE TITLE
[DOS] Implement "-noflats" command line parameter to render flats as single color

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#92]
I think I can emulate this feature from Doom Alpha. It also increases performance a little bit, since it it possible to disable some calculations, at least `-timedemo` in DOS version shows higher average fps.

Excepted result: 

![default](https://user-images.githubusercontent.com/21193394/48049692-82d08f00-e1b0-11e8-995d-2625144a906f.png)

Also possible to implement this in Windows version, but the necessity is doubtful, though it looks cool.

**Comment by fabiangreffrath** [comment]
Interesting! How are you going to determine the solid color that is to replace each flat?

**Comment by JNechaevsky** [comment]
Quite simple, it's the color of fist top-left pixel of the texture. In the code it looks like this:

void R_DrawSpan

```
    // We do not check for zero spans here?
    count = ds_x2 - ds_x1;

    do
    {
        // Calculate current texture index in u,v.
        // [crispy] fix flats getting more distorted the closer they are to the right
---    ytemp = (ds_yfrac >> 10) & 0x0fc0;
---    xtemp = (ds_xfrac >> 16) & 0x3f;
+++     // [JN] use static values
+++     xtemp = 0;
+++     xtemp = 0;
        spot = xtemp | ytemp;

        // Lookup pixel from flat texture tile,
        //  re-index using light/colormap.
        *dest++ = ds_colormap[ds_source[spot]];

        // position += step;
---        ds_xfrac += ds_xstep;
---        ds_yfrac += ds_ystep;
+++        // [JN] don't do these calculations:
+++        // ds_yfrac += ds_ystep;
+++        // ds_yfrac += ds_ystep;

    } while (count--);
```

It is also possible to disable diminished lighting calculation, probably will also give few bits of performance, but visual result is quite ugly.

**Comment by JNechaevsky** [comment]
Take a try to do this in Crispy and run few `-timedemo` tests with and without this edit. You probably will have a 15-20 more average fps with single colored flats. In DOS, though, my very first `-timedemo` trst are quite fun: on some maps single color gives +10 fps, in some +50 fps.

In more short words: should I suggest in for Crispy, maybe as a hidden config file variable? It's really not necessary on modern PCs, but could be interesting for some technical stuff like fps benchmarking.

**Comment by fabiangreffrath** [comment]
> should I suggest in for Crispy

Sure, why not. ;) Maybe as a fun addition to the GOOBERS cheat code.

**Comment by JNechaevsky** [comment]
Excellent, thanks! I'll move on to Crispy tracker in the evening, guess I have few more ideas about it.

**Comment by JNechaevsky** [comment]
**Fabian**, just want to ask last question here. Do you know how to do this trick?

![untitled-1](https://user-images.githubusercontent.com/21193394/48077688-eed6e580-e1f8-11e8-8edf-37b8c949b49d.png)

**Comment by fabiangreffrath** [comment]
Hm, what is this supposed to show? 23 days, 55 hours, 8 minutes and 16 seconds? Honestly, to me it looks more like a bug than a trick. But if you want proper time display from `leveltime`, sure I can do that.

**Comment by JNechaevsky** [comment]
Meanwhile, in DOS version... It might be a good idea to make a separate function, instead of having a bunch of `if ...` condition for disabling some things. Optimized and significantly shortened version of current [R_DrawSpan](https://github.com/JNechaevsky/russian-doom/blob/master/src_dos/r_draw.c#L479) in RD for DOS:

**r_draw.c**
```
//
// [JN] Draws the actual span without texture.
// TODO: same for low detail version.
void R_DrawSpanNoTexture (void)
{
    byte*   dest;
    int     i;
    int     dsp_x1, dsp_x2;
    int     countp;

#ifdef RANGECHECK
    if (ds_x2 < ds_x1 || ds_x1<0 || ds_x2>=SCREENWIDTH || (unsigned)ds_y>SCREENHEIGHT)
    I_Error( "R_DrawSpan: %i Є %i ў %i", ds_x1,ds_x2,ds_y);
#endif

    for (i = 0; i < 4; i++)
    {
        outp (SC_INDEX+1, 1<<i); // [JN] what is this ?!
        dsp_x1 = (ds_x1-i)/4;

        if (dsp_x1*4+i < ds_x1)
        dsp_x1++;

        dest = destview + ds_y*80 + dsp_x1;
        dsp_x2 = (ds_x2-i)/4;
        countp = dsp_x2 - dsp_x1;

        if (countp < 0)
        continue;

        do
        {
            *dest++ = ds_colormap[ds_source[0]];
        }
        while (countp--);
    }
}
```

The results of `-timedemo` are staggering. I have run Doom 1 `DEMO3` three times with and without textures. Average FPS (indication was implemented in commit https://github.com/JNechaevsky/russian-doom/commit/f0803bbfbd8fa34da30aa42cf91b16d7c4cf6278):

- With textures: 109 / 107 / 108
- W/o textures: 138 / 138 / 136

**Comment by JNechaevsky** [comment]
@fabiangreffrath, no-no-no, I was just asking. The trick is to show indication of more than three pairs of `00:00:00`. You can count such a huge time this way:

- Start Crispy with `-timedemo demo1` cmd line parameter
- While demo is running, start new game
- Minimize game window. Screen renderer will be deactivated, so CPU can count ticks much, much faster.
- Restore game windows after a ~5 minutes and take a look at the level time on automap / intermission screen.

That's the trick. But there is one odd thing: if you'll save the game and load it again, total time will be dropped to three only pairs like `00:00:00`. I may be wrong a liitle bit, because haven't tested it properly yes, but if you wish, we can investigate it. Really have no idea, is it worth attention or not, so it's at your discretion.

**Comment by JNechaevsky** [comment]
Working low-res version:

```
//
// Again..
//
void R_DrawSpanLowNoTexture (void)
{
    byte*   dest; 
    int     i;
    int     dsp_x1, dsp_x2;
    int     countp;

#ifdef RANGECHECK
    if (ds_x2 < ds_x1 || ds_x1<0 || ds_x2>=SCREENWIDTH || (unsigned)ds_y>SCREENHEIGHT)
    I_Error( "R_DrawSpan: %i Є %i ў %i", ds_x1,ds_x2,ds_y);
#endif 

    for (i = 0; i < 2; i++)
    {
        outp (SC_INDEX+1, 3<<(i*2)); // [JN] again, what is this ?!
        dsp_x1 = (ds_x1-i)/2;

        if (dsp_x1*2+i < ds_x1)
        dsp_x1++;

        dest = destview + ds_y*80 + dsp_x1;
        dsp_x2 = (ds_x2-i)/2;
        countp = dsp_x2 - dsp_x1;

        if (countp < 0)
        continue;

        do
        {
            *dest++ = ds_colormap[ds_source[0]];
        }
        while (countp--);
    }
}
```

**Comment by JNechaevsky** [comment]
The results of `-timedemo` average fps of Ultimate Doom `DEMO1` low detail, three runs for each mode:
- With textures: 130 / 129 / 128
- W/o textures: 182 / 183 / 179

Insanity...

**Comment by fabiangreffrath** [comment]
Regarding proper multi-hour time display in the intermission screen:
```
--- a/src/doom/wi_stuff.c
+++ b/src/doom/wi_stuff.c
@@ -751,7 +751,13 @@ WI_drawTime
            if (div==60 || t / div)
                V_DrawPatch(x, y, colon);

-       } while (t / div);
+       } while (t / div && div < 3600);
+
+       // [crispy] print at most hhhh:mm:ss
+       if ((n = (t / div)))
+       {
+           x = WI_drawNum(x, y, n, -1);
+       }
     }
     else
     {
```

**Comment by JNechaevsky** [comment]
Maybe using a `HHHH` will be more clear than `DD`, since we can't print letter "D". Hmph.

**Comment by fabiangreffrath** [comment]
We shouldn't display days, only hours. `hh:mm:ss` is already an established format for displaying times, whereas `dd:hh:mm:ss` (or even `ddDhh:mm:ss`) is not.
