### ISSUE TITLE
Monsters don't become faster on the Black Plague skill level in Heretic

### ISSUE THREAD

**Issue by mykola-ambar** [Russian-Doom/russian-doom#95]
In Heretic, Black Plague skill seems to only change monsters' reaction time to 0, while their projectile speeds and state durations remain identical to lower skill levels.

**Comment by JNechaevsky** [comment]
Hi @mykola-ambar and sorry for such a late reply, I'm really not active on RusDoom last time.
Just double checked, monsters movement and projectile speed seems to be fine and different on 1-4 | 5 | 6 skill levels, when starting just a new game and when starting a new game with different skill level after previous new game was started.

Which steps you have to done to reproduce it?

**Comment by mykola-ambar** [comment]
To reproduce it, just select New Game -> Black Plague Possesseth Thee or Quicketh Art Thee, Foul Wraith and look at how fast monsters' projectiles are. 
I made a short video comparing projectile speeds on skill 5/6 in Russian Heretic and skill 5 in Chocolate Heretic: https://streamable.com/ijtn3
The projectiles in Chocolate Heretic are much faster. This is from yesterday's (25.11.2018) 3.1 version.

**Comment by JNechaevsky** [comment]
I'm wildly sorry for it takes almost a month to fix it. For now, projectiles speed on 5th and 6th skill are fixed (and they are same, not sure speed up even more on 6th is a good idea). Need also check Hexen, I'm afraid there is a same bug.

Thanks again, I'll gladly add your name and/or nick name (or whatever you'll preffer) to acknowledment section!
